Repository redaxo/redaxo, pull requests merged in 2019-11, with the labels that each got.

#2980 Added cs-fixing GithubAction
  .github/workflows/csfix.yml
Labels: automerge

#2983 cronjob/optimize_tables: fix escaping, add message
  redaxo/src/addons/cronjob/plugins/optimize_tables/lib/cronjob.php
Labels: automerge

#2984 try to fix "Unexpected symbol: '$keyword_found'" error
  .github/workflows/csfix.yml
Labels: automerge

#2939 added rex-linting as a GithubAction
  .github/workflows/default.config.yml.github-action.diff
  .github/workflows/push.yml
  .travis.yml
Labels: automerge

#2987 update csfix.yml to peter-evans/create-pull-request@v1.6.1
  .github/workflows/csfix.yml
Labels: automerge

#2988 use correct php-version for style-fixing
  .github/workflows/csfix.yml
Labels: automerge

#2989 use GithubActions for psalm-analysis
  .github/workflows/push.yml
  .travis.yml
Labels: automerge

#2990 use GithubActions for phpstan-analysis
  .github/workflows/push.yml
  .travis.yml
Labels: automerge

#2991 use --no-progress for phpstan
  .github/workflows/push.yml
Labels: automerge

#2993 use global require to not modify files within the project
  .github/workflows/csfix.yml
Labels: automerge

#2947 addSlice() Methode erstellt
  redaxo/src/addons/structure/plugins/content/lib/service_slice.php
Labels: automerge

#2994 Allow failure in phpstan build
  .github/workflows/push.yml
Labels: automerge

#2995 Optimize csfixing action for speed
  .github/workflows/csfix.yml
Labels: automerge

#2996 Added GithubAction to check codestyle
  .github/workflows/push.yml
  redaxo/src/addons/debug/lib/logger_debug.php
  redaxo/src/addons/install/lib/api_core_update.php
  redaxo/src/addons/install/lib/webservice.php
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
  redaxo/src/addons/mediapool/lib/media.php
  redaxo/src/addons/mediapool/lib/media_category.php
  redaxo/src/addons/mediapool/lib/service_media_category.php
  redaxo/src/addons/metainfo/functions/function_metainfo.php
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/metainfo/lib/handler/media_handler.php
  redaxo/src/addons/structure/lib/category.php
  redaxo/src/addons/structure/lib/structure_element.php
  redaxo/src/addons/structure/plugins/content/lib/article_slice.php
  redaxo/src/addons/users/lib/role.php
  redaxo/src/core/lib/api_function.php
  redaxo/src/core/lib/be/controller.php
  redaxo/src/core/lib/be/navigation.php
  redaxo/src/core/lib/be/page.php
  redaxo/src/core/lib/console/application.php
  redaxo/src/core/lib/exception.php
  redaxo/src/core/lib/extension_point.php
  redaxo/src/core/lib/form/form.php
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/login/user.php
  redaxo/src/core/lib/sql/schema_dumper.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/sql/table.php
  redaxo/src/core/lib/util/i18n.php
  redaxo/src/core/lib/util/logger.php
  redaxo/src/core/lib/util/string.php
  redaxo/src/core/lib/util/timer.php
  redaxo/src/core/lib/util/validator.php
  redaxo/src/core/lib/view.php
Labels: automerge

#2999 csfix GithubAction: check for status code instead of output
  .github/workflows/csfix.yml
Labels: automerge

#3000 GithubAction: try to fix 'fix-cs' action
  .github/workflows/csfix.yml
Labels: automerge

#3001 csfix GithubAction: simplify
  .github/workflows/csfix.yml
Labels: automerge, fix-cs

#3002 csfix GithubAction: simplify
  .github/workflows/csfix.yml
Labels: automerge

#3005 ignore remaining phpstan errors
  .github/workflows/push.yml
  phpstan.neon.dist
Labels: automerge

#3015 docs: remove forum section
  README.de.md
  README.md
Labels: automerge

#3012 Structure: remove '..' level up icon (#774)
  redaxo/src/addons/structure/pages/index.php
Labels: automerge

#3017 Added editor_basepath property
  redaxo/src/core/default.config.yml
  redaxo/src/core/lib/util/editor.php
Labels: Core, Developer Experience (DX), Enhancement

#3019 structure: fix notice
  redaxo/src/addons/structure/lib/select_template.php
Labels: Structure

#3020 setup: only allow https settings via https call
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/pages/setup.php
Labels: Core, Developer Experience (DX), Enhancement, automerge

#3023 psalm: activate more errors
  psalm.xml
Labels: automerge

#3021 psalm: activate undef var errors
  psalm.xml
  redaxo/src/addons/cronjob/lib/manager_sql.php
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#3025 psalm: activate more errors
  psalm.xml
Labels: automerge

#3018 dependabot: added config
  .dependabot/config.yml
Labels: Developer Experience (DX), Enhancement, automerge

#3032 backup: update default filename
  redaxo/src/addons/backup/lib/cronjob.php
  redaxo/src/addons/backup/pages/export.php
Labels: Backup, Enhancement

#3033 section Fragment angepasst, kann Attribute aufnehmen
  redaxo/src/core/fragments/core/page/section.php
Labels: automerge

#3035 Verfügbare Packages / AddOns durchsuchbar machen
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/pages/packages.php
Labels: Feature, Installer

#3037 setup: remove hsts checkbox
  redaxo/src/core/boot.php
  redaxo/src/core/default.config.yml
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/nl_nl.lang
  redaxo/src/core/lang/sv_se.lang
  redaxo/src/core/pages/setup.php
Labels: Core, Enhancement
