Repository redaxo/redaxo, pull requests merged in 2019-08, with the labels that each got.

#2799 Media Manager :: Hilfe überarbeitet
  redaxo/src/addons/media_manager/README.de.md
  redaxo/src/addons/media_manager/README.md
  redaxo/src/addons/media_manager/help.php
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/addons/media_manager/pages/overview.php
Labels: Developer Experience (DX), User Experience (UX)

#2824 more specific phpdocs
  redaxo/src/core/lib/login/user.php
Labels: Needs revision

#2828 Setup Kodiak Bot
  .kodiak.toml
Labels: Awaiting feedback

#2831 added phpdoc
  redaxo/src/addons/metainfo/lib/handler/handler.php
Labels: automerge

#2830 Refactored REX_FORM_ERROR_VIOLATE_UNIQUE_KEY zur rex_form Klassenkons…
  redaxo/src/addons/media_manager/pages/types.php
  redaxo/src/core/lib/form/form.php
Labels: automerge

#2833 kodiak: Merge-Titel und -Beschreibung angepasst
  .kodiak.toml
Labels: automerge

#2829 SCSS: strip_comments option wird nicht mehr unterstützt
  redaxo/src/addons/be_style/lib/scss_compiler.php
Labels: automerge

#2832 Added phpdoc
  redaxo/src/addons/metainfo/lib/handler/handler.php
Labels: automerge

#2838 rex_metainfo_table_manager konstanten definieren
  redaxo/src/addons/metainfo/boot.php
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/metainfo/lib/table_expander.php
  redaxo/src/addons/metainfo/lib/table_manager.php
Labels: automerge

#2821 rex_article_content: Einheitliches Format für createdate/updatedate
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
Labels: automerge

#2835 Revert "be_style: rex_copy() return wert während installation auswerten"
  redaxo/src/addons/be_style/install.php
Labels: automerge

#2841 Setup: "Nicht angemeldet" in Header entfernt
  redaxo/src/core/layout/top.php
Labels: automerge

#2836 Vorlage für .gitignore
  .gitignore.example
  redaxo/bin/release
Labels: automerge

#2842 Metainfo: Deprecation-Anmerkungen korrigiert
  redaxo/src/addons/metainfo/boot.php
Labels: automerge

#2844 PHPMailer - README Übersetzung - Englisch
  redaxo/src/addons/phpmailer/README.de.md
  redaxo/src/addons/phpmailer/README.md
Labels: automerge

#2843 EP CAT_MOVED: clang_id -> clang
  redaxo/src/addons/structure/lib/service_category.php
Labels: automerge

#2848 Debug code entfernt
  redaxo/src/addons/mediapool/pages/sync.php
Labels: automerge

#2847 Include-pfade vereinfacht
  redaxo/src/addons/metainfo/functions/function_metainfo.php
Labels: automerge

#2851 phpdocs ergänzt
  redaxo/src/core/lib/form/elements/select.php
Labels: automerge

#2852 Phpdoc ergänzt
  redaxo/src/core/lib/form/elements/element.php
Labels: automerge

#2849 Metainfo inputs: datetime getters funktionieren jetzt
  redaxo/src/addons/metainfo/lib/input/datetime.php
Labels: automerge

#2850 rex_input: phpdocs ergänzt
  redaxo/src/addons/metainfo/lib/input.php
Labels: automerge

#2853 Metainfo: attribut escaping ergänzt
  redaxo/src/addons/metainfo/lib/input.php
Labels: Security, automerge

#2854 Init $RETURN
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
Labels: automerge

#2860 unset() undefined var
  redaxo/src/addons/structure/lib/service_article.php
Labels: automerge

#2858 fixed psalm warning in backend_login
  redaxo/src/core/lib/login/login.php
Labels: automerge

#2857 fix psalm warnings in rex::getVersionHash()
  redaxo/src/core/lib/rex.php
Labels: automerge

#2855 Added: debug-confirm Alert message
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/pages/system.settings.php
Labels: automerge

#2861 fix psalm warning in be_controller
  redaxo/src/core/lib/be/controller.php
Labels: automerge

#2856 inline rex_input::factory() into call-sites (and deprecate it)
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/metainfo/lib/input.php
  redaxo/src/addons/metainfo/lib/input/datetime.php
Labels: automerge

#2864 Fix phpdoc
  redaxo/src/core/lib/list.php
Labels: automerge

#2865 added phpdocs
  redaxo/src/core/lib/packages/addons/manager.php
Labels: automerge

#2866 Simplify
  redaxo/src/addons/structure/lib/linkmap/renderer.php
Labels: automerge

#2870 fix phpstan warning bzgl. $type_id
  redaxo/src/addons/media_manager/pages/effects.php
Labels: automerge

#2871 fix phpstan warning bzgl. $template_select
  redaxo/src/addons/structure/pages/index.php
Labels: automerge

#2868 fixed phpstan warning bzgl. parent_id
  redaxo/src/addons/structure/lib/service_article.php
Labels: automerge

#2869 fix phpstan warnings bzgl. templates
  redaxo/src/addons/structure/lib/service_category.php
Labels: automerge

#2837 add code of conduct
  .github/CODE_OF_CONDUCT.md
Labels: automerge

#2818 Added psalm static analysis
  .travis.yml
  psalm.xml
  redaxo/src/core/lib/sql/util.php
  redaxo/src/core/lib/util/string.php
Labels: automerge

#2877 use stable psalm release
  .travis.yml
Labels: automerge

#2880 Clang-id nicht unset()‘ten. Unnötiger 3. zustand
  redaxo/src/core/pages/system.clangs.php
Labels: automerge

#2881 If Bedingungen vereinfacht
  redaxo/src/addons/mediapool/pages/media.detail.php
Labels: automerge

#2884 Whoops: Safe-mode war nicht aktivierbar
  redaxo/src/core/lib/error_handler.php
Labels: Bug, Core, automerge

#2887 In cli nicht session_cache_limiter aufrufen
  redaxo/src/core/boot.php
Labels: automerge

#2888 Psalm: Dateien besser filtern
  phpstan-bootstrap.php
  psalm.xml
Labels: automerge

#2890 Setup: Early-Returns verwenden
  redaxo/src/core/pages/setup.php
Labels: automerge

#2889 CS für files im app-root auch checken
  .php_cs.dist
Labels: automerge
