Repository redaxo/redaxo, pull requests merged in 2020-03, with the labels that each got.

#3377 Setup: mit rex_context arbeiten
  redaxo/src/core/pages/setup.php
  redaxo/src/core/pages/setup.step1.php
  redaxo/src/core/pages/setup.step2.php
  redaxo/src/core/pages/setup.step3.php
  redaxo/src/core/pages/setup.step4.php
  redaxo/src/core/pages/setup.step5.php
  redaxo/src/core/pages/setup.step6.php
Labels: automerge

#3368 Installer: Optimierung für Windows
  redaxo/src/addons/install/lib/archive.php
Labels: Enhancement, Installer, automerge

#3379 PHPMailer Log Tab
  redaxo/src/addons/phpmailer/package.yml
  redaxo/src/addons/phpmailer/pages/log.php
  redaxo/src/addons/phpmailer/pages/system.log.phpmailer.php
Labels: automerge

#3382 docs für das refresh command
  redaxo/bin/refresh
Labels: Core, Developer Experience (DX), Enhancement, automerge

#3380 PHPMailer :: Debug-Output im Panel ausgeben
  redaxo/src/addons/phpmailer/pages/checkmail.php
Labels: Enhancement, PHPMailer, automerge

#3383 PHPMailer:: setzen der default Verschlüsselung
  redaxo/src/addons/phpmailer/package.yml
Labels: PHPMailer, automerge

#3375 Pre-Releases kennzeichnen in addon-verwaltung, installer, credits
  redaxo/src/addons/be_style/assets/css/styles.css
  redaxo/src/addons/be_style/scss/_icon.scss
  redaxo/src/addons/install/pages/packages.update.php
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lib/system_report.php
  redaxo/src/core/lib/util/validator.php
  redaxo/src/core/lib/util/version.php
  redaxo/src/core/pages/credits.php
  redaxo/src/core/pages/packages.php
  redaxo/src/core/pages/system.report.html.php
  redaxo/src/core/pages/system.settings.php
  redaxo/src/core/tests/util/version_test.php
Labels: automerge

#3385 Update vendors
  redaxo/src/core/composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/symfony/console/Application.php
  redaxo/src/core/vendor/symfony/console/Command/Command.php
  redaxo/src/core/vendor/symfony/console/Helper/Table.php
  redaxo/src/core/vendor/symfony/console/Style/SymfonyStyle.php
  redaxo/src/core/vendor/symfony/console/Tester/ApplicationTester.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/DateCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Cloner/Stub.php
  redaxo/src/core/vendor/symfony/var-dumper/Resources/functions/dump.php
  redaxo/src/core/vendor/symfony/yaml/Inline.php
Labels: automerge

#3386 PHPMailer::AutoTLS genauer erklärt
  redaxo/src/addons/phpmailer/README.de.md
  redaxo/src/addons/phpmailer/README.md
  redaxo/src/addons/phpmailer/lang/de_de.lang
  redaxo/src/addons/phpmailer/lang/en_gb.lang
  redaxo/src/addons/phpmailer/lang/es_es.lang
  redaxo/src/addons/phpmailer/lang/sv_se.lang
Labels: automerge

#3387 MP: Fallback für alte MM-Versionen entfernt
  redaxo/src/addons/mediapool/pages/media.detail.php
  redaxo/src/addons/mediapool/pages/media.list.php
Labels: Enhancement, Media Manager, automerge

#3388 Customizer :: Default settings nach package.yml
  redaxo/src/addons/be_style/plugins/customizer/install.php
  redaxo/src/addons/be_style/plugins/customizer/package.yml
Labels: automerge

#3391 Warnings: HTML nicht escapen
  redaxo/src/core/lib/error_handler.php
Labels: automerge

#3390 rex_category/rex_article: Int-Values wirklich als int
  redaxo/src/addons/structure/lib/structure_element.php
Labels: automerge

#3389 psalm: activate more errors
  phpstan.neon.dist
  psalm.xml
  redaxo/src/addons/mediapool/pages/media.detail.php
  redaxo/src/addons/mediapool/pages/media.list.php
  redaxo/src/addons/mediapool/pages/media.php
  redaxo/src/addons/mediapool/pages/structure.php
  redaxo/src/addons/mediapool/pages/sync.php
  redaxo/src/addons/mediapool/pages/upload.php
  redaxo/src/addons/metainfo/pages/content.metainfo.php
  redaxo/src/addons/metainfo/pages/field.php
  redaxo/src/addons/structure/functions/function_rex_category.php
  redaxo/src/addons/structure/plugins/content/pages/content.edit.php
  redaxo/src/addons/structure/plugins/content/pages/content.functions.php
  redaxo/src/addons/structure/plugins/content/pages/content.php
  redaxo/src/addons/structure/plugins/content/pages/modules.actions.php
  redaxo/src/addons/structure/plugins/content/pages/templates.php
  redaxo/src/core/pages/setup.step3.php
  redaxo/src/core/pages/setup.step4.php
  redaxo/src/core/pages/setup.step5.php
  redaxo/src/core/pages/setup.step6.php
Labels: automerge

#3378 Docker für lokale Entwicklung
  .dockerignore
  README.de.md
  README.md
  docker-compose.yml
Labels: Contributor Experience, Feature, automerge

#3392 tests: remove unnecessary file creation
  redaxo/src/addons/tests/bin/setup.php
Labels: automerge

#3394 Core-Versionen korrekt ausgeben
  redaxo/src/addons/install/pages/packages.update.php
Labels: automerge

#3395 Installer: Kompatibilität zu R5.7 wieder hergestellt
  redaxo/src/addons/install/lib/package/package_update.php
  redaxo/src/addons/install/package.yml
Labels: automerge

#3396 Added phpdoc
  redaxo/src/addons/install/lib/api/api_core_update.php
Labels: automerge

#3398 Installer: Markdown in älteren REDAXO-Versionen absichern
  redaxo/src/addons/install/pages/index.php
  redaxo/src/addons/install/pages/packages.add.php
  redaxo/src/addons/install/pages/packages.update.php
  redaxo/src/addons/install/pages/packages.upload.php
Labels: automerge

#3400 install: escape url parameter
  redaxo/src/addons/install/lib/api/api_package_delete.php
  redaxo/src/addons/install/lib/api/api_package_upload.php
Labels: automerge

#3401 Installer: $markdown-Variable verfügbar gemacht
  redaxo/src/addons/install/pages/index.php
Labels: automerge

#3399 Versions-Funktionen in rex_version verschoben
  psalm.xml
  redaxo/src/core/.phpstorm.meta.php
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/lib/rex.php
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/lib/system_report.php
  redaxo/src/core/lib/util/formatter.php
  redaxo/src/core/lib/util/string.php
  redaxo/src/core/lib/util/version.php
  redaxo/src/core/pages/system.settings.php
  redaxo/src/core/tests/util/string_test.php
  redaxo/src/core/tests/util/version_test.php
Labels: automerge

#3402 psalm: activate more errors
  psalm.xml
  redaxo/src/addons/cronjob/lib/manager.php
  redaxo/src/addons/install/lib/package/package_update.php
  redaxo/src/addons/media_manager/lib/effect_abstract.php
  redaxo/src/addons/media_manager/lib/media_manager.php
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/metainfo/lib/input.php
  redaxo/src/addons/users/boot.php
  redaxo/src/core/.phpstorm.meta.php
  redaxo/src/core/lib/base/factory_trait.php
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/login/user.php
  redaxo/src/core/lib/packages/manager.php
Labels: automerge

#3403 Normalizer direkt nutzen
  redaxo/src/core/composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/lib/util/string.php
  redaxo/src/core/vendor/composer/installed.json
Labels: automerge

#3404 rex_article_slice: Spalten umsortiert
  redaxo/src/addons/structure/plugins/content/install.php
Labels: automerge

#3405 Cache löschen: auch Opcache leeren
  redaxo/src/core/functions/function_rex_other.php
Labels: automerge

#3406 structure/content: assert-Warning vermeiden
  redaxo/src/addons/structure/plugins/content/pages/content.php
Labels: automerge

#3408 Installer: Absicherung in R<5.10 korrigiert
  redaxo/src/addons/install/pages/index.php
Labels: automerge

#3409 disable `html_errors`
  redaxo/src/core/boot.php
  redaxo/src/core/lib/error_handler.php
Labels: automerge

#3416 bootstrap-select: *.map-datei korrigiert
  redaxo/src/addons/be_style/vendor_files.php
Labels: automerge

#3415 Artikel-Funktionen korrigiert
  redaxo/src/addons/structure/plugins/content/pages/content.functions.php
Labels: automerge

#3418 Installer: Fehlendes Escaping ergänzt
  redaxo/src/addons/install/pages/packages.add.php
  redaxo/src/addons/install/pages/packages.upload.php
Labels: automerge

#3417 Slice-Message nicht verwerfen
  redaxo/src/addons/structure/plugins/content/pages/content.edit.php
Labels: automerge

#3422 Medienpool: assert-Warning vermeiden
  redaxo/src/addons/mediapool/pages/index.php
Labels: automerge

#3421 Module-Key: Korrekte Umgang mit leerem Key
  redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
Labels: automerge

#3426 Backup-Cronjob: Bessere Feldreihenfolge
  redaxo/src/addons/backup/lib/cronjob.php
Labels: automerge

#3428 PHPMailer-Readme kompatibel zu antiXss gemacht
  redaxo/src/addons/phpmailer/README.de.md
  redaxo/src/addons/phpmailer/README.md
Labels: automerge

#3430 psalm: activate PossiblyUndefinedMethod
  composer.json
  psalm.xml
Labels: automerge

#3431 PhpStorm-Settings optimiert
  .idea/inspectionProfiles/Project_Default.xml
  .idea/redaxo.iml
Labels: automerge

#3432 suggest to insert stacktrace / whoops
  .github/ISSUE_TEMPLATE/---bug-report.md
Labels: automerge

#3433 fix rex_module::getKey()
  redaxo/src/addons/structure/plugins/content/lib/api_module.php
  redaxo/src/addons/structure/plugins/content/lib/api_template.php
Labels: Bug, Structure, automerge

#3434 console: wrong user - no hard exit
  redaxo/src/core/lib/console/application.php
Labels: Console, Enhancement, automerge

#3436 REX_MODULE_KEY-Ersetzung vereinfacht
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
Labels: automerge

#3435 Update AntiXSS und escapte script-tags erlauben
  redaxo/src/core/composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/lib/util/string.php
  redaxo/src/core/tests/util/markdown_test.php
  redaxo/src/core/tests/util/string_test.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/voku/anti-xss/CHANGELOG.md
  redaxo/src/core/vendor/voku/anti-xss/src/voku/helper/AntiXSS.php
  redaxo/src/core/vendor/voku/portable-ascii/CHANGELOG.md
  redaxo/src/core/vendor/voku/portable-ascii/src/voku/helper/ASCII.php
  redaxo/src/core/vendor/voku/portable-utf8/CHANGELOG.md
  redaxo/src/core/vendor/voku/portable-utf8/src/voku/helper/UTF8.php
Labels: automerge

#3437 Module: Einfache Var-Ersetzungen vor den richtigen REX_VARs
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
Labels: automerge

#3429 Added phpdoc
  redaxo/src/core/lib/packages/addons/addon.php
Labels: automerge

#3438 fix phpdoc
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#3441 Fix phpdoc
  redaxo/src/core/lib/util/logger.php
Labels: automerge

#3442 Fix phpdoc
  redaxo/src/core/lib/packages/addons/addon.php
Labels: automerge

#3440 Fix phpdocs
  redaxo/src/core/lib/packages/addons/interface.php
  redaxo/src/core/lib/packages/plugins/plugin.php
Labels: automerge

#3444 console: sync packages with filesystem
  redaxo/src/core/lib/console/package/activate.php
  redaxo/src/core/lib/console/package/deactivate.php
  redaxo/src/core/lib/console/package/delete.php
  redaxo/src/core/lib/console/package/install.php
  redaxo/src/core/lib/console/package/uninstall.php
  redaxo/src/core/pages/packages.php
Labels: Bug, Console, Core, automerge

#3445 Fix docs, add psalm annotations
  composer.json
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/login/user.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/var/var.php
Labels: automerge

#3443 Fix types
  redaxo/src/core/lib/packages/addons/addon.php
Labels: automerge

#3446 psalm: activate more errors
  psalm.xml
  redaxo/src/addons/media_manager/lib/media_manager.php
  redaxo/src/addons/mediapool/boot.php
  redaxo/src/addons/structure/boot.php
  redaxo/src/addons/structure/plugins/content/boot.php
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/login/complex_perm.php
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#3448 rex_sql_table: Teils falsche Spaltenreihenfolge bei ensureGlobalColumns
  redaxo/src/core/boot.php
  redaxo/src/core/lib/sql/table.php
  redaxo/src/core/tests/sql/sql_table_test.php
Labels: Bug, Core, automerge

#3453 Addonverwaltung: Whoops vermeiden, wenn Version nicht gesetzt
  redaxo/src/core/pages/packages.php
Labels: automerge

#3455 setDefaultSaveValue akzeptiert auch null
  redaxo/src/core/lib/form/elements/element.php
Labels: automerge

#3459 fix accesskey shortcuts
  redaxo/src/addons/mediapool/package.yml
  redaxo/src/addons/mediapool/pages/sync.php
  redaxo/src/core/assets/standard.js
Labels: Bug, Core, Mediapool

#3460 structure: wrong i18n keys
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/plugins/content/package.yml
  redaxo/src/addons/structure/plugins/content/pages/templates.php
Labels: Bug, Structure, automerge

#3450 Installer: added rex_install
  redaxo/src/addons/install/lib/install.php
  redaxo/src/addons/install/package.yml
Labels: Add to Docs, Feature, Installer, automerge

#3461 Update vendors
  psalm.xml
  redaxo/src/addons/phpmailer/composer.lock
  redaxo/src/addons/phpmailer/package.yml
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/README.md
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/VERSION
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/language/phpmailer.lang-da.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/PHPMailer.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/POP3.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/SMTP.php
  redaxo/src/addons/tests/composer.lock
  redaxo/src/addons/tests/vendor/phpspec/prophecy/CHANGES.md
  redaxo/src/addons/tests/vendor/phpspec/prophecy/src/Prophecy/PhpDocumentor/ClassTagRetriever.php
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/voku/portable-ascii/CHANGELOG.md
  redaxo/src/core/vendor/voku/portable-ascii/src/voku/helper/ASCII.php
Labels: automerge

#3465 Fix create:user via console
  redaxo/src/core/install.php
  redaxo/src/core/lib/console/user/create.php
Labels: Bug, Core

#3464 docs: fix toc position
  redaxo/src/addons/be_style/package.yml
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/package.yml
  redaxo/src/addons/be_style/plugins/redaxo/scss/_docs.scss
Labels: Design / CSS, automerge

#3475 actions: start mysql manually
  .github/workflows/push.yml
Labels: automerge

#3474 rex_sql_table: column sorting korrigiert
  redaxo/src/core/lib/sql/table.php
  redaxo/src/core/tests/sql/sql_table_test.php
Labels: automerge

#3462 Added visual regression testing
  .github/tests-visual/index.png
  .github/tests-visual/login.png
  .github/tests-visual/visual-record.js
  .github/workflows/visual-tests.yml
  .gitignore
  redaxo/src/addons/tests/bin/setup.php
Labels: Core, Developer Experience (DX), automerge

#3473 Unit-Tests nicht mit ins Release
  redaxo/bin/release
Labels: automerge

#3477 fix package phpdoc
  redaxo/src/addons/install/lib/command/list.php
  redaxo/src/addons/media_manager/lib/effects/effect_filter_blur.php
  redaxo/src/addons/media_manager/lib/effects/effect_filter_brightness.php
  redaxo/src/addons/media_manager/lib/effects/effect_filter_colorize.php
  redaxo/src/addons/media_manager/lib/effects/effect_filter_contrast.php
  redaxo/src/addons/phpmailer/lib/system_setting_phpmailer_errormail.php
  redaxo/src/core/pages/system.clangs.php
Labels: automerge

#3476 psalm: activate InvalidOperand
  psalm.xml
  redaxo/src/addons/cronjob/lib/manager_sql.php
  redaxo/src/addons/cronjob/update.php
  redaxo/src/addons/install/pages/packages.update.php
  redaxo/src/addons/media_manager/lib/effects/effect_mirror.php
  redaxo/src/addons/media_manager/lib/effects/effect_resize.php
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
  redaxo/src/addons/structure/pages/index.php
  redaxo/src/core/lib/be/page.php
  redaxo/src/core/lib/console/package/activate.php
  redaxo/src/core/lib/console/package/deactivate.php
  redaxo/src/core/lib/console/package/delete.php
  redaxo/src/core/lib/console/package/install.php
  redaxo/src/core/lib/console/package/uninstall.php
  redaxo/src/core/lib/login/password_policy.php
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/lib/util/formatter.php
  redaxo/src/core/tests/packages/manager_test.php
Labels: automerge

#3480 more visual coverage
  .github/tests-visual/backup_export.png
  .github/tests-visual/backup_import.png
  .github/tests-visual/cronjob_cronjobs.png
  .github/tests-visual/media_manager_settings.png
  .github/tests-visual/media_manager_types.png
  .github/tests-visual/media_manager_types_edit.png
  .github/tests-visual/mediapool_media.png
  .github/tests-visual/mediapool_structure.png
  .github/tests-visual/mediapool_sync.png
  .github/tests-visual/mediapool_upload.png
  .github/tests-visual/metainfo_articles.png
  .github/tests-visual/metainfo_categories.png
  .github/tests-visual/metainfo_clangs.png
  .github/tests-visual/metainfo_media.png
  .github/tests-visual/modules_actions.png
  .github/tests-visual/modules_modules.png
  .github/tests-visual/packages.png
  .github/tests-visual/phpmailer_config.png
  .github/tests-visual/system_log.png
  .github/tests-visual/system_report.png
  .github/tests-visual/system_settings.png
  .github/tests-visual/templates.png
  .github/tests-visual/templates_edit.png
  .github/tests-visual/users_roles.png
  .github/tests-visual/users_users.png
  .github/tests-visual/visual-record.js
  .github/workflows/visual-tests.yml
Labels: automerge

#3482 rex_sql_table: Fehler bei mehrfacher Ausführung ohne Änderung
  redaxo/src/core/lib/sql/table.php
  redaxo/src/core/tests/sql/sql_table_test.php
Labels: automerge

#3485 Setup: Passwortregeln berücksichtigen
  redaxo/src/core/pages/setup.php
  redaxo/src/core/pages/setup.step6.php
Labels: automerge

#3484 Neue Methoden rex_user::get und ::require
  .github/tests-visual/system_report.png
  redaxo/src/addons/users/package.yml
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/boot.php
  redaxo/src/core/lib/console/user/set_password.php
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/lib/login/user.php
  redaxo/src/core/pages/profile.php
Labels: automerge

#3478 command: added package:list
  redaxo/src/core/lib/console/command_loader.php
  redaxo/src/core/lib/console/package/list.php
Labels: Add to Docs, Console, Core, Feature, automerge

#3487 Use php-setup@v2
  .github/workflows/csfix.yml
  .github/workflows/push.yml
  .github/workflows/visual-tests.yml
Labels: automerge

#3490 phpstorm.meta korrigiert
  .github/tests-visual/system_report.png
  redaxo/src/core/.phpstorm.meta.php
  redaxo/src/core/lib/rex.php
Labels: automerge
