Repository redaxo/redaxo, pull requests merged in 2020-05, with the labels that each got.

#3579 Addons: PHP-Mindestversion setzen
  redaxo/src/addons/backup/package.yml
  redaxo/src/addons/be_style/package.yml
  redaxo/src/addons/cronjob/package.yml
  redaxo/src/addons/debug/package.yml
  redaxo/src/addons/install/package.yml
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/addons/mediapool/package.yml
  redaxo/src/addons/metainfo/package.yml
  redaxo/src/addons/phpmailer/package.yml
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/users/package.yml
Labels: automerge

#3583 updated clockwork to 4.1.2
  redaxo/bin/update-requirements
  redaxo/src/addons/debug/composer.json
  redaxo/src/addons/debug/composer.lock
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/CHANGELOG.md
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Clockwork.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/DataSource/DataSource.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/DataSource/DataSourceInterface.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/DataSource/PhpDataSource.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Helpers/Serializer.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Helpers/StackTrace.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/Log.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/Request.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/RequestType.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Storage/FileStorage.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Storage/Search.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Support/Vanilla/Clockwork.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/composer.json
Labels: Debug, automerge

#3582 debug: auf system/settings verlinken, um den debug modus dort zu akti…
  redaxo/src/addons/debug/pages/index.php
Labels: Debug, Enhancement, automerge

#3578 Metainfo: Umgang mit Attributen korrigiert
  redaxo/src/addons/metainfo/lib/handler/handler.php
Labels: automerge

#3526 debug: use property editor and editor_basepath
  redaxo/src/addons/debug/boot.php
  redaxo/src/addons/debug/lib/debug.php
  redaxo/src/addons/debug/package.yml
  redaxo/src/core/lib/util/editor.php
Labels: Debug, Enhancement, automerge

#3584 Update clockwork frontend
  redaxo/src/addons/debug/frontend/build.sh
  redaxo/src/addons/debug/frontend/build_master.sh
  redaxo/src/addons/debug/frontend/web/css/app.234d59d2.css
  redaxo/src/addons/debug/frontend/web/css/app.af135e9c.css
  redaxo/src/addons/debug/frontend/web/index.html
  redaxo/src/addons/debug/frontend/web/js/app.036b074b.js
  redaxo/src/addons/debug/frontend/web/js/app.8372dceb.js
Labels: Debug, automerge

#3585 Debug: rex_socket show url
  redaxo/src/core/lib/util/socket/socket.php
Labels: Debug, automerge

#3586 Debug: refactoring
  redaxo/src/addons/debug/boot.php
  redaxo/src/addons/debug/frontend/web/js/app.036b074b.js
  redaxo/src/addons/debug/lib/api_debug.php
  redaxo/src/addons/debug/lib/debug.php
  redaxo/src/addons/debug/lib/debug_clockwork.php
  redaxo/src/addons/debug/lib/extensions/api_function_debug.php
  redaxo/src/addons/debug/lib/extensions/extension_debug.php
  redaxo/src/addons/debug/lib/extensions/logger_debug.php
  redaxo/src/addons/debug/lib/extensions/sql_debug.php
Labels: Debug, automerge

#3575 Remove phpstan workaround for constant expressions
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#3588 Navi-Blöcke: Reihenfolge über Prio änderbar
  redaxo/src/core/layout/top.php
  redaxo/src/core/lib/be/navigation.php
  redaxo/src/core/tests/be/navigation_test.php
Labels: Add to Docs, automerge

#3590 Update vendors (jquery 3.5.1)
  redaxo/src/core/assets/jquery.js
  redaxo/src/core/assets/jquery.min.js
  redaxo/src/core/assets/jquery.min.map
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
Labels: automerge

#3592 PHPMailer README Mails an Testadresse
  redaxo/src/addons/phpmailer/README.de.md
  redaxo/src/addons/phpmailer/README.md
Labels: automerge

#3595 fix AssertionError
  redaxo/src/core/lib/form/elements/container.php
Labels: automerge

#2956 Tabellen via rex_sql_util kopieren
  redaxo/src/core/lib/sql/util.php
  redaxo/src/core/tests/sql/sql_util_test.php
Labels: Add to Docs

#3587 Artikel/Kategorien: getClosest, getClosestValue und isOnlineIncludingParents
  redaxo/src/addons/structure/lib/structure_element.php
  redaxo/src/addons/structure/tests/category_test.php
Labels: Add to Docs, automerge

#3597 rex_fragment: neue Methode getSubfragment
  redaxo/src/core/lib/fragment.php
Labels: Add to Docs, automerge

#3600 Eigener Ordner für Tools
  .tools/bin/clone-addon
  .tools/bin/refresh
  .tools/bin/release
  .tools/bin/update-requirements
  .tools/bootstrap.php
  .tools/psalm/RexTypeReturnProvider.php
  phpstan.neon.dist
  psalm.xml
Labels: automerge

#3601 fix rex_mediapool_syncFile
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
  redaxo/src/addons/mediapool/pages/sync.php
Labels: automerge

#3602 root composer.json
  .tools/bin/update-requirements
  .tools/bin/update-root-composer
  .tools/bootstrap.php
  .tools/constants.php
  composer.json
  phpstan.neon.dist
  psalm.xml
Labels: automerge

#3609 trigger github-actions when PR leaves DRAFT state
  .github/workflows/csfix.yml
  .github/workflows/push.yml
  .github/workflows/visual-tests.yml
Labels: automerge

#3607 rex_article_slice: getStatus -> isOnline
  redaxo/src/addons/structure/plugins/content/lib/article_slice.php
Labels: Structure, automerge

#3613 Recht publishSlice hinzugefügt
  redaxo/src/addons/structure/plugins/content/boot.php
  redaxo/src/addons/structure/plugins/content/lang/de_de.lang
  redaxo/src/addons/structure/plugins/content/lib/api_functions/api_content_slice_status.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php
  redaxo/src/addons/structure/update.php
Labels: automerge

#3611 fix psalm
  composer.json
  redaxo/src/addons/media_manager/lib/effects/effect_crop.php
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/lib/system_report.php
  redaxo/src/core/lib/util/finder.php
Labels: automerge

#3616 Split GitHub Action workflows in separate files
  .github/workflows/cs-check.yml
  .github/workflows/cs-fix.yml
  .github/workflows/push.yml
  .github/workflows/rexlint.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
Labels: automerge

#3614 Alerts im Artikelinhalt angepasst
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_alerts.scss
  redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php
Labels: automerge

#3622 Debug: load clockwork frontend only if admin user is logged in.
  redaxo/src/addons/debug/boot.php
Labels: Bug, Debug, automerge

#3628 debug() expanded design fix
  redaxo/src/core/lib/var_dumper.php
Labels: Design / CSS, Developer Experience (DX), automerge

#3629 JSON schema for config.yml and package.yml
  .gitignore
  .idea/jsonSchemas.xml
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/core/schemas/config.json
  redaxo/src/core/schemas/package.json
Labels: Core, Developer Experience (DX), Enhancement, automerge

#3633 Log: Datei mit Editor-Url verlinken
  redaxo/src/core/pages/system.log.redaxo.php
Labels: automerge

#3634 Log: Styles korrigiert
  .github/tests-visual/system_report.png
  redaxo/src/addons/be_style/assets/css/styles.css
  redaxo/src/addons/be_style/scss/_base.scss
Labels: Bug, Design / CSS, automerge

#3638 GithubAction: dont run jobs on forks, because we are not allowed to commit
  .github/workflows/cs-fix.yml
Labels: automerge

#3641 Dont preload font-awesome
  redaxo/src/addons/be_style/boot.php
Labels: automerge

#3621 Debug console integrate
  .github/tests-visual/system_report.png
  redaxo/src/addons/debug/boot.php
  redaxo/src/core/lib/console/application.php
  redaxo/src/core/lib/console/extension_point_console_shutdown.php
Labels: Debug, Feature, automerge

#3644 Debug: remove unnecessary check
  redaxo/src/addons/debug/boot.php
Labels: Debug, Enhancement, automerge

#3645 Remove unnecessary variable
  redaxo/src/addons/debug/boot.php
Labels: automerge

#3646 update requirements
  composer.json
  redaxo/src/addons/debug/composer.lock
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/CHANGELOG.md
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Clockwork.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Storage/FileStorage.php
  redaxo/src/addons/tests/composer.lock
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/autoload_psr4.php
  redaxo/src/core/vendor/composer/autoload_static.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php
  redaxo/src/core/vendor/symfony/polyfill-ctype/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-ctype/composer.json
  redaxo/src/core/vendor/symfony/polyfill-intl-grapheme/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-intl-grapheme/composer.json
  redaxo/src/core/vendor/symfony/polyfill-intl-normalizer/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-intl-normalizer/composer.json
  redaxo/src/core/vendor/symfony/polyfill-mbstring/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-mbstring/composer.json
  redaxo/src/core/vendor/symfony/polyfill-php72/Php72.php
  redaxo/src/core/vendor/symfony/polyfill-php72/README.md
  redaxo/src/core/vendor/symfony/polyfill-php72/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-php72/composer.json
  redaxo/src/core/vendor/symfony/polyfill-php73/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-php73/composer.json
  redaxo/src/core/vendor/voku/portable-utf8/CHANGELOG.md
  redaxo/src/core/vendor/voku/portable-utf8/README.md
  redaxo/src/core/vendor/voku/portable-utf8/bootstrap.php
  redaxo/src/core/vendor/voku/portable-utf8/composer.json
  redaxo/src/core/vendor/voku/portable-utf8/src/voku/helper/UTF8.php
Labels: automerge

#3648 register redaxo console as composer binary
  composer.json
Labels: automerge

#3650 fix psalm errors
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
  redaxo/src/core/lib/list.php
Labels: automerge

#3653 fix typo
  redaxo/src/core/lib/console/assets_sync.php
Labels: automerge

#3635 Meldung bei Backup, wenn Sonderzeichen in Exportdatei-Namen
  redaxo/src/addons/backup/lang/de_de.lang
  redaxo/src/addons/backup/pages/export.php
Labels: automerge

#3652 Added a Exception in case core-assets folder is not writable
  redaxo/src/core/lib/setup/setup.php
Labels: Developer Experience (DX), Enhancement, automerge

#3654 Installer: Addon-Website ausgeben
  redaxo/src/addons/install/lang/de_de.lang
  redaxo/src/addons/install/lang/en_gb.lang
  redaxo/src/addons/install/pages/packages.add.php
  redaxo/src/addons/install/pages/packages.update.php
  redaxo/src/addons/install/pages/packages.upload.php
Labels: automerge

#3660 update psalm to the latest release
  composer.json
Labels: automerge

#3662 update vendors
  composer.json
  redaxo/src/addons/debug/composer.lock
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Clockwork.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/Request.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Support/Vanilla/config.php
  redaxo/src/addons/phpmailer/composer.json
  redaxo/src/addons/phpmailer/composer.lock
  redaxo/src/core/composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/autoload_psr4.php
  redaxo/src/core/vendor/composer/autoload_static.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/voku/portable-ascii/build/composer.json
  redaxo/src/core/vendor/voku/portable-ascii/build/generate_docs.php
  redaxo/src/core/vendor/voku/portable-ascii/composer.json
  redaxo/src/core/vendor/voku/portable-ascii/src/voku/helper/ASCII.php
  redaxo/src/core/vendor/voku/portable-ascii/src/voku/helper/data/ascii_by_languages.php
Labels: automerge

#3658 mediapool perm for sync files
  .github/tests-visual/packages.png
  .github/tests-visual/system_report.png
  redaxo/src/addons/mediapool/lang/de_de.lang
  redaxo/src/addons/mediapool/lang/en_gb.lang
  redaxo/src/addons/mediapool/package.yml
  redaxo/src/addons/mediapool/pages/sync.php
  redaxo/src/addons/mediapool/update.php
Labels: Enhancement, Mediapool, automerge

#3665 Benutzerverwaltung: Korrektur Unterscheidung ob Selbsteditierung
  redaxo/src/addons/users/pages/users.php
Labels: automerge

#3639 Editor-Einstellungen optional via Cookie
  .github/tests-visual/system_settings.png
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/nl_nl.lang
  redaxo/src/core/lang/sv_se.lang
  redaxo/src/core/lib/response.php
  redaxo/src/core/lib/util/editor.php
  redaxo/src/core/pages/system.settings.php
Labels: Add to Docs, Core, Feature, automerge

#3669 fix typo
  redaxo/src/core/lib/console/setup/run.php
Labels: Console, Enhancement, automerge
