Repository redaxo/redaxo, pull requests merged in 2020-11, with the labels that each got.

#4002 Added rex_finder phpdocs
  redaxo/src/core/lib/util/finder.php
Labels: automerge

#4004 Systembericht: Leere Version abfangen
  redaxo/src/core/pages/system.report.html.php
Labels: automerge

#4007 add @psalm-return never
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/login/api_has_user_session.php
  redaxo/src/core/lib/login/api_user_impersonate.php
Labels: automerge

#4006 psalm: RexTypeReturnProvider erweitert
  .tools/psalm/RexTypeReturnProvider.php
  redaxo/src/addons/structure/plugins/content/pages/content.php
  redaxo/src/addons/structure/plugins/content/pages/modules.actions.php
  redaxo/src/core/pages/setup.php
  redaxo/src/core/pages/system.clangs.php
Labels: automerge

#3999 Added phpdocs
  redaxo/src/core/lib/util/socket/socket.php
Labels: automerge

#4014 Anpassungen für text-overflow
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_form.scss
Labels: automerge

#4017 added note regarding 32bit unix timestamp limitation
  redaxo/src/core/lib/util/formatter.php
Labels: automerge

#4021 Lang, Perm: PHPMailer added German/english
  redaxo/src/addons/phpmailer/lang/de_de.lang
  redaxo/src/addons/phpmailer/lang/en_gb.lang
Labels: automerge

#4022 ini_get kann auch leeren String liefern
  redaxo/src/core/lib/setup/setup.php
Labels: automerge

#4019 Update vendors
  .github/tests-visual/media_manager_settings.png
  composer.json
  redaxo/src/addons/be_style/composer.json
  redaxo/src/addons/be_style/composer.lock
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Exception/Inspector.php
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Run.php
  redaxo/src/core/vendor/voku/anti-xss/composer.json
  redaxo/src/core/vendor/voku/anti-xss/src/voku/helper/AntiXSS.php
  redaxo/src/core/vendor/voku/portable-ascii/composer.json
  redaxo/src/core/vendor/voku/portable-ascii/src/voku/helper/ASCII.php
  redaxo/src/core/vendor/voku/portable-ascii/src/voku/helper/data/ascii_by_languages.php
  redaxo/src/core/vendor/voku/portable-ascii/src/voku/helper/data/x02e.php
  redaxo/src/core/vendor/voku/portable-utf8/composer.json
  redaxo/src/core/vendor/voku/portable-utf8/src/voku/helper/UTF8.php
Labels: automerge

#4026 rex_sql::transactional() return type-template
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#4005 MM insert_image: Abstand zu Rand korrigiert bei right/bottom
  redaxo/src/addons/media_manager/lib/effects/effect_insert_image.php
Labels: automerge

#4029 backup import: SQL-Error escapen
  redaxo/src/addons/backup/lib/backup.php
Labels: automerge

#4018 Version 5.11.1
  redaxo/src/addons/backup/CHANGELOG.md
  redaxo/src/addons/backup/package.yml
  redaxo/src/addons/be_style/CHANGELOG.md
  redaxo/src/addons/be_style/package.yml
  redaxo/src/addons/be_style/plugins/redaxo/package.yml
  redaxo/src/addons/debug/CHANGELOG.md
  redaxo/src/addons/debug/package.yml
  redaxo/src/addons/media_manager/CHANGELOG.md
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/addons/phpmailer/CHANGELOG.md
  redaxo/src/addons/phpmailer/package.yml
  redaxo/src/addons/structure/CHANGELOG.md
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/plugins/content/package.yml
  redaxo/src/addons/users/CHANGELOG.md
  redaxo/src/addons/users/package.yml
  redaxo/src/core/CHANGELOG.md
  redaxo/src/core/boot.php
Labels: automerge

#4024 rex_timer::measure() return type-template
  redaxo/src/core/lib/fragment.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/util/timer.php
Labels: automerge

#4031 update scssphp
  .github/tests-visual/backup_export.png
  .github/tests-visual/backup_import.png
  .github/tests-visual/cronjob_cronjobs.png
  .github/tests-visual/index.png
  .github/tests-visual/media_manager_settings.png
  .github/tests-visual/media_manager_types.png
  .github/tests-visual/media_manager_types_edit.png
  .github/tests-visual/metainfo_articles.png
  .github/tests-visual/metainfo_categories.png
  .github/tests-visual/metainfo_clangs.png
  .github/tests-visual/metainfo_media.png
  .github/tests-visual/modules_actions.png
  .github/tests-visual/modules_modules.png
  .github/tests-visual/packages.png
  .github/tests-visual/phpmailer_config.png
  .github/tests-visual/system_log.png
  .github/tests-visual/system_report.png
  .github/tests-visual/system_settings.png
  .github/tests-visual/templates.png
  .github/tests-visual/templates_edit.png
  .github/tests-visual/users_roles.png
  .github/tests-visual/users_users.png
  composer.json
  redaxo/src/addons/be_style/assets/css/styles.css
  redaxo/src/addons/be_style/composer.json
  redaxo/src/addons/be_style/composer.lock
  redaxo/src/addons/be_style/lib/scss_compiler.php
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/composer.json
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Block.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Compiler.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Exception/SassScriptException.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/Compact.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/Compressed.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/Crunched.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/Debug.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/Expanded.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/Nested.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/OutputBlock.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Node/Number.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/OutputStyle.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Parser.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/SourceMap/Base64VLQ.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/SourceMap/SourceMapGenerator.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Type.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Util.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Version.php
Labels: automerge

#4033 Fixed typo
  .github/tests-visual/visual-record.js
Labels: automerge

#4034 cs: use heredoc_indentation fixer
  .php_cs.dist
  redaxo/src/addons/debug/boot.php
  redaxo/src/addons/structure/pages/linkmap.php
  redaxo/src/core/lib/console/config/set.php
  redaxo/src/core/lib/console/db/connection_options.php
  redaxo/src/core/lib/error_handler.php
  redaxo/src/core/lib/system_report.php
  redaxo/src/core/tests/util/i18n_test.php
  redaxo/src/core/tests/util/log_file_test.php
  redaxo/src/core/tests/util/markdown_test.php
  redaxo/src/core/tests/util/string_test.php
  redaxo/src/core/tests/var/var_test.php
Labels: automerge

#4032 Use composer v2
  composer.json
  redaxo/src/addons/be_style/composer.json
  redaxo/src/addons/be_style/composer.lock
  redaxo/src/addons/debug/composer.json
  redaxo/src/addons/debug/composer.lock
  redaxo/src/addons/phpmailer/composer.json
  redaxo/src/addons/phpmailer/composer.lock
  redaxo/src/core/composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/ClassLoader.php
  redaxo/src/core/vendor/composer/InstalledVersions.php
  redaxo/src/core/vendor/composer/autoload_classmap.php
  redaxo/src/core/vendor/composer/autoload_real.php
  redaxo/src/core/vendor/composer/autoload_static.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
Labels: automerge

#4035 rex_fragment: more precise phpdoc
  redaxo/src/core/lib/fragment.php
Labels: automerge

#4036 define rex_fragment as a universal object crate
  phpstan.neon.dist
Labels: automerge

#4040 rex_context: more precise phpdocs
  redaxo/src/core/lib/context.php
Labels: automerge

#4039 rex_be_controller: more precise phpdoc
  redaxo/src/core/lib/be/controller.php
Labels: automerge

#4041 rex_config_db: a representation of the db connection configuration
  .idea/redaxo.iml
  .tools/phpstan/baseline.neon
  redaxo/src/addons/cronjob/lib/form.php
  redaxo/src/addons/metainfo/lib/table_manager.php
  redaxo/src/core/lib/config_db.php
  redaxo/src/core/lib/form/form.php
  redaxo/src/core/lib/list.php
  redaxo/src/core/lib/login/login.php
  redaxo/src/core/lib/rex.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/sql/table.php
  redaxo/src/core/tests/sql/sql_test.php
Labels: automerge

#4046 use newly introduced `rex::getDbConfig()`
  redaxo/src/core/lib/console/db/connection_options.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/pages/system.settings.php
Labels: automerge

#4045 rex: more precise phpdoc
  redaxo/src/core/lib/error_handler.php
  redaxo/src/core/lib/rex.php
Labels: automerge

#4048 Fix typo
  redaxo/src/core/lib/rex.php
Labels: automerge

#4047 define `rex_escape()` return type via psalm-template
  redaxo/src/core/functions/function_rex_escape.php
  redaxo/src/core/lib/api_function.php
  redaxo/src/core/lib/fragment.php
  redaxo/src/core/lib/util/i18n.php
  redaxo/src/core/pages/credits.php
  redaxo/src/core/pages/packages.list.php
Labels: automerge

#4055 psalm: Debug-Trace-Ausgaben als error werten
  psalm.xml
Labels: automerge

#4057 Native type-hints nutzen
  redaxo/src/core/lib/rex.php
Labels: automerge

#4053 password_policy: added typehints
  redaxo/src/core/lib/login/backend_password_policy.php
  redaxo/src/core/lib/login/password_policy.php
Labels: automerge

#4060 Undefined Notice vermeiden
  redaxo/src/core/lib/config_db.php
Labels: automerge

#4061 GithubAction: added a psalm taint analysis job
  .github/workflows/static-analysis.yml
Labels: automerge

#4063 added psalm taint-analysis composer scripts
  composer.json
Labels: automerge

#4066 require composer v2.. our setup doesn't work with v1 anymore
  composer.json
Labels: automerge

#4068 don't use psalm cache while taint analysis
  .github/workflows/static-analysis.yml
  composer.json
Labels: automerge

#4064 setup: sanitize import filename to prevent path-traversal attacks
  redaxo/src/addons/backup/pages/import.server.php
  redaxo/src/addons/backup/pages/import.upload.php
  redaxo/src/core/lib/util/path.php
  redaxo/src/core/pages/setup.php
Labels: Security, automerge

#4067 rex_editor: added editor constants and editor-name validation
  redaxo/src/core/lib/util/editor.php
Labels: automerge

#4073 fix phpstorm duplicate method error
  redaxo/src/core/lib/fragment.php
Labels: automerge

#4071 make sure we don't miss to close output-buffers when module-output throws
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
Labels: automerge

#4065 prevent xss in rex_form_base
  redaxo/src/core/functions/function_rex_escape.php
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/fragment.php
  redaxo/src/core/lib/util/i18n.php
  redaxo/src/core/lib/util/string.php
Labels: Security, automerge

#4072 extract slice-rendering into separate method
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
Labels: automerge

#4078 avoid xss in rex_form
  redaxo/src/core/lib/form/form_base.php
Labels: Security, automerge

#4079 avoid xss
  redaxo/src/addons/backup/pages/export.php
  redaxo/src/addons/install/pages/packages.add.php
  redaxo/src/addons/install/pages/packages.update.php
  redaxo/src/addons/structure/pages/linkmap.php
Labels: Security, automerge

#4081 throw exception when json cannot be decoded
  .github/tests-visual/login.png
  redaxo/src/core/lib/api_function.php
Labels: automerge

#4082 Revert "require composer v2.. our setup doesn't work with v1 anymore …
  composer.json
Labels: automerge

#4087 moved sanitizing of importName into rex_setup_importer::loadExistingImport()
  redaxo/src/core/lib/setup/import.php
  redaxo/src/core/pages/setup.php
Labels: automerge

#4088 rex_sql: validate filename in importDump() method
  redaxo/src/core/lib/sql/util.php
Labels: automerge

#4086 extracted backup-file validation logic into rex_backup::isFilenameValid()
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/backup/pages/import.server.php
  redaxo/src/addons/backup/pages/import.upload.php
Labels: automerge

#4089 added a psalm taint-baseline
  .github/workflows/static-analysis.yml
  .tools/psalm/baseline-taint.xml
  composer.json
Labels: automerge

#4074 Adding SARIF support to Psalm enables triaging reports within the GitHub UI
  .github/workflows/static-analysis.yml
Labels: automerge

#4091 upload sarif report only for release-branches and on schedule
  .github/workflows/sarif-report.yml
  .github/workflows/static-analysis.yml
Labels: automerge

#4062 handle psalm false-positives
  .github/tests-visual/login.png
  .tools/psalm/baseline-taint.xml
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/backup/pages/export.php
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/structure/plugins/content/lib/article_action.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php
  redaxo/src/addons/structure/plugins/content/lib/var_template.php
Labels: automerge

#4090 cronjob: added phpdocs
  redaxo/src/addons/cronjob/pages/cronjobs.php
  redaxo/src/core/lib/form/elements/container.php
Labels: automerge

#4093 psalm: baseline aktualisiert
  .tools/psalm/baseline.xml
Labels: automerge

#4097 Fix typo
  .github/workflows/sarif-report.yml
Labels: automerge

#4096 php-src basename() als deprecated behandeln
  .tools/psalm/deprecated.stub
  psalm.xml
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/backup/pages/export.php
  redaxo/src/addons/be_style/plugins/customizer/pages/system.customizer.php
  redaxo/src/addons/cronjob/pages/log.php
  redaxo/src/addons/install/lib/archive.php
  redaxo/src/addons/install/lib/webservice.php
  redaxo/src/addons/media_manager/lib/effects/effect_header.php
  redaxo/src/addons/media_manager/lib/managed_media.php
  redaxo/src/addons/media_manager/lib/media_manager.php
  redaxo/src/core/lib/response.php
  redaxo/src/core/lib/util/file.php
  redaxo/src/core/lib/util/path.php
  redaxo/src/core/lib/util/socket/socket.php
  redaxo/src/core/pages/system.log.external.php
  redaxo/src/core/pages/system.log.redaxo.php
  redaxo/src/core/pages/system.settings.php
Labels: automerge

#4099 update vendors
  composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/voku/anti-xss/composer.json
  redaxo/src/core/vendor/voku/anti-xss/src/voku/helper/AntiXSS.php
  redaxo/src/core/vendor/voku/portable-ascii/src/voku/helper/ASCII.php
  redaxo/src/core/vendor/voku/portable-ascii/src/voku/helper/data/ascii_by_languages.php
  redaxo/src/core/vendor/voku/portable-utf8/composer.json
  redaxo/src/core/vendor/voku/portable-utf8/src/voku/helper/UTF8.php
Labels: automerge

#4100 Taint-Analysis: False-positive durch rex_i18n gelöst
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/lib/util/i18n.php
Labels: automerge

#4101 Statische Analyse: Kein Setup notwendig
  .github/workflows/sarif-report.yml
  .github/workflows/static-analysis.yml
Labels: automerge

#4103 rex_escape als escaper markiert
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/functions/function_rex_escape.php
Labels: automerge

#4080 Taint-Analyse: EP-Handling optimiert
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/lib/extension.php
  redaxo/src/core/lib/extension_point.php
Labels: automerge

#4108 phpstan: activate dead code detection
  .tools/phpstan/baseline.neon
  phpstan.neon.dist
Labels: automerge

#4112 fix phpdoc
  .tools/phpstan/baseline.neon
  redaxo/src/core/lib/api_function.php
Labels: automerge

#4111 fix phpstan warning
  .tools/phpstan/baseline.neon
  redaxo/src/addons/structure/plugins/content/lib/select_template.php
Labels: automerge

#4110 removed unused $options property in rex_effect_workspace
  .tools/phpstan/baseline.neon
  redaxo/src/addons/media_manager/lib/effects/effect_workspace.php
Labels: automerge

#4113 fix phpdoc
  .tools/phpstan/baseline.neon
  redaxo/src/core/lib/sql/table.php
Labels: automerge

#4114 fix phpstan warnings
  .tools/phpstan/baseline.neon
  redaxo/src/core/lib/clang/clang.php
Labels: automerge

#4115 fix phpstan warning
  .tools/phpstan/baseline.neon
  redaxo/src/core/lib/form/elements/container.php
Labels: automerge

#4117 rex_list: removed unused property $query
  .tools/phpstan/baseline.neon
  redaxo/src/core/lib/list.php
Labels: automerge

#4104 Falsche Tabelle und falsches Wording
  redaxo/src/addons/structure/plugins/content/lib/cache_module.php
Labels: automerge

#4116 rex_form_prio_element: removed unused property primaryKey
  .tools/phpstan/baseline.neon
  redaxo/src/core/lib/form/elements/prio.php
Labels: automerge

#4118 Actions: Prüfen, ob psalm baseline aktuell
  .github/workflows/static-analysis.yml
Labels: automerge

#4122 added initial rector config
  .tools/rector/rector.php
  composer.json
Labels: automerge

#4124 rector: prevent 'Use of undefined constant REX_MIN_PHP_VERSION' warnings
  .tools/rector/rector.php
Labels: automerge

#4125 rector: make sure we get php 7.3 compatible code
  .tools/rector/rector.php
Labels: automerge

#4123 rector: ChangeAndIfToEarlyReturnRector
  redaxo/src/core/lib/error_handler.php
  redaxo/src/core/lib/extension.php
  redaxo/src/core/lib/packages/package.php
  redaxo/src/core/lib/response.php
  redaxo/src/core/lib/util/i18n.php
Labels: automerge

#4128 rex_package::splitId
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/lib/packages/package.php
  redaxo/src/core/tests/packages/package_test.php
Labels: automerge

#4126 rector: ChangeAndIfToEarlyReturnRector
  .tools/rector/rector.php
  redaxo/src/core/lib/form/form.php
  redaxo/src/core/lib/util/pager.php
Labels: automerge

#4120 Codemirror-Update 5.58.3
  redaxo/src/addons/be_style/plugins/customizer/assets/vendor/codemirror.zip
  redaxo/src/addons/be_style/plugins/customizer/help.php
Labels: automerge, dependencies

#4129 Optionen ohne "--" deklarieren
  redaxo/src/core/lib/console/setup/run.php
Labels: automerge

#3559 Implement phpstan symfony-console analysis
  .idea/php.xml
  .idea/redaxo.iml
  .tools/phpstan/console.php
  composer.json
  phpstan.neon.dist
Labels: automerge

#3949 Installer in AddOn liste anbinden
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/pages/packages.list.php
Labels: Core, Developer Experience (DX), Enhancement, automerge

#4127 rector: ChangeAndIfToEarlyReturnRector & RemoveAlwaysElseRector
  .tools/rector/rector.php
Labels: automerge

#4131 recotor: activate early-return set instead of separate rules
  .tools/rector/rector.php
Labels: automerge

#4130 rex_extension: add docs
  redaxo/src/core/lib/extension.php
Labels: automerge

#4132 recotor: add addons lib-paths to rector
  .tools/rector/rector.php
  redaxo/src/addons/media_manager/lib/managed_media.php
  redaxo/src/addons/structure/lib/api_functions/api_article2category.php
  redaxo/src/addons/structure/lib/api_functions/api_article2startarticle.php
  redaxo/src/addons/structure/lib/api_functions/api_article_move.php
  redaxo/src/addons/structure/lib/api_functions/api_category2article.php
  redaxo/src/addons/structure/lib/api_functions/api_category_move.php
Labels: automerge

#4134 backup import: Cache wurde nicht gelöscht, und Erfolgsmeldung war rot
  redaxo/src/addons/backup/lib/backup.php
Labels: Bug, automerge

#4137 revert changes from #4123 in response.php
  redaxo/src/core/lib/response.php
Labels: automerge
