Repository redaxo/redaxo, pull requests merged in 2020-12, with the labels that each got.

#4121 Anpassung rex_error_handler für PHP 8
  redaxo/src/core/lib/error_handler.php
Labels: Bug, Core, automerge

#4140 Symfony components 5.2
  composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/InstalledVersions.php
  redaxo/src/core/vendor/composer/autoload_classmap.php
  redaxo/src/core/vendor/composer/autoload_static.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
  redaxo/src/core/vendor/symfony/console/Application.php
  redaxo/src/core/vendor/symfony/console/Color.php
  redaxo/src/core/vendor/symfony/console/Command/Command.php
  redaxo/src/core/vendor/symfony/console/Command/HelpCommand.php
  redaxo/src/core/vendor/symfony/console/Command/ListCommand.php
  redaxo/src/core/vendor/symfony/console/Command/SignalableCommandInterface.php
  redaxo/src/core/vendor/symfony/console/ConsoleEvents.php
  redaxo/src/core/vendor/symfony/console/Descriptor/JsonDescriptor.php
  redaxo/src/core/vendor/symfony/console/Descriptor/MarkdownDescriptor.php
  redaxo/src/core/vendor/symfony/console/Descriptor/TextDescriptor.php
  redaxo/src/core/vendor/symfony/console/Descriptor/XmlDescriptor.php
  redaxo/src/core/vendor/symfony/console/Event/ConsoleSignalEvent.php
  redaxo/src/core/vendor/symfony/console/Formatter/OutputFormatter.php
  redaxo/src/core/vendor/symfony/console/Formatter/OutputFormatterStyle.php
  redaxo/src/core/vendor/symfony/console/Helper/ProgressBar.php
  redaxo/src/core/vendor/symfony/console/Helper/QuestionHelper.php
  redaxo/src/core/vendor/symfony/console/Helper/SymfonyQuestionHelper.php
  redaxo/src/core/vendor/symfony/console/Helper/Table.php
  redaxo/src/core/vendor/symfony/console/Helper/TableCell.php
  redaxo/src/core/vendor/symfony/console/Helper/TableCellStyle.php
  redaxo/src/core/vendor/symfony/console/Input/ArgvInput.php
  redaxo/src/core/vendor/symfony/console/Output/ConsoleOutput.php
  redaxo/src/core/vendor/symfony/console/Output/TrimmedBufferOutput.php
  redaxo/src/core/vendor/symfony/console/Question/ChoiceQuestion.php
  redaxo/src/core/vendor/symfony/console/Question/Question.php
  redaxo/src/core/vendor/symfony/console/SignalRegistry/SignalRegistry.php
  redaxo/src/core/vendor/symfony/console/SingleCommandApplication.php
  redaxo/src/core/vendor/symfony/console/Style/SymfonyStyle.php
  redaxo/src/core/vendor/symfony/console/Tester/TesterTrait.php
  redaxo/src/core/vendor/symfony/console/composer.json
  redaxo/src/core/vendor/symfony/string/AbstractUnicodeString.php
  redaxo/src/core/vendor/symfony/string/ByteString.php
  redaxo/src/core/vendor/symfony/string/Inflector/FrenchInflector.php
  redaxo/src/core/vendor/symfony/string/Resources/functions.php
  redaxo/src/core/vendor/symfony/string/Slugger/AsciiSlugger.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/ArgsStub.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/ReflectionCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Cloner/AbstractCloner.php
  redaxo/src/core/vendor/symfony/var-dumper/Dumper/CliDumper.php
  redaxo/src/core/vendor/symfony/var-dumper/Dumper/HtmlDumper.php
  redaxo/src/core/vendor/symfony/var-dumper/Server/DumpServer.php
  redaxo/src/core/vendor/symfony/var-dumper/VarDumper.php
  redaxo/src/core/vendor/symfony/yaml/Parser.php
Labels: automerge

#4141 refresh script: alle core packages reinstallieren, aber nur wenn schon installiert
  .tools/bin/refresh
Labels: automerge

#4102 psalm taint: use threads=1
  composer.json
Labels: automerge

#4038 rex_file: more precise phpdoc
  .tools/psalm/baseline-taint.xml
  .tools/psalm/baseline.xml
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/backup/lib/tar.php
  redaxo/src/addons/be_style/lib/scss_compiler.php
  redaxo/src/addons/media_manager/lib/managed_media.php
  redaxo/src/addons/mediapool/lib/media.php
  redaxo/src/addons/structure/lib/structure_element.php
  redaxo/src/core/backend.php
  redaxo/src/core/lib/be/controller.php
  redaxo/src/core/lib/console/db/set_connection.php
  redaxo/src/core/lib/console/setup/run.php
  redaxo/src/core/lib/util/file.php
  redaxo/src/core/pages/credits.php
  redaxo/src/core/pages/packages.help.php
  redaxo/src/core/pages/packages.license.php
  redaxo/src/core/pages/setup.step2.php
  redaxo/src/core/tests/console/config/set_test.php
  redaxo/src/core/tests/util/file_test.php
  redaxo/src/core/tests/util/log_file_test.php
Labels: automerge

#4105 Handle $escape dependent taint-escape handling
  .tools/psalm/baseline-taint.xml
  redaxo/src/addons/backup/pages/export.php
  redaxo/src/core/lib/util/i18n.php
Labels: automerge

#4148 use `rex_sql::FORMAT_DATETIME`
  redaxo/src/addons/media_manager/pages/types.php
  redaxo/src/addons/structure/plugins/history/lib/article_slice_history.php
Labels: Core, automerge

#4147 introduce `rex_log_entry::DATE_FORMAT`
  redaxo/src/core/lib/util/log_file.php
  redaxo/src/core/tests/util/log_entry_test.php
Labels: Core, automerge

#4151 rex_sql: remove unused variables
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#4155 tests: ignore only php version constraints
  .github/workflows/tests.yml
Labels: automerge

#4153 rex_sql: type support in getValue
  .tools/psalm/RexTypeReturnProvider.php
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/lib/login/user.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/tests/sql/sql_test.php
Labels: automerge

#4156 rex_formatter: phpdoc
  redaxo/src/core/lib/util/formatter.php
Labels: automerge

#4157 rex_sql::getValue: support scalar types only
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/tests/sql/sql_test.php
Labels: automerge

#4158 rex_formatter: declare null as supported $value, which is already hand…
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/util/formatter.php
Labels: automerge

#4161 added php 8.0 end of life handling
  redaxo/src/core/lib/setup/setup.php
Labels: automerge

#4162 Added mariadb 10.5 / mysql 8.0 end of life handling
  redaxo/src/core/lib/setup/setup.php
Labels: automerge

#4145 rex_media_category_select: fix root & perm handling
  redaxo/src/addons/mediapool/lib/media_category_select.php
Labels: Mediapool, automerge

#4013 override sendCacheControl in sendResource()
  redaxo/src/core/lib/response.php
Labels: Core, Enhancement, automerge

#4169 cs: clean config
  .php_cs.dist
  redaxo/src/addons/cronjob/lib/cronjob.php
  redaxo/src/addons/media_manager/lib/effect_abstract.php
  redaxo/src/core/lib/base/singleton_trait.php
  redaxo/src/core/lib/packages/null.php
Labels: automerge

#4170 cs: simplified if return
  redaxo/src/addons/backup/lib/tar.php
  redaxo/src/addons/cronjob/lib/types/phpcode.php
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
  redaxo/src/addons/mediapool/lib/cache_media.php
  redaxo/src/addons/structure/plugins/content/lib/api_template.php
Labels: automerge

#4152 structure: add separate error message when a clang with id=0 exists
  redaxo/src/addons/structure/pages/index.php
Labels: automerge

#4172 PHP 8: Warnings vermeiden
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#4173 remove nunomaduro/collision dependency
  composer.json
  phpunit.xml.dist
Labels: automerge

#4176 Vendor updates
  composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/voku/anti-xss/composer.json
  redaxo/src/core/vendor/voku/anti-xss/src/voku/helper/AntiXSS.php
  redaxo/src/core/vendor/voku/portable-utf8/src/voku/helper/UTF8.php
Labels: automerge

#4184 Remove ci-skip handling
  .github/workflows/visual-tests.yml
Labels: automerge

#4190 github actions: added /visual-test chatcommand
  .github/tests-visual/visual-record.js
  .github/workflows/chatops.yml
  .github/workflows/visual-tests.yml
Labels: automerge

#4191 github actions: try to commit changes on repo-dispatch /visual-test
  .github/workflows/visual-tests.yml
Labels: automerge

#4188 Use proper phpdoc
  redaxo/src/addons/metainfo/boot.php
Labels: automerge

#4189 Use proper phpdoc
  redaxo/src/addons/cronjob/boot.php
Labels: automerge

#4192 github actions: try to commit changes on repo-dispatch /visual-test
  .github/workflows/visual-tests.yml
Labels: automerge

#4193 github actions: try to commit changes on repo-dispatch /visual-test
  .github/workflows/visual-tests.yml
Labels: automerge

#4194 visual testing: added user-edit and role-add coverage
  .github/tests-visual/users_edit.png
  .github/tests-visual/users_role_add.png
  .github/tests-visual/visual-record.js
  .github/workflows/visual-tests.yml
Labels: automerge

#4094 backup: exportieren/importieren von großen Dateibackups ermöglichen
  .idea/redaxo.iml
  .tools/bin/update-all
  .tools/bin/update-root-composer
  .tools/psalm/baseline-taint.xml
  composer.json
  phpstan.neon.dist
  psalm.xml
  redaxo/src/addons/backup/composer.json
  redaxo/src/addons/backup/composer.lock
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/backup/lib/tar.php
  redaxo/src/addons/backup/pages/export.php
  redaxo/src/addons/backup/vendor/splitbrain/php-archive/LICENSE
  redaxo/src/addons/backup/vendor/splitbrain/php-archive/composer.json
  redaxo/src/addons/backup/vendor/splitbrain/php-archive/src/Archive.php
  redaxo/src/addons/backup/vendor/splitbrain/php-archive/src/ArchiveCorruptedException.php
  redaxo/src/addons/backup/vendor/splitbrain/php-archive/src/ArchiveIOException.php
  redaxo/src/addons/backup/vendor/splitbrain/php-archive/src/ArchiveIllegalCompressionException.php
  redaxo/src/addons/backup/vendor/splitbrain/php-archive/src/FileInfo.php
  redaxo/src/addons/backup/vendor/splitbrain/php-archive/src/FileInfoException.php
  redaxo/src/addons/backup/vendor/splitbrain/php-archive/src/Tar.php
  redaxo/src/addons/backup/vendor/splitbrain/php-archive/src/Zip.php
  redaxo/src/addons/backup/vendor/tar.php
Labels: automerge

#4178 structure/content: use rex:ready
  redaxo/src/addons/structure/plugins/content/assets/content.js
Labels: automerge

#4204 fix composer bash-scripts on windows
  composer.json
Labels: automerge

#4182 update login page styles
  .github/tests-visual/login.png
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_login.scss
Labels: automerge

#4183 use REDAXO logo SVG instead of img
  redaxo/src/core/assets/redaxo-logo.svg
  redaxo/src/core/fragments/core/header.php
  redaxo/src/core/fragments/core/login_branding.php
Labels: automerge

#4180 use greener green
  .github/tests-visual/backup_export.png
  .github/tests-visual/media_manager_settings.png
  .github/tests-visual/mediapool_upload.png
  .github/tests-visual/phpmailer_config.png
  .github/tests-visual/system_log.png
  .github/tests-visual/system_settings.png
  .github/tests-visual/templates_edit.png
  .github/tests-visual/users_edit.png
  .github/tests-visual/users_role_add.png
  redaxo/src/addons/be_style/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_variables.scss
Labels: automerge

#4179 align form-control heights with button heights
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_form.scss
Labels: automerge

#4210 Vendor updates
  composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/symfony/console/ConsoleEvents.php
  redaxo/src/core/vendor/symfony/console/Descriptor/ApplicationDescription.php
  redaxo/src/core/vendor/symfony/console/Event/ConsoleCommandEvent.php
  redaxo/src/core/vendor/symfony/console/Formatter/OutputFormatterStyle.php
  redaxo/src/core/vendor/symfony/console/Input/InputArgument.php
  redaxo/src/core/vendor/symfony/console/Input/InputOption.php
  redaxo/src/core/vendor/symfony/console/Input/StringInput.php
  redaxo/src/core/vendor/symfony/console/Logger/ConsoleLogger.php
  redaxo/src/core/vendor/symfony/console/Output/OutputInterface.php
  redaxo/src/core/vendor/symfony/console/Style/SymfonyStyle.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/Caster.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/ReflectionCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Cloner/Cursor.php
  redaxo/src/core/vendor/symfony/var-dumper/Cloner/Stub.php
  redaxo/src/core/vendor/symfony/var-dumper/Dumper/AbstractDumper.php
  redaxo/src/core/vendor/symfony/var-dumper/Dumper/CliDumper.php
  redaxo/src/core/vendor/symfony/yaml/Escaper.php
  redaxo/src/core/vendor/symfony/yaml/Inline.php
  redaxo/src/core/vendor/symfony/yaml/Parser.php
  redaxo/src/core/vendor/symfony/yaml/Unescaper.php
  redaxo/src/core/vendor/symfony/yaml/Yaml.php
Labels: automerge

#4214 Templates-Page: fehlendes escaping
  redaxo/src/addons/structure/plugins/content/pages/templates.php
Labels: Security, automerge

#4215 Phpstan: activate debug-mode
  .github/workflows/static-analysis.yml
Labels: automerge

#4133 rector: apply code-quality set to core/lib
  redaxo/src/core/lib/be/navigation.php
  redaxo/src/core/lib/console/assets_sync.php
  redaxo/src/core/lib/console/setup/run.php
  redaxo/src/core/lib/form/elements/checkbox.php
  redaxo/src/core/lib/form/elements/element.php
  redaxo/src/core/lib/form/elements/prio.php
  redaxo/src/core/lib/form/elements/radio.php
  redaxo/src/core/lib/login/login.php
  redaxo/src/core/lib/sql/foreign_key.php
  redaxo/src/core/lib/sql/index.php
  redaxo/src/core/lib/util/editor.php
  redaxo/src/core/lib/util/sortable_iterator.php
  redaxo/src/core/lib/util/validator.php
  redaxo/src/core/lib/view.php
Labels: automerge

#4216 Backup: taint-escapes erweitert
  .tools/psalm/baseline-taint.xml
  redaxo/src/addons/backup/pages/export.php
Labels: automerge

#4211 Datei-Import: Media-Ordner nicht löschen
  .github/tests-visual/backup_import.png
  redaxo/src/addons/backup/lang/de_de.lang
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/backup/pages/import.server.php
  redaxo/src/addons/backup/pages/import.upload.php
Labels: automerge

#4209 submit forms via strg/cmd + enter
  redaxo/src/core/assets/standard.js
Labels: automerge

#4221 rex_form prio-feld: sql injection verhindern
  redaxo/src/core/lib/form/elements/prio.php
Labels: Security, automerge

#4222 cronjob: escaping
  .tools/psalm/baseline-taint.xml
  redaxo/src/addons/cronjob/pages/cronjobs.php
Labels: automerge

#4223 metainfo: prepared statements nutzen
  redaxo/src/addons/metainfo/lib/table_expander.php
Labels: Security, automerge

#4218 `composer refresh`: fix core-assets copying
  .tools/bin/refresh
Labels: Bug, Developer Experience (DX), automerge

#4220 use php8 attributes for deprecated methods which allows automatic rep…
  redaxo/src/core/lib/login/password_policy.php
  redaxo/src/core/lib/rex.php
  redaxo/src/core/lib/util/string.php
Labels: automerge

#4027 extensionPoint: Use generic template
  redaxo/src/core/lib/extension_point.php
Labels: automerge

#4205 Debug: Clockwork 5.x
  redaxo/src/addons/debug/boot.php
  redaxo/src/addons/debug/composer.json
  redaxo/src/addons/debug/composer.lock
  redaxo/src/addons/debug/frontend/build.sh
  redaxo/src/addons/debug/frontend/web/css/app.234d59d2.css
  redaxo/src/addons/debug/frontend/web/css/app.65a6b11f.css
  redaxo/src/addons/debug/frontend/web/index.html
  redaxo/src/addons/debug/frontend/web/js/app.aee4659b.js
  redaxo/src/addons/debug/frontend/web/js/app.caa64fe8.js
  redaxo/src/addons/debug/frontend/web/js/chunk-vendors.57b6c479.js
  redaxo/src/addons/debug/frontend/web/js/chunk-vendors.b6cbf595.js
  redaxo/src/addons/debug/lib/extensions/api_function_debug.php
  redaxo/src/addons/debug/lib/extensions/extension_debug.php
  redaxo/src/addons/debug/lib/extensions/logger_debug.php
  redaxo/src/addons/debug/lib/extensions/sql_debug.php
  redaxo/src/addons/debug/package.yml
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/.gitattributes
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/.gitignore
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Clockwork.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/DataSource/DataSource.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/DataSource/DataSourceInterface.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/DataSource/PhpDataSource.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/DataSource/XdebugDataSource.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Helpers/Concerns/ResolvesViewName.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Helpers/Serializer.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Helpers/ServerTiming.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Helpers/StackFilter.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Helpers/StackFrame.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Helpers/StackTrace.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/IncomingRequest.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/Log.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/Request.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/ShouldCollect.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/ShouldRecord.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/Timeline.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/Timeline/Event.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/Timeline/Timeline.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/UserData.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/UserDataItem.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Storage/FileStorage.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Storage/Search.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Storage/StorageInterface.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Support/Vanilla/Clockwork.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Support/Vanilla/config.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Support/Vanilla/helpers.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/LICENSE
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/composer.json
Labels: Debug, automerge

#4237 measure boot time of each package individually
  redaxo/src/core/packages.php
Labels: Debug, Developer Experience (DX), automerge

#4236 .idea: prevent "suggest default language level change"
  .idea/php.xml
Labels: automerge

#4240 fix sidebar panel toggle js (structure/content)
  redaxo/src/addons/structure/plugins/content/assets/content.js
Labels: automerge

#4225 rex_sql::in() für `IN (...)` statements
  redaxo/src/core/lib/config.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/tests/sql/sql_test.php
Labels: Add to Docs, automerge

#4248 PHP-Mailer: Adding default setting errormail
  redaxo/src/addons/phpmailer/package.yml
Labels: automerge

#4252 setup a minimal exception handler to print early errors in console
  redaxo/src/core/console.php
Labels: automerge

#4254 console-setup: print file-errors in list-style
  redaxo/src/core/lib/console/setup/run.php
Labels: Console, Developer Experience (DX), automerge

#4253 add global .gitattributes to make git checkouts work when git core.autocrlf is configured
  .gitattributes
Labels: automerge

#4213 Taint-Analyse für rex_request optimieren
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/functions/function_rex_globals.php
  redaxo/src/core/lib/request.php
  redaxo/src/core/lib/util/type.php
Labels: automerge

#4224 structure: prepared statements nutzen
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/pages/index.php
Labels: automerge

#4261 Installer: Zusätzlicher Schutz vor path traversal
  .tools/psalm/baseline-taint.xml
  redaxo/src/addons/install/lib/package/package_download.php
Labels: automerge

#4262 Taint-Analyse: False-positive in Asset-Handling
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/backend.php
Labels: automerge

#4267 Auskommentierte Login Navigation entfernt
  redaxo/src/core/layout/top.php
Labels: automerge

#4266 fixed comments in lang files
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/it_it.lang
  redaxo/src/core/lang/nl_nl.lang
  redaxo/src/core/lang/pt_br.lang
  redaxo/src/core/lang/sv_se.lang
Labels: Core, automerge

#4257 PHPMailer: Checkmail success / error via rex_view
  redaxo/src/addons/phpmailer/pages/checkmail.php
Labels: PHPMailer, automerge

#4265 Pflichtfelder markieren
  .github/tests-visual/system_settings.png
  .github/tests-visual/users_edit.png
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/pages/setup.step4.php
  redaxo/src/core/pages/setup.step5.php
  redaxo/src/core/pages/setup.step6.php
  redaxo/src/core/pages/system.settings.php
Labels: Developer Experience (DX), Setup, User Experience (UX), automerge

#4274 Lizenz-erklären link als externer link markiert
  redaxo/src/core/pages/packages.license.php
Labels: Enhancement, User Experience (UX), automerge

#4272 Debug: debug-mode hinweise auch im debug-setup step anzeigen
  redaxo/src/addons/debug/pages/index.php
Labels: Debug, Developer Experience (DX), automerge

#4260 taint analyse: fix false-positive in rex_list/rex_sql/rex_pager
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/lib/list.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/util/pager.php
Labels: automerge

#4273 UI: pulsierendes herz-symbol bei aktiviertem debug-mode
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_utilities.scss
  redaxo/src/core/fragments/core/header.php
Labels: Design / CSS, Developer Experience (DX), Enhancement, automerge
