Repository redaxo/redaxo, pull requests merged in 2020-06, with the labels that each got.

#3675 Console: config:set allow boolean string
  redaxo/src/core/lib/console/config/set.php
  redaxo/src/core/tests/console/config/set_test.php
Labels: Bug, Console, automerge

#3677 separated value-casting from path-building
  redaxo/src/core/lib/console/config/set.php
Labels: automerge

#3671 update requirements
  .tools/bin/update-requirements
  composer.json
  redaxo/src/addons/debug/composer.lock
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Clockwork.php
  redaxo/src/addons/tests/composer.lock
  redaxo/src/addons/tests/vendor/doctrine/instantiator/composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/bin/var-dump-server
  redaxo/src/core/vendor/composer/autoload_classmap.php
  redaxo/src/core/vendor/composer/autoload_files.php
  redaxo/src/core/vendor/composer/autoload_psr4.php
  redaxo/src/core/vendor/composer/autoload_static.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/symfony/console/Application.php
  redaxo/src/core/vendor/symfony/console/Helper/ProcessHelper.php
  redaxo/src/core/vendor/symfony/console/Helper/QuestionHelper.php
  redaxo/src/core/vendor/symfony/console/composer.json
  redaxo/src/core/vendor/symfony/polyfill-php80/LICENSE
  redaxo/src/core/vendor/symfony/polyfill-php80/Php80.php
  redaxo/src/core/vendor/symfony/polyfill-php80/Resources/stubs/Stringable.php
  redaxo/src/core/vendor/symfony/polyfill-php80/Resources/stubs/ValueError.php
  redaxo/src/core/vendor/symfony/polyfill-php80/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-php80/composer.json
  redaxo/src/core/vendor/symfony/var-dumper/Caster/Caster.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/ClassStub.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/ExceptionCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/ReflectionCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/SplCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Cloner/AbstractCloner.php
  redaxo/src/core/vendor/symfony/var-dumper/Dumper/HtmlDumper.php
  redaxo/src/core/vendor/symfony/var-dumper/Resources/bin/var-dump-server
  redaxo/src/core/vendor/symfony/var-dumper/Server/DumpServer.php
  redaxo/src/core/vendor/symfony/var-dumper/composer.json
  redaxo/src/core/vendor/symfony/yaml/Inline.php
  redaxo/src/core/vendor/symfony/yaml/Parser.php
  redaxo/src/core/vendor/symfony/yaml/composer.json
Labels: automerge

#3678 improve config:set tests
  redaxo/src/core/tests/console/config/set_test.php
Labels: Console, automerge

#3674 Hinweis auf Aktionen in Modul-Editier Maske
  redaxo/src/addons/structure/plugins/content/lang/de_de.lang
  redaxo/src/addons/structure/plugins/content/lang/en_gb.lang
  redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
Labels: Enhancement, Structure, User Experience (UX), automerge

#3679 dependabot: root-tools aktualisieren
  .dependabot/config.yml
  .github/dependabot.yml
  .idea/redaxo.iml
  composer.json
Labels: automerge

#3680 fix dependabot
  .github/dependabot.yml
Labels: automerge

#3682 Redaxo-Log-Eintrag um Success erweitern
  redaxo/src/core/pages/system.log.redaxo.php
Labels: automerge

#3683 history plugin: fix missing module key
  .github/tests-visual/packages.png
  .github/tests-visual/system_report.png
  redaxo/src/addons/structure/plugins/history/boot.php
  redaxo/src/addons/structure/plugins/history/package.yml
Labels: automerge

#3686 Debug: update clockwork frontend
  redaxo/src/addons/debug/frontend/build.sh
  redaxo/src/addons/debug/frontend/web/index.html
  redaxo/src/addons/debug/frontend/web/js/app.036b074b.js
  redaxo/src/addons/debug/frontend/web/js/app.caa64fe8.js
Labels: Debug, Enhancement, automerge

#3695 Update vendors
  composer.json
  redaxo/src/addons/be_style/composer.lock
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Compiler.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/SourceMap/Base64VLQ.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Version.php
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
Labels: automerge

#3657 Extension Point vor Upload in Medienpool erstellt
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
Labels: Enhancement, Mediapool, automerge

#3696 rex::getConsole() befüllen vor Laden der Addons
  redaxo/src/core/console.php
Labels: Bug, Console, automerge

#3704 Added GithubActions dependabot config
  .github/dependabot.yml
Labels: automerge

#3697 Beschriftung HTML-Attribute statt Feldattribute
  redaxo/src/addons/metainfo/lang/de_de.lang
Labels: Enhancement, Metainfo, automerge

#3715 Added phpstan/phpstan-phpunit plugin
  composer.json
Labels: Contributor Experience, automerge

#3713 take mysql comments into account in `rex_sql_column`
  redaxo/src/core/lib/sql/column.php
  redaxo/src/core/lib/sql/schema_dumper.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/sql/table.php
  redaxo/src/core/tests/sql/sql_table_test.php
Labels: Console, Core, Enhancement, automerge

#3722 Project-Addon: More examples
  redaxo/src/addons/project/package.yml
Labels: automerge

#3723 Project-Addon: more explicit docs
  redaxo/src/addons/project/package.yml
Labels: automerge

#3721 api-functions: notes about permissions in backend calls
  redaxo/src/core/lib/api_function.php
Labels: automerge

#3727 More precise phpdocs
  redaxo/src/core/lib/view.php
Labels: automerge

#3735 Effekt mediapath: Korrekten Dateinamen nehmen
  redaxo/src/addons/media_manager/lib/effects/effect_mediapath.php
Labels: automerge

#3725 Setup: Use rex_path for i18n messages
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/it_it.lang
  redaxo/src/core/lang/nl_nl.lang
  redaxo/src/core/lang/pt_br.lang
  redaxo/src/core/lang/sv_se.lang
  redaxo/src/core/pages/setup.php
  redaxo/src/core/pages/setup.step4.php
Labels: Enhancement, Setup, automerge

#3743 Debug: ensure clockwork storage path after cache clear
  redaxo/src/addons/debug/boot.php
  redaxo/src/addons/debug/lib/debug_clockwork.php
Labels: Bug, Debug, automerge

#3746 Template-Lösch-Fehler korrigiert
  redaxo/src/addons/structure/plugins/content/pages/templates.php
Labels: automerge

#3748 Setup: rex_backup-Klasse verfügbar machen
  redaxo/src/core/lib/console/setup/run.php
Labels: automerge

#3750 Systemeinstellungen: Editor nicht nullen
  redaxo/src/core/pages/system.settings.php
Labels: automerge

#3749 Exception message etwas "verschönert"
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#3753 Repo als Supportpage
  redaxo/src/addons/backup/package.yml
  redaxo/src/addons/be_style/package.yml
  redaxo/src/addons/be_style/plugins/customizer/package.yml
  redaxo/src/addons/be_style/plugins/redaxo/package.yml
  redaxo/src/addons/cronjob/package.yml
  redaxo/src/addons/cronjob/plugins/article_status/package.yml
  redaxo/src/addons/cronjob/plugins/optimize_tables/package.yml
  redaxo/src/addons/debug/package.yml
  redaxo/src/addons/install/package.yml
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/addons/mediapool/package.yml
  redaxo/src/addons/metainfo/package.yml
  redaxo/src/addons/phpmailer/package.yml
  redaxo/src/addons/project/package.yml
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/plugins/content/package.yml
  redaxo/src/addons/structure/plugins/history/package.yml
  redaxo/src/addons/structure/plugins/version/package.yml
  redaxo/src/addons/tests/package.yml
  redaxo/src/addons/users/package.yml
Labels: automerge

#3757 CS config: Pfade korrigiert
  .php_cs.dist
  .tools/bin/release
Labels: automerge

#3760 Debug: "Headers already sent" vermeiden
  redaxo/src/addons/debug/lib/api_debug.php
Labels: automerge

#3763 table-hover ergänzt
  redaxo/src/addons/media_manager/pages/effects.php
  redaxo/src/addons/media_manager/pages/types.php
  redaxo/src/addons/metainfo/pages/field.php
Labels: automerge

#3764 leere Zeile in Artikelliste anzeigen
  redaxo/src/addons/structure/pages/index.php
Labels: automerge

#3770 Korrektur Ausrufezeichen entfernt
  redaxo/src/core/lang/de_de.lang
Labels: User Experience (UX), automerge

#3772 phpstan fix
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#3773 Update vendors
  composer.json
  redaxo/src/addons/tests/composer.lock
  redaxo/src/addons/tests/vendor/myclabs/deep-copy/composer.json
  redaxo/src/addons/tests/vendor/myclabs/deep-copy/doc/clone.png
  redaxo/src/addons/tests/vendor/myclabs/deep-copy/doc/deep-clone.png
  redaxo/src/addons/tests/vendor/myclabs/deep-copy/doc/deep-copy.png
  redaxo/src/addons/tests/vendor/myclabs/deep-copy/doc/graph.png
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/symfony/polyfill-ctype/composer.json
  redaxo/src/core/vendor/symfony/polyfill-intl-grapheme/composer.json
  redaxo/src/core/vendor/symfony/polyfill-intl-normalizer/Normalizer.php
  redaxo/src/core/vendor/symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php
  redaxo/src/core/vendor/symfony/polyfill-intl-normalizer/Resources/unidata/canonicalComposition.php
  redaxo/src/core/vendor/symfony/polyfill-intl-normalizer/Resources/unidata/canonicalDecomposition.php
  redaxo/src/core/vendor/symfony/polyfill-intl-normalizer/Resources/unidata/combiningClass.php
  redaxo/src/core/vendor/symfony/polyfill-intl-normalizer/Resources/unidata/compatibilityDecomposition.php
  redaxo/src/core/vendor/symfony/polyfill-intl-normalizer/composer.json
  redaxo/src/core/vendor/symfony/polyfill-mbstring/Resources/unidata/lowerCase.php
  redaxo/src/core/vendor/symfony/polyfill-mbstring/Resources/unidata/upperCase.php
  redaxo/src/core/vendor/symfony/polyfill-mbstring/composer.json
  redaxo/src/core/vendor/symfony/polyfill-php73/composer.json
  redaxo/src/core/vendor/symfony/polyfill-php80/composer.json
Labels: automerge

#3778 git-auto-commit-action: use tag "v4"
  .github/workflows/cs-fix.yml
  .github/workflows/visual-tests.yml
Labels: automerge

#3777 Editor-Basepath normalisieren (Slash am Ende)
  redaxo/src/core/lib/util/editor.php
Labels: automerge

#3716 Added psalm/plugin-phpunit plugin
  .php_cs.dist
  composer.json
  psalm.xml
  redaxo/src/addons/mediapool/tests/media_test.php
  redaxo/src/addons/structure/tests/article_test.php
  redaxo/src/addons/structure/tests/category_test.php
  redaxo/src/core/tests/base/singleton_trait_test.php
  redaxo/src/core/tests/clang/clang_test.php
  redaxo/src/core/tests/packages/manager_test.php
  redaxo/src/core/tests/rex_test.php
  redaxo/src/core/tests/sql/sql_test.php
  redaxo/src/core/tests/util/formatter_test.php
  redaxo/src/core/tests/util/log_entry_test.php
  redaxo/src/core/tests/util/socket_test.php
  redaxo/src/core/tests/util/validator_test.php
Labels: Contributor Experience, automerge
