Repository redaxo/redaxo, pull requests merged in 2020-04, with the labels that each got.

#3492 Update vendors
  redaxo/src/addons/tests/composer.lock
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/autoload_classmap.php
  redaxo/src/core/vendor/composer/autoload_static.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/psr/log/Psr/Log/LoggerInterface.php
  redaxo/src/core/vendor/symfony/console/Application.php
  redaxo/src/core/vendor/symfony/console/Command/Command.php
  redaxo/src/core/vendor/symfony/console/Descriptor/ApplicationDescription.php
  redaxo/src/core/vendor/symfony/console/Exception/MissingInputException.php
  redaxo/src/core/vendor/symfony/console/Formatter/OutputFormatter.php
  redaxo/src/core/vendor/symfony/console/Formatter/OutputFormatterStyle.php
  redaxo/src/core/vendor/symfony/console/Helper/QuestionHelper.php
  redaxo/src/core/vendor/symfony/console/Helper/Table.php
  redaxo/src/core/vendor/symfony/console/Helper/TableStyle.php
  redaxo/src/core/vendor/symfony/console/Input/StringInput.php
  redaxo/src/core/vendor/symfony/console/Output/StreamOutput.php
  redaxo/src/core/vendor/symfony/console/Question/ChoiceQuestion.php
  redaxo/src/core/vendor/symfony/polyfill-ctype/composer.json
  redaxo/src/core/vendor/symfony/polyfill-intl-grapheme/README.md
  redaxo/src/core/vendor/symfony/polyfill-intl-grapheme/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-intl-grapheme/composer.json
  redaxo/src/core/vendor/symfony/polyfill-intl-normalizer/README.md
  redaxo/src/core/vendor/symfony/polyfill-intl-normalizer/composer.json
  redaxo/src/core/vendor/symfony/polyfill-mbstring/README.md
  redaxo/src/core/vendor/symfony/polyfill-mbstring/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-mbstring/composer.json
  redaxo/src/core/vendor/symfony/polyfill-php72/README.md
  redaxo/src/core/vendor/symfony/polyfill-php72/composer.json
  redaxo/src/core/vendor/symfony/polyfill-php73/composer.json
  redaxo/src/core/vendor/symfony/var-dumper/Cloner/Data.php
  redaxo/src/core/vendor/symfony/var-dumper/Cloner/VarCloner.php
  redaxo/src/core/vendor/symfony/yaml/Dumper.php
  redaxo/src/core/vendor/symfony/yaml/Inline.php
  redaxo/src/core/vendor/symfony/yaml/Parser.php
Labels: automerge

#3456 Phpmailer Update: Umleitung
  redaxo/src/addons/phpmailer/boot.php
  redaxo/src/addons/phpmailer/lang/de_de.lang
  redaxo/src/addons/phpmailer/lang/en_gb.lang
  redaxo/src/addons/phpmailer/lang/es_es.lang
  redaxo/src/addons/phpmailer/lang/sv_se.lang
  redaxo/src/addons/phpmailer/lib/mailer.php
  redaxo/src/addons/phpmailer/package.yml
  redaxo/src/addons/phpmailer/pages/config.php
Labels: Feature, PHPMailer, automerge

#3494 psalm: more types and activate more errors
  .github/tests-visual/packages.png
  .github/tests-visual/phpmailer_config.png
  .github/tests-visual/system_report.png
  composer.json
  psalm.xml
  redaxo/src/addons/backup/lib/tar.php
  redaxo/src/addons/backup/vendor/tar.php
  redaxo/src/addons/cronjob/lib/types/phpcode.php
  redaxo/src/addons/install/pages/packages.add.php
  redaxo/src/addons/media_manager/lib/effects/effect_filter_blur.php
  redaxo/src/addons/media_manager/lib/effects/effect_filter_colorize.php
  redaxo/src/addons/media_manager/lib/effects/effect_filter_sharpen.php
  redaxo/src/addons/mediapool/lib/media_category.php
  redaxo/src/addons/mediapool/lib/service_media_category.php
  redaxo/src/addons/mediapool/pages/structure.php
  redaxo/src/addons/metainfo/pages/content.metainfo.php
  redaxo/src/addons/structure/lib/linkmap/var_linklist.php
  redaxo/src/addons/structure/lib/navigation.php
  redaxo/src/addons/structure/lib/select_category.php
  redaxo/src/addons/structure/lib/structure_element.php
  redaxo/src/addons/structure/plugins/content/install.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
  redaxo/src/addons/structure/plugins/history/pages/system.history.php
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/lib/be/controller.php
  redaxo/src/core/lib/be/page.php
  redaxo/src/core/lib/clang/service.php
  redaxo/src/core/lib/config.php
  redaxo/src/core/lib/console/application.php
  redaxo/src/core/lib/exception.php
  redaxo/src/core/lib/form/elements/options.php
  redaxo/src/core/lib/list.php
  redaxo/src/core/lib/login/complex_perm.php
  redaxo/src/core/lib/packages/interface.php
  redaxo/src/core/lib/response.php
  redaxo/src/core/lib/rex.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/sql/util.php
  redaxo/src/core/lib/util/formatter.php
  redaxo/src/core/lib/util/i18n.php
  redaxo/src/core/lib/var/var.php
Labels: automerge

#3495 $imagick->setResolution wurde ignoriert
  redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
Labels: Bug, automerge

#3493 Installer-API-Key nicht in Repo speichern
  .gitignore.example
Labels: automerge

#3503 Update .gitignore.example
  .gitignore.example
Labels: automerge

#3506 Structure/Content :: module key for module_select fragment
  .github/tests-visual/packages.png
  .github/tests-visual/system_report.png
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/plugins/content/fragments/module_select.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php
  redaxo/src/addons/structure/plugins/content/package.yml
Labels: Enhancement, Structure, automerge

#3507 debug-addon: compat for R<5.11
  redaxo/src/addons/debug/boot.php
Labels: automerge

#3508 convert2img: colorspace korrekt umwandeln
  redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
  redaxo/src/addons/media_manager/package.yml
Labels: automerge

#3510 Clockwork: Aufgelöste Page, bzw. Artikel/Clang anzeigen
  .github/tests-visual/packages.png
  .github/tests-visual/system_report.png
  redaxo/src/addons/debug/boot.php
Labels: Debug, automerge

#3486 Passwortregeln: Passwort muss nach X getauscht werden etc.
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/backend.php
  redaxo/src/core/install.php
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lib/console/setup/run.php
  redaxo/src/core/lib/console/user/create.php
  redaxo/src/core/lib/console/user/set_password.php
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/lib/login/backend_password_policy.php
  redaxo/src/core/pages/profile.php
  redaxo/src/core/pages/setup.php
Labels: Add to Docs, automerge

#3512 pswfunc-Rest entfernen
  redaxo/src/addons/users/lang/de_de.lang
  redaxo/src/addons/users/lang/en_gb.lang
  redaxo/src/addons/users/lang/es_es.lang
  redaxo/src/addons/users/lang/pt_br.lang
  redaxo/src/addons/users/lang/sv_se.lang
  redaxo/src/addons/users/pages/users.php
Labels: automerge

#3514 Dokumentierten Return-Type auch wirklich zurückgeben
  redaxo/src/core/lib/clang/clang.php
  redaxo/src/core/lib/login/user.php
  redaxo/src/core/tests/clang/clang_test.php
Labels: automerge

#3513 Optional explizit Passwortänderung erfordern
  redaxo/src/addons/users/lang/de_de.lang
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/backend.php
  redaxo/src/core/install.php
  redaxo/src/core/lib/console/user/create.php
  redaxo/src/core/lib/console/user/set_password.php
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/pages/profile.php
Labels: automerge

#3520 Debug: use cache folder
  redaxo/src/addons/debug/lib/debug.php
Labels: automerge

#3516 debug: use `rex_sql::getQueryType()`
  redaxo/src/addons/debug/boot.php
Labels: Debug, Enhancement, automerge

#3519 Weitere Stellen mit rex_timer messen
  redaxo/src/addons/debug/boot.php
  redaxo/src/core/lib/be/controller.php
  redaxo/src/core/lib/fragment.php
Labels: automerge

#3515 debug: initiale readme
  redaxo/src/addons/debug/README.md
Labels: Debug, Enhancement, automerge

#3523 debug: added example to readme
  redaxo/src/addons/debug/README.md
Labels: Debug, Enhancement, automerge

#3521 Debug-Timeline: EPs über normalen rex_timer-Mechanismus
  redaxo/src/addons/debug/lib/extension_debug.php
  redaxo/src/core/lib/extension.php
  redaxo/src/core/lib/login/user.php
Labels: automerge

#3530 psalm: Anpassungen für neue Version
  psalm.xml
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/structure/lib/article.php
  redaxo/src/addons/structure/lib/category.php
  redaxo/src/addons/users/lib/role.php
  redaxo/src/core/lib/form/form.php
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/list.php
  redaxo/src/core/lib/login/role.php
  redaxo/src/core/lib/login/user.php
  redaxo/src/core/lib/util/log_file.php
Labels: automerge

#3528 added google chrome workaround for slow clear-site-data bug
  redaxo/src/core/backend.php
Labels: Core, Enhancement, automerge

#3531 psalm: Anpassungen für neue Version
  redaxo/src/addons/install/lib/packages.php
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/users/lib/role.php
  redaxo/src/core/console.php
  redaxo/src/core/lib/config.php
  redaxo/src/core/lib/console/application.php
  redaxo/src/core/lib/packages/addons/addon.php
  redaxo/src/core/lib/packages/interface.php
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/lib/rex.php
  redaxo/src/core/lib/setup/import.php
  redaxo/src/core/lib/util/socket/socket_response.php
  redaxo/src/core/packages.php
Labels: automerge

#3532 rex_timer::measure: nur im Debugmode messen
  redaxo/src/core/lib/util/timer.php
Labels: automerge

#3536 added phpdoc
  redaxo/src/core/lib/login/complex_perm.php
Labels: automerge

#3539 Fix typo
  redaxo/src/core/lib/form/form.php
Labels: automerge

#3540 Fix typo
  redaxo/src/core/lib/form/form_base.php
Labels: automerge

#3544 Added phpdoc
  redaxo/src/core/lib/util/validator.php
Labels: automerge

#3547 Added phpdoc
  redaxo/src/core/lib/form/form_base.php
Labels: automerge

#3548 Systembericht: DB-Version in Zusammenfassung
  redaxo/src/core/lib/system_report.php
Labels: automerge

#3541 Added phpdocs
  redaxo/src/core/lib/form/form_base.php
Labels: automerge

#3550 GithubAction: added phpstan result cache
  .github/workflows/push.yml
  phpstan.neon.dist
Labels: automerge

#3551 Fixed phpstan result-cache - take 2
  .github/workflows/push.yml
  phpstan.neon.dist
Labels: automerge

#3552 GithubAction: added psalm result cache
  .github/workflows/push.yml
Labels: automerge

#3553 Use php 7.4 in CI tool jobs
  .github/workflows/push.yml
Labels: automerge

#3554 MM: Toggle-JS korrigiert
  redaxo/src/addons/media_manager/lib/effects/effect_mirror.php
  redaxo/src/addons/media_manager/lib/effects/effect_resize.php
  redaxo/src/addons/media_manager/lib/effects/effect_workspace.php
Labels: Bug, Media Manager, automerge

#3555 added rex_list phpdocs
  redaxo/src/core/lib/list.php
Labels: automerge

#3557 Added shepherd project url
  README.de.md
  README.md
Labels: automerge

#3558 debug: fix notice
  redaxo/src/addons/debug/lib/debug.php
Labels: Bug, Debug, automerge

#3549 Slice Status in rex_article_slice berücksichtigen
  redaxo/src/addons/structure/plugins/content/lib/article_slice.php
Labels: automerge

#3533 Caching für Template/Module-Keys
  redaxo/src/addons/structure/plugins/content/lib/api_module.php
  redaxo/src/addons/structure/plugins/content/lib/api_template.php
  redaxo/src/addons/structure/plugins/content/lib/cache_module.php
  redaxo/src/addons/structure/plugins/content/lib/cache_template.php
  redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
  redaxo/src/addons/structure/plugins/content/pages/templates.php
Labels: automerge

#3561 rex_sql: properly restore DBID on Exceptions in setDBQuery
  redaxo/src/core/lib/sql/sql.php
Labels: Bug, Core, automerge

#3564 psalm: analyse only changed files
  .github/workflows/push.yml
Labels: automerge

#3560 Added phpdocs
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#3545 Environment as table, ask for database
  .github/ISSUE_TEMPLATE/---bug-report.md
Labels: Developer Experience (DX), automerge

#3567 Systemreport: SQL-Fehler abfangen
  redaxo/src/core/lib/system_report.php
Labels: automerge

#3534 Templateausführung messen
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
  redaxo/src/addons/structure/plugins/content/lib/var_template.php
  redaxo/src/addons/structure/plugins/content/package.yml
  redaxo/src/core/lib/util/timer.php
Labels: automerge

#3569 psalm: add symfony plugin
  composer.json
  psalm.xml
  redaxo/src/addons/install/lib/command/download.php
  redaxo/src/addons/install/lib/command/update.php
  redaxo/src/core/lib/console/package/activate.php
  redaxo/src/core/lib/console/package/deactivate.php
  redaxo/src/core/lib/console/package/delete.php
  redaxo/src/core/lib/console/package/install.php
  redaxo/src/core/lib/console/package/uninstall.php
Labels: automerge

#3570 Artikel-Content-Generierung: Exception bei Fehlern
  redaxo/src/addons/structure/plugins/content/lib/article_content.php
  redaxo/src/addons/structure/plugins/content/lib/content_service.php
Labels: Bug, Structure, automerge

#3571 Update vendors
  redaxo/bin/update-requirements
  redaxo/src/addons/be_style/composer.lock
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/composer.json
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Cache.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Colors.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Compiler.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/Nested.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Node/Number.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Parser.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/SourceMap/SourceMapGenerator.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Version.php
  redaxo/src/addons/phpmailer/composer.lock
  redaxo/src/addons/tests/composer.lock
  redaxo/src/addons/tests/vendor/phpdocumentor/reflection-common/composer.json
  redaxo/src/addons/tests/vendor/phpdocumentor/reflection-common/src/Element.php
  redaxo/src/addons/tests/vendor/phpdocumentor/reflection-common/src/File.php
  redaxo/src/addons/tests/vendor/phpdocumentor/reflection-common/src/Fqsen.php
  redaxo/src/addons/tests/vendor/phpdocumentor/reflection-common/src/Location.php
  redaxo/src/addons/tests/vendor/phpdocumentor/reflection-common/src/Project.php
  redaxo/src/addons/tests/vendor/phpdocumentor/reflection-common/src/ProjectFactory.php
  redaxo/src/addons/tests/vendor/webmozart/assert/CHANGELOG.md
  redaxo/src/addons/tests/vendor/webmozart/assert/README.md
  redaxo/src/addons/tests/vendor/webmozart/assert/ci/composer.json
  redaxo/src/addons/tests/vendor/webmozart/assert/composer.json
  redaxo/src/addons/tests/vendor/webmozart/assert/src/Assert.php
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/autoload_real.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/symfony/var-dumper/Server/DumpServer.php
  redaxo/src/core/vendor/symfony/yaml/Escaper.php
  redaxo/src/core/vendor/symfony/yaml/Inline.php
Labels: automerge

#3574 GithubAction: run REX-Lint, cs-check & visual-tests only for non-draft PRs
  .github/workflows/csfix.yml
  .github/workflows/push.yml
  .github/workflows/visual-tests.yml
Labels: automerge

#3572 psalm: activate more errors
  psalm.xml
  redaxo/src/addons/backup/vendor/tar.php
  redaxo/src/addons/install/lib/packages.php
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
  redaxo/src/addons/mediapool/pages/media.list.php
  redaxo/src/addons/metainfo/extensions/extension_content_sidebar.php
  redaxo/src/addons/metainfo/functions/function_metainfo.php
  redaxo/src/addons/metainfo/pages/content.metainfo.php
  redaxo/src/addons/users/lib/role.php
  redaxo/src/core/boot.php
  redaxo/src/core/lib/console/setup/run.php
  redaxo/src/core/lib/form/elements/container.php
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/lib/packages/package.php
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/lib/util/formatter.php
  redaxo/src/core/lib/util/i18n.php
  redaxo/src/core/lib/util/socket/socket.php
Labels: automerge
