Repository redaxo/redaxo, pull requests merged in 2020-02, with the labels that each got.

#3248 Text-Korrekturen Backup
  redaxo/src/addons/backup/lang/de_de.lang
Labels: automerge

#3256 MM: rotate-Effekt: Transparenz erhalten
  redaxo/src/addons/media_manager/lib/effects/effect_rotate.php
Labels: automerge

#3247 Support für PHP-imagick extension
  redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
Labels: automerge

#3220 Phpstan: level++
  phpstan.neon.dist
  redaxo/src/addons/be_style/lib/scss_compiler.php
  redaxo/src/addons/media_manager/lib/effect_abstract.php
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
  redaxo/src/addons/metainfo/lib/handler/article_handler.php
  redaxo/src/addons/metainfo/lib/input/date.php
  redaxo/src/addons/structure/lib/select_category.php
  redaxo/src/addons/structure/plugins/content/pages/content.php
  redaxo/src/core/lib/clang/clang.php
  redaxo/src/core/lib/console/list_command.php
  redaxo/src/core/lib/login/login.php
  redaxo/src/core/lib/packages/addons/manager.php
  redaxo/src/core/lib/packages/interface.php
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/lib/packages/plugins/manager.php
  redaxo/src/core/lib/response.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/util/i18n.php
Labels: automerge

#3258 ImageMagick-Hinweis korrigiert
  redaxo/src/addons/media_manager/lang/de_de.lang
  redaxo/src/addons/media_manager/lang/en_gb.lang
  redaxo/src/addons/media_manager/lang/es_es.lang
  redaxo/src/addons/media_manager/lang/sv_se.lang
  redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
Labels: automerge

#3257 php-cs-fixer 2.16 nutzen + CS-Anpassungen
  .github/workflows/csfix.yml
  .github/workflows/push.yml
  .php_cs.dist
  redaxo/src/addons/media_manager/tests/managed_media_test.php
  redaxo/src/addons/media_manager/tests/media_manager_test.php
  redaxo/src/addons/mediapool/tests/media_test.php
  redaxo/src/addons/mediapool/tests/mediapool_functions_test.php
  redaxo/src/addons/structure/lib/navigation.php
  redaxo/src/addons/structure/plugins/content/tests/article_content_base_test.php
  redaxo/src/addons/structure/plugins/content/tests/article_content_test.php
  redaxo/src/addons/structure/tests/article_test.php
  redaxo/src/addons/structure/tests/category_test.php
  redaxo/src/addons/structure/tests/navigation_test.php
  redaxo/src/core/lib/api_function.php
  redaxo/src/core/lib/fragment.php
  redaxo/src/core/lib/request.php
  redaxo/src/core/lib/response.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/sql/util.php
  redaxo/src/core/tests/base/factory_trait_test.php
  redaxo/src/core/tests/base/instance_list_pool_trait_test.php
  redaxo/src/core/tests/base/instance_pool_trait_test.php
  redaxo/src/core/tests/base/singleton_trait_test.php
  redaxo/src/core/tests/clang/clang_test.php
  redaxo/src/core/tests/config_test.php
  redaxo/src/core/tests/console/command_test.php
  redaxo/src/core/tests/context_test.php
  redaxo/src/core/tests/extension_test.php
  redaxo/src/core/tests/login/backend_login_test.php
  redaxo/src/core/tests/login/password_policy_test.php
  redaxo/src/core/tests/packages/manager_test.php
  redaxo/src/core/tests/path_test.php
  redaxo/src/core/tests/rex_test.php
  redaxo/src/core/tests/sql/sql_select_test.php
  redaxo/src/core/tests/sql/sql_table_test.php
  redaxo/src/core/tests/sql/sql_test.php
  redaxo/src/core/tests/util/dir_test.php
  redaxo/src/core/tests/util/file_test.php
  redaxo/src/core/tests/util/finder_test.php
  redaxo/src/core/tests/util/formatter_test.php
  redaxo/src/core/tests/util/i18n_test.php
  redaxo/src/core/tests/util/log_entry_test.php
  redaxo/src/core/tests/util/log_file_test.php
  redaxo/src/core/tests/util/markdown_test.php
  redaxo/src/core/tests/util/socket_proxy_test.php
  redaxo/src/core/tests/util/socket_response_test.php
  redaxo/src/core/tests/util/socket_test.php
  redaxo/src/core/tests/util/sortable_iterator_test.php
  redaxo/src/core/tests/util/stream_test.php
  redaxo/src/core/tests/util/string_test.php
  redaxo/src/core/tests/util/timer_test.php
  redaxo/src/core/tests/util/type_test.php
  redaxo/src/core/tests/util/validator_test.php
  redaxo/src/core/tests/var/var_base_test.php
  redaxo/src/core/tests/view_test.php
Labels: automerge

#3253 Support mysql8
  .travis.yml
  redaxo/src/core/lib/sql/column.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/sql/table.php
  redaxo/src/core/tests/sql/sql_table_test.php
Labels: Core, Enhancement, automerge

#3259 Mimetype-Bestimung beim MP-Sync korrigiert
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
Labels: automerge

#3261 Backup: Null-Values als solche exportieren
  redaxo/src/addons/backup/CHANGELOG.md
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/backup/package.yml
Labels: Backup, Bug, automerge

#3265 be_style/customizer: declare zip dependency
  redaxo/src/addons/be_style/plugins/customizer/package.yml
Labels: Bug, automerge

#3056 psalter --issues=InvalidReturnType --php-version=5.6
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
  redaxo/src/addons/mediapool/lib/media_category.php
  redaxo/src/addons/metainfo/lib/table_expander.php
  redaxo/src/addons/structure/lib/article.php
  redaxo/src/addons/structure/lib/cache_article.php
  redaxo/src/addons/structure/lib/service_article.php
  redaxo/src/addons/structure/lib/structure_element.php
  redaxo/src/addons/structure/plugins/content/lib/content_service.php
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/login/login.php
  redaxo/src/core/lib/packages/addons/addon.php
  redaxo/src/core/lib/packages/addons/interface.php
  redaxo/src/core/lib/packages/addons/null.php
  redaxo/src/core/lib/packages/interface.php
  redaxo/src/core/lib/packages/null.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/util/pager.php
Labels: automerge

#3272 cs2pr is now built into shivammathur/setup-php@v1
  .github/workflows/push.yml
Labels: automerge

#3270 Metainfo: TEXT-Spalten ohne Defaults
  redaxo/src/addons/metainfo/lib/table_expander.php
  redaxo/src/addons/metainfo/lib/table_manager.php
  redaxo/src/addons/metainfo/package.yml
Labels: automerge

#3271 Metainfo: Im Template-Filter auch Templates mit Kategoriebeschränkung listen
  redaxo/src/addons/metainfo/lib/table_expander.php
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/plugins/content/lib/select_template.php
  redaxo/src/addons/structure/plugins/content/package.yml
Labels: automerge

#3273 Package-Ladereihenfolge korrigiert
  redaxo/src/core/boot.php
  redaxo/src/core/lib/packages/manager.php
Labels: automerge

#3277 phpstan: level++
  phpstan.neon.dist
Labels: automerge

#3278 phpstan: level++
  phpstan.neon.dist
Labels: automerge

#3279 phpstan: level++
  phpstan.neon.dist
Labels: automerge

#3282 Fix invalid phpstan config
  phpstan.neon.dist
Labels: automerge

#3298 Fix psalm errors
  .github/workflows/push.yml
  redaxo/src/addons/mediapool/pages/media.list.php
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/lib/response.php
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#3284 SQL-Debugausgabe: Parameter in fullquery richtig ersetzen
  redaxo/src/core/lib/sql/sql.php
Labels: Bug, Core, automerge

#3285 Codemirror-Zip: Ziel mit absolutem Pfad angeben
  redaxo/src/addons/be_style/package.yml
  redaxo/src/addons/be_style/plugins/customizer/install.php
  redaxo/src/addons/be_style/plugins/customizer/package.yml
Labels: automerge

#3299 Update vendors
  redaxo/src/addons/be_style/assets/css/styles.css
  redaxo/src/addons/be_style/composer.lock
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/README.md
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Base/Range.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Block.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Cache.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Colors.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Compiler.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Compiler/Environment.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Exception/CompilerException.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Exception/ParserException.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Exception/RangeException.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Exception/ServerException.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/Compact.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/Compressed.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/Crunched.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/Debug.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/Expanded.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/Nested.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/OutputBlock.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Node.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Node/Number.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Parser.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/SourceMap/Base64.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/SourceMap/Base64VLQ.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/SourceMap/SourceMapGenerator.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Type.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Util.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Version.php
  redaxo/src/addons/tests/composer.lock
  redaxo/src/addons/tests/vendor/webmozart/assert/CHANGELOG.md
  redaxo/src/addons/tests/vendor/webmozart/assert/README.md
  redaxo/src/addons/tests/vendor/webmozart/assert/ci/composer.json
  redaxo/src/addons/tests/vendor/webmozart/assert/src/Assert.php
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/symfony/console/Application.php
  redaxo/src/core/vendor/symfony/polyfill-ctype/composer.json
  redaxo/src/core/vendor/symfony/polyfill-mbstring/Mbstring.php
  redaxo/src/core/vendor/symfony/polyfill-mbstring/composer.json
  redaxo/src/core/vendor/symfony/polyfill-php72/composer.json
  redaxo/src/core/vendor/symfony/polyfill-php73/composer.json
  redaxo/src/core/vendor/symfony/var-dumper/Caster/ClassStub.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/ExceptionCaster.php
Labels: automerge

#3295 rex_config: id-Spalte löschen, falls noch vorhanden
  redaxo/src/core/install.php
Labels: automerge

#3294 Parsedown immer aus Core-Vendors laden
  redaxo/src/core/lib/autoload.php
Labels: automerge

#3293 rex_media_manager::getUrl(): Immer Frontend-URL generieren
  redaxo/src/addons/media_manager/lib/media_manager.php
  redaxo/src/addons/media_manager/package.yml
Labels: Bug, Media Manager, automerge

#3301 fix psalm and phpstan
  phpstan.neon.dist
  psalm-utils.php
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/backup/lib/tar.php
  redaxo/src/addons/backup/vendor/tar.php
  redaxo/src/addons/cronjob/lib/form.php
  redaxo/src/addons/cronjob/lib/manager_sql.php
  redaxo/src/addons/install/lib/api_core_update.php
  redaxo/src/addons/structure/lib/structure_element.php
  redaxo/src/core/lib/packages/interface.php
  redaxo/src/core/lib/packages/manager.php
Labels: automerge

#3302 CS in Fragmenten und psalm-utils fixen
  .php_cs.dist
  psalm-utils.php
  redaxo/src/addons/structure/plugins/content/fragments/module_select.php
  redaxo/src/addons/structure/plugins/history/fragments/history/layer.php
  redaxo/src/core/fragments/core/bottom.php
  redaxo/src/core/fragments/core/buttons/button_group.php
  redaxo/src/core/fragments/core/dropdowns/dropdown.php
  redaxo/src/core/fragments/core/form/checkbox.php
  redaxo/src/core/fragments/core/form/container.php
  redaxo/src/core/fragments/core/form/form.php
  redaxo/src/core/fragments/core/form/input_group.php
  redaxo/src/core/fragments/core/form/radio.php
  redaxo/src/core/fragments/core/form/submit.php
  redaxo/src/core/fragments/core/form/widget.php
  redaxo/src/core/fragments/core/form/widget_list.php
  redaxo/src/core/fragments/core/navigation.php
  redaxo/src/core/fragments/core/navigations/breadcrumb.php
  redaxo/src/core/fragments/core/navigations/content.php
  redaxo/src/core/fragments/core/navigations/main.php
  redaxo/src/core/fragments/core/navigations/meta.php
  redaxo/src/core/fragments/core/page/grid.php
  redaxo/src/core/fragments/core/page/header.php
  redaxo/src/core/fragments/core/page/main_content.php
  redaxo/src/core/fragments/core/page/section.php
  redaxo/src/core/fragments/core/toolbar.php
  redaxo/src/core/fragments/core/top.php
Labels: automerge

#3305 Einheitliche Collation _unicode_ci verwenden
  redaxo/src/core/lib/sql/table.php
Labels: Bug, Core, automerge

#3304 Neue Methode rex_file::mimeType(), um svg-Problem zu lösen
  redaxo/src/addons/media_manager/lib/managed_media.php
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
  redaxo/src/addons/mediapool/package.yml
  redaxo/src/addons/mediapool/pages/media.detail.php
  redaxo/src/addons/mediapool/pages/upload.php
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/lib/util/file.php
  redaxo/src/core/tests/util/file_test.php
Labels: Core, Media Manager, Mediapool, automerge

#3306 composer.json im Root für Tools
  .github/workflows/csfix.yml
  .github/workflows/push.yml
  .gitignore
  composer.json
  phpstan.neon.dist
  psalm.xml
Labels: automerge

#3307 PhpStorm settings
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/encodings.xml
  .idea/fileTemplates/code/PHP Constructor.php
  .idea/fileTemplates/code/PHP Fluent Setter Method.php
  .idea/fileTemplates/code/PHP Getter Method.php
  .idea/fileTemplates/code/PHP Setter Method.php
  .idea/fileTemplates/includes/PHP Class Doc Comment.php
  .idea/fileTemplates/includes/PHP Property Doc Comment.php
  .idea/fileTemplates/internal/PHP Class.php
  .idea/fileTemplates/internal/PHP Interface.php
  .idea/fileTemplates/internal/PHP Trait.php
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/php.xml
  .idea/redaxo.iml
  .idea/scopes/core___core_addons.xml
  .idea/sqldialects.xml
Labels: Contributor Experience, automerge

#3310 added mysql and mariadb EOL checks
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/pages/setup.php
Labels: automerge

#3316 Version 5.10.0-dev
  redaxo/src/core/boot.php
Labels: automerge

#3315 added rex_response::sendJson()
  redaxo/src/core/lib/login/api_has_user_session.php
  redaxo/src/core/lib/response.php
Labels: automerge

#3322 PhpStorm-Settings aktualisiert
  .idea/inspectionProfiles/Project_Default.xml
  .idea/redaxo.iml
Labels: automerge

#3323 added media-category extension points: MEDIA_CATEGORY_ADDED, MEDIA_CA…
  redaxo/src/addons/mediapool/lib/service_media_category.php
Labels: automerge

#3321 svg auch convert2img verarbeiten
  redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
Labels: automerge

#3317 refactored EOL checks into rex_setup class for re-use in redaxo console
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/pages/setup.php
Labels: Enhancement, automerge

#3319 Transparenzen bei Bildkonvertierung korrigiert
  redaxo/src/addons/media_manager/lang/de_de.lang
  redaxo/src/addons/media_manager/lang/en_gb.lang
  redaxo/src/addons/media_manager/lang/es_es.lang
  redaxo/src/addons/media_manager/lang/sv_se.lang
  redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
Labels: automerge

#3325 Backup: archive anhand des dateinamens sortieren
  redaxo/src/addons/backup/lib/backup.php
Labels: Backup, Enhancement, automerge

#3326 console: setup eol warnings
  redaxo/src/core/lib/console/setup/run.php
Labels: Console, Enhancement, automerge

#3328 convert string callable to array notation
  redaxo/src/addons/media_manager/boot.php
  redaxo/src/addons/mediapool/lib/media.php
  redaxo/src/addons/mediapool/lib/media_category.php
  redaxo/src/addons/users/boot.php
  redaxo/src/core/lib/packages/addons/addon.php
  redaxo/src/core/lib/packages/null.php
  redaxo/src/core/lib/packages/plugins/plugin.php
  redaxo/src/core/tests/base/instance_list_pool_trait_test.php
  redaxo/src/core/tests/util/i18n_test.php
Labels: Developer Experience (DX), Enhancement, automerge

#3327 split setup steps into separate files
  redaxo/src/core/pages/setup.php
  redaxo/src/core/pages/setup.step1.php
  redaxo/src/core/pages/setup.step2.php
  redaxo/src/core/pages/setup.step3.php
  redaxo/src/core/pages/setup.step4.php
  redaxo/src/core/pages/setup.step5.php
  redaxo/src/core/pages/setup.step6.php
  redaxo/src/core/pages/setup.step7.php
Labels: Enhancement, Setup, automerge

#3311 added rex_sql options to support mysql with ssl
  .github/workflows/default.config.yml.github-action.diff
  redaxo/src/core/default.config.yml
  redaxo/src/core/lib/sql/sql.php
Labels: Add to Docs, automerge

#3308 Console: added install:list command
  redaxo/src/addons/install/lib/command/list.php
  redaxo/src/addons/install/package.yml
Labels: Add to Docs, Console, Installer, automerge

#3330 removed unnecessary bc code
  redaxo/src/addons/structure/lib/service_article.php
  redaxo/src/addons/structure/lib/service_category.php
  redaxo/src/addons/structure/plugins/content/lib/content_service.php
Labels: Enhancement, automerge

#3331 actviate phpstan for core-tests
  composer.json
  phpstan.neon.dist
  redaxo/src/core/tests/var/var_config_test.php
  redaxo/src/core/tests/var/var_property_test.php
Labels: automerge

#3324 REX_TEMPLATE_KEY implementiert
  redaxo/src/addons/structure/plugins/content/lib/api_template.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
  redaxo/src/addons/structure/plugins/content/lib/var_template.php
Labels: Add to Docs, automerge

#3333 activate phpstan for addon tests
  composer.json
  phpstan.neon.dist
Labels: automerge

#3329 Readme: added contribution details
  README.de.md
  README.md
Labels: automerge

#3297 rex_console_command tests
  redaxo/bin/update-requirements
  redaxo/src/core/tests/console/config/get_test.php
  redaxo/src/core/vendor/composer/autoload_classmap.php
  redaxo/src/core/vendor/composer/autoload_static.php
  redaxo/src/core/vendor/symfony/console/Tester/ApplicationTester.php
  redaxo/src/core/vendor/symfony/console/Tester/CommandTester.php
  redaxo/src/core/vendor/symfony/console/Tester/TesterTrait.php
Labels: automerge

#3334 remove always-true condition
  redaxo/src/addons/structure/pages/index.php
Labels: automerge

#3332 render status as dropdown if count(status) > 2
  redaxo/src/addons/structure/lib/api_functions/api_article_status.php
  redaxo/src/addons/structure/lib/api_functions/api_category_status.php
  redaxo/src/addons/structure/lib/service_article.php
  redaxo/src/addons/structure/lib/service_category.php
  redaxo/src/addons/structure/pages/index.php
Labels: Add to Docs, Enhancement, Structure, automerge

#3287 CONSOLE :: check ssh user/owner and advise
  redaxo/src/core/lib/console/application.php
Labels: Console, Enhancement, automerge

#3336 add cronjob environment information to log
  redaxo/src/addons/cronjob/lang/de_de.lang
  redaxo/src/addons/cronjob/lib/manager.php
  redaxo/src/addons/cronjob/pages/log.php
Labels: Cronjob, Enhancement, automerge

#3335 hide password in setup
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/pages/setup.php
  redaxo/src/core/pages/setup.step4.php
Labels: automerge

#3314 Link zu Webseite hinzufügen die die Rahmenbedinugungen von Lizenzen erklärt
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/pages/packages.php
Labels: automerge

#3339 save a sql query when retrieving a template from id and call getKey()
  redaxo/src/addons/structure/plugins/content/lib/api_template.php
Labels: Enhancement, automerge

#3312 REX_MODULE_KEY implementieren
  redaxo/src/addons/structure/plugins/content/install.php
  redaxo/src/addons/structure/plugins/content/lang/de_de.lang
  redaxo/src/addons/structure/plugins/content/lib/api_module.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
  redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
  redaxo/src/core/lib/exception.php
  redaxo/src/core/lib/sql/sql.php
Labels: Add to Docs, automerge

#3338 install: refactoring
  redaxo/src/addons/install/lib/api/api_core_update.php
  redaxo/src/addons/install/lib/api/api_package_add.php
  redaxo/src/addons/install/lib/api/api_package_delete.php
  redaxo/src/addons/install/lib/api/api_package_update.php
  redaxo/src/addons/install/lib/api/api_package_upload.php
  redaxo/src/addons/install/lib/api_package_add.php
  redaxo/src/addons/install/lib/package/package_add.php
  redaxo/src/addons/install/lib/package/package_download.php
  redaxo/src/addons/install/lib/package/package_update.php
Labels: Enhancement, Installer, automerge

#3340 simplify template already exists validation
  redaxo/src/addons/structure/plugins/content/pages/templates.php
Labels: automerge

#3342 remove html markup from checkPhpSecurity() & checkDbSecurity()
  redaxo/src/core/lib/console/setup/run.php
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/pages/setup.step3.php
  redaxo/src/core/pages/setup.step5.php
Labels: Enhancement, automerge

#3341 report php/mysql security checks in sysreport
  redaxo/src/core/lib/system_report.php
Labels: Core, Feature, automerge

#3343 added category_id param to MEDIA_ADDED, MEDIA_UPDATED
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
Labels: Enhancement, Mediapool, automerge

#3345 fixed rendering of cronjob.log rex_editor button
  redaxo/src/addons/cronjob/pages/log.php
Labels: Bug, Cronjob, automerge

#3344 extract constants
  redaxo/src/addons/media_manager/lib/effects/effect_image_properties.php
  redaxo/src/addons/media_manager/lib/managed_media.php
Labels: automerge

#3346 fix typo
  redaxo/src/addons/structure/plugins/content/lib/api_functions/api_content_copy.php
Labels: automerge

#3348 fix typos
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/lib/system_report.php
Labels: automerge

#3347 implement rex_file::move()
  redaxo/src/core/lib/util/file.php
Labels: Core, Enhancement, automerge

#3351 add save/apply button titles
  redaxo/src/addons/media_manager/pages/settings.php
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php
  redaxo/src/addons/structure/plugins/content/pages/modules.actions.php
  redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
  redaxo/src/addons/structure/plugins/content/pages/templates.php
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lib/form/form.php
Labels: automerge

#3349 Default-Config in package.yml ermöglichen
  redaxo/src/addons/install/lib/api/api_core_update.php
  redaxo/src/addons/install/lib/package/package_update.php
  redaxo/src/addons/media_manager/install.php
  redaxo/src/addons/media_manager/lib/managed_media.php
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/addons/media_manager/pages/settings.php
  redaxo/src/addons/phpmailer/install.php
  redaxo/src/addons/phpmailer/package.yml
  redaxo/src/core/lib/packages/manager.php
Labels: automerge

#3354 console: added package:delete
  redaxo/src/core/lib/console/command_loader.php
  redaxo/src/core/lib/console/package/delete.php
Labels: Console, Core, Feature, automerge

#3353 console: added install:download
  redaxo/src/addons/install/lib/command/download.php
  redaxo/src/addons/install/package.yml
Labels: Add to Docs, Console, Feature, Installer, automerge

#3337 Metainfoform fest in Sidebar
  redaxo/src/addons/metainfo/assets/metainfo.css
  redaxo/src/addons/metainfo/boot.php
  redaxo/src/addons/metainfo/package.yml
  redaxo/src/addons/metainfo/pages/content.metainfo.php
  redaxo/src/addons/structure/plugins/content/boot.php
Labels: Add to Docs, automerge

#3355 Core-Update: Doppel-rename statt löschen+rename
  redaxo/src/addons/install/lib/api/api_core_update.php
Labels: automerge

#3357 rex_package: Korrekte Return-Types, neue Methode rex_package::require()
  redaxo/src/core/console.php
  redaxo/src/core/lib/console/application.php
  redaxo/src/core/lib/packages/addons/addon.php
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/lib/packages/package.php
  redaxo/src/core/lib/packages/plugins/plugin.php
  redaxo/src/core/lib/setup/import.php
  redaxo/src/core/packages.php
Labels: Core, Enhancement, automerge

#3360 phpmailer_log_info > phpmailer_archive_info
  redaxo/src/addons/phpmailer/pages/config.php
Labels: Bug, PHPMailer

#3358 Fix phpdocs
  redaxo/src/addons/install/lib/package/package_update.php
  redaxo/src/addons/install/lib/packages.php
  redaxo/src/addons/mediapool/lib/media_category.php
  redaxo/src/addons/mediapool/lib/media_category_select.php
  redaxo/src/addons/metainfo/lib/input.php
  redaxo/src/addons/structure/lib/navigation.php
  redaxo/src/addons/structure/lib/select_category.php
  redaxo/src/addons/structure/lib/structure_element.php
  redaxo/src/addons/users/lib/role.php
Labels: Enhancement, automerge

#3356 Installer: Temp-Dateien besser löschen, Abbruch bei Entpack-Fehler
  redaxo/src/addons/install/lib/api/api_core_update.php
  redaxo/src/addons/install/lib/api/api_package_upload.php
  redaxo/src/addons/install/lib/archive.php
  redaxo/src/addons/install/lib/package/package_download.php
Labels: automerge

#3362 Vendor updates
  redaxo/bin/update-requirements
  redaxo/src/addons/be_style/composer.lock
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Compiler.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Node/Number.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Parser.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Type.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Version.php
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/autoload_classmap.php
  redaxo/src/core/vendor/composer/autoload_static.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/symfony/service-contracts/Test/ServiceLocatorTest.php
Labels: automerge

#3363 Composer: classmap-authoritative über dumpautoload setzen
  redaxo/bin/update-requirements
  redaxo/src/core/lib/autoload.php
  redaxo/src/core/vendor/composer/autoload_real.php
Labels: automerge

#3364 redaxo/bin/refresh: Tools über Composer aktualisieren
  redaxo/bin/refresh
Labels: automerge

#3366 .phpstorm.meta.php: typo fix
  redaxo/src/core/.phpstorm.meta.php
Labels: automerge

#3365 psalm: activate more errors
  psalm.xml
  redaxo/src/addons/backup/pages/export.php
  redaxo/src/addons/backup/vendor/tar.php
  redaxo/src/addons/be_style/plugins/customizer/pages/system.customizer.php
  redaxo/src/addons/cronjob/lib/form.php
  redaxo/src/addons/cronjob/pages/cronjobs.php
  redaxo/src/addons/install/lib/command/download.php
  redaxo/src/addons/mediapool/lib/media_category.php
  redaxo/src/addons/mediapool/pages/media.list.php
  redaxo/src/addons/structure/lib/article.php
  redaxo/src/addons/structure/lib/service_article.php
  redaxo/src/addons/structure/lib/service_category.php
  redaxo/src/addons/structure/lib/structure_element.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
  redaxo/src/addons/structure/plugins/content/lib/content_service.php
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/it_it.lang
  redaxo/src/core/lang/nl_nl.lang
  redaxo/src/core/lang/pt_br.lang
  redaxo/src/core/lang/sv_se.lang
  redaxo/src/core/lib/console/setup/run.php
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/login/api_user_impersonate.php
  redaxo/src/core/lib/login/login.php
  redaxo/src/core/lib/login/role.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/sql/util.php
  redaxo/src/core/lib/util/finder.php
  redaxo/src/core/lib/util/i18n.php
  redaxo/src/core/lib/var/var.php
  redaxo/src/core/pages/system.settings.php
Labels: automerge

#3361 Fix phpdocs
  redaxo/src/addons/mediapool/pages/media.list.php
  redaxo/src/core/lib/be/controller.php
  redaxo/src/core/lib/clang/clang.php
  redaxo/src/core/lib/console/system/report.php
  redaxo/src/core/lib/form/form.php
  redaxo/src/core/lib/form/form_base.php
Labels: automerge

#3372 console: install:download - decode html
  redaxo/src/addons/install/lib/command/download.php
Labels: Console, Installer, automerge

#3373 psalm: activate more errors
  psalm.xml
  redaxo/src/addons/cronjob/lib/manager_sql.php
  redaxo/src/addons/debug/lib/sql_debug.php
  redaxo/src/addons/media_manager/lib/media_manager.php
  redaxo/src/addons/mediapool/lib/media.php
  redaxo/src/addons/mediapool/lib/media_category.php
  redaxo/src/addons/metainfo/extensions/extension_cleanup.php
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/structure/lib/article.php
  redaxo/src/addons/structure/lib/category.php
  redaxo/src/addons/structure/lib/structure_element.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
  redaxo/src/addons/structure/plugins/content/lib/article_slice.php
  redaxo/src/addons/structure/plugins/history/boot.php
  redaxo/src/addons/tests/lib/test_locator.php
  redaxo/src/core/fragments/core/form/form.php
  redaxo/src/core/lib/api_function.php
  redaxo/src/core/lib/be/controller.php
  redaxo/src/core/lib/be/page.php
  redaxo/src/core/lib/clang/clang.php
  redaxo/src/core/lib/console/package/activate.php
  redaxo/src/core/lib/console/package/deactivate.php
  redaxo/src/core/lib/console/package/delete.php
  redaxo/src/core/lib/console/package/install.php
  redaxo/src/core/lib/console/package/uninstall.php
  redaxo/src/core/lib/form/elements/element.php
  redaxo/src/core/lib/form/elements/prio.php
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/lib/login/complex_perm.php
  redaxo/src/core/lib/login/login.php
  redaxo/src/core/lib/login/user.php
  redaxo/src/core/lib/packages/addons/addon.php
  redaxo/src/core/lib/packages/api_package.php
  redaxo/src/core/lib/packages/interface.php
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/lib/packages/plugins/plugin.php
  redaxo/src/core/lib/setup/import.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/sql/table.php
  redaxo/src/core/lib/sql/util.php
  redaxo/src/core/lib/util/i18n.php
  redaxo/src/core/lib/util/log_file.php
  redaxo/src/core/lib/util/socket/socket_response.php
  redaxo/src/core/lib/util/string.php
Labels: automerge

#3371 Installer: command install:update
  redaxo/src/addons/install/lib/command/update.php
  redaxo/src/addons/install/package.yml
Labels: Console, Feature, Installer, automerge

#3367 Module/Templates löschen: Fehlermeldung bei Verwendung in Artikeln vereinheitlicht
  redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
  redaxo/src/addons/structure/plugins/content/pages/templates.php
Labels: automerge

#3350 Copy to Clipboard Button for markdown sysreport
  redaxo/src/core/assets/clipboard-copy-element.js
  redaxo/src/core/backend.php
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/pages/system.report.markdown.php
Labels: Core, Enhancement, automerge
