Repository redaxo/redaxo, pull requests merged in 2020-01, with the labels that each got.

#3071 fix command user:create
  redaxo/src/core/lib/console/user/create.php
Labels: Bug, Console, Core, automerge

#3078 REX_VARs: Var-Name an Callback übergeben
  redaxo/src/core/lib/var/var.php
  redaxo/src/core/tests/var/var_test.php
Labels: automerge

#3081 ETag in Safari nicht mehr deaktivieren
  redaxo/src/core/lib/response.php
Labels: automerge

#3083 Installer: Nach Addon-Version hochladen, auf Addon-Details landen
  redaxo/src/addons/install/lib/api_package_upload.php
Labels: automerge

#3085 rex_user::isAdmin beschleunigt
  redaxo/src/core/lib/login/user.php
Labels: automerge

#3088 Update ParsedownExtra
  redaxo/src/core/composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/erusev/parsedown-extra/ParsedownExtra.php
  redaxo/src/core/vendor/erusev/parsedown-extra/composer.json
Labels: automerge

#3086 PHP 7.4: Notice vermeiden
  redaxo/src/core/lib/list.php
Labels: automerge

#3084 Leeres Array aus Cache akzeptieren
  redaxo/src/addons/mediapool/lib/media.php
  redaxo/src/addons/mediapool/lib/media_category.php
  redaxo/src/addons/structure/lib/structure_element.php
Labels: Performance, automerge

#3077 Media Manager: 404-Response statt Error-Bild
  redaxo/src/addons/media_manager/lib/managed_media.php
  redaxo/src/addons/media_manager/lib/media_manager.php
  redaxo/src/addons/media_manager/lib/not_found_exception.php
  redaxo/src/addons/media_manager/media/warning.jpg
  redaxo/src/addons/media_manager/tests/managed_media_test.php
  redaxo/src/addons/media_manager/tests/media_manager_test.php
Labels: automerge

#3087 Dokumentations-Sidebar rechts anordnen
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_docs.scss
Labels: automerge

#3089 update rex_autoload::findClasses
  redaxo/src/core/lib/autoload.php
Labels: automerge

#3091 Präfix "rex_htaccess_check" als Indikator für Quelle
  redaxo/src/core/assets/standard.js
Labels: automerge

#3093 GithubAction: activate `@verbose` mode to debug ext-intl issues
  .github/workflows/push.yml
Labels: automerge

#3090 Github: Security Policy
  SECURITY.md
Labels: automerge

#3099 psalm: use 2 threads in GithubAction
  .github/workflows/push.yml
Labels: automerge

#3101 GithubAction: add PAT to csfix action
  .github/workflows/csfix.yml
Labels: automerge

#3098 psalm: activate shepherd.dev mode to collect type coverage
  .github/workflows/push.yml
  README.md
Labels: automerge

#3104 Console: disable package loading for db:set-connection
  redaxo/src/core/lib/console/application.php
Labels: Console, Enhancement, automerge

#3092 rex_navigation Ankerinhalt bearbeitbar machen
  redaxo/src/addons/structure/lib/navigation.php
Labels: Add to Docs, automerge

#3108 Added docs
  redaxo/src/core/lib/console/application.php
Labels: automerge

#3107 Toten Code entfernt
  redaxo/src/addons/structure/assets/linkmap.js
Labels: automerge

#3095 Update auf: jQuery v3.4.1, jQuery UI - v1.12.1, PJAX 2.0.1
  redaxo/bin/update-requirements
  redaxo/src/addons/be_style/plugins/customizer/assets/js/main.js
  redaxo/src/core/assets/jquery-pjax.min.js
  redaxo/src/core/assets/jquery-ui.custom.min.js
  redaxo/src/core/assets/jquery.js
  redaxo/src/core/assets/jquery.min.js
  redaxo/src/core/assets/jquery.min.map
Labels: Core, Performance, Security, automerge

#3103 Console: fix commands
  redaxo/src/core/lib/console/db/set_connection.php
  redaxo/src/core/lib/console/user/create.php
Labels: Bug, Console, Core, automerge

#3080 added command config:set
  redaxo/src/core/lib/console/command_loader.php
  redaxo/src/core/lib/console/config/set.php
Labels: Console, Core, Feature, automerge

#3111 Setup warnung wenn php 7.4 verwendet wird nach EOL
  redaxo/src/core/pages/setup.php
Labels: Developer Experience (DX), Security, automerge

#3112 GithubActions: update actions/checkout to v2
  .github/workflows/csfix.yml
  .github/workflows/push.yml
Labels: automerge

#3113 Fix typo
  redaxo/src/core/CHANGELOG.md
Labels: automerge

#3114 Update README.de.md
  README.de.md
Labels: automerge

#3115 psalm-coverage badge via shields.io with "for-the-badge" style
  README.de.md
  README.md
Labels: automerge

#3116 Use latest GithubActions
  .github/workflows/csfix.yml
Labels: automerge

#3117 Remove fetch-depth
  .github/workflows/csfix.yml
Labels: automerge

#3106 Console: db:set-connection connection check
  redaxo/src/core/lib/console/db/set_connection.php
Labels: Console, Enhancement, automerge

#3119 Auto-cs-fixer: Going back to actions/checkout@v1
  .github/workflows/csfix.yml
Labels: automerge

#3121 Use constant instead of magic value
  redaxo/src/addons/structure/plugins/version/boot.php
Labels: automerge

#3123 rex_config: error beim speichern in db
  redaxo/src/core/lib/config.php
Labels: Bug, Core, automerge

#2764 Wording Datenbankexport angepasst.
  redaxo/src/addons/backup/lang/de_de.lang
  redaxo/src/addons/backup/lang/en_gb.lang
  redaxo/src/addons/backup/lang/es_es.lang
  redaxo/src/addons/backup/lang/it_it.lang
  redaxo/src/addons/backup/lang/pt_br.lang
  redaxo/src/addons/backup/lang/sv_se.lang
  redaxo/src/addons/backup/pages/import.upload.php
Labels: Backup, Enhancement, automerge

#3127 rex_media: consistent has/getValue
  redaxo/src/addons/mediapool/lib/media.php
  redaxo/src/addons/mediapool/tests/media_test.php
Labels: Bug, Mediapool, automerge

#3130 fix tests
  redaxo/src/core/tests/config_test.php
  redaxo/src/core/tests/rex_test.php
Labels: automerge

#2977 Structure context
  redaxo/src/addons/structure/lib/structure_context.php
  redaxo/src/addons/structure/pages/index.php
Labels: automerge

#3133 Prio-Sync nur, wenn Prio sich geändert hat
  redaxo/src/addons/structure/lib/service_article.php
  redaxo/src/addons/structure/lib/service_category.php
Labels: automerge

#3134 Structure context: bugfix
  redaxo/src/addons/structure/pages/index.php
Labels: Bug, Structure, automerge

#3136 Addon nach Download markieren
  redaxo/src/addons/install/lib/api_package_add.php
  redaxo/src/core/pages/packages.php
Labels: Core, Installer, User Experience (UX), automerge

#3135 rex_api_function::hasMessage() immer aufrufbar machen
  redaxo/src/core/lib/api_function.php
Labels: automerge

#3132 Version-Toolbar besser platzieren
  redaxo/src/addons/structure/plugins/version/boot.php
Labels: automerge

#3138 Installer: Bei Aufruf Details nach oben scrollen
  redaxo/src/addons/install/pages/packages.add.php
  redaxo/src/addons/install/pages/packages.update.php
  redaxo/src/addons/install/pages/packages.upload.php
Labels: automerge

#961 Add Templatefilter to "Metainfo" Addon
  redaxo/src/addons/metainfo/install.php
  redaxo/src/addons/metainfo/lang/de_de.lang
  redaxo/src/addons/metainfo/lang/en_gb.lang
  redaxo/src/addons/metainfo/lib/handler/article_handler.php
  redaxo/src/addons/metainfo/lib/restrictions_element.php
  redaxo/src/addons/metainfo/lib/table_expander.php
Labels: Feature, automerge

#3141 Datumsformat vereinheitlicht für Sprachen
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/it_it.lang
  redaxo/src/core/lang/nl_nl.lang
  redaxo/src/core/lang/pt_br.lang
  redaxo/src/core/lang/sv_se.lang
  redaxo/src/core/tests/util/formatter_test.php
Labels: automerge

#3129 fix inconsistent has/getValue
  phpstan.neon.dist
  redaxo/src/addons/structure/plugins/content/lib/article_content.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
  redaxo/src/addons/structure/plugins/content/tests/article_content_base_test.php
  redaxo/src/addons/structure/plugins/content/tests/article_content_test.php
  redaxo/src/addons/structure/tests/article_test.php
  redaxo/src/addons/structure/tests/category_test.php
  redaxo/src/core/tests/clang/clang_test.php
Labels: Bug, Core, Enhancement, Structure, automerge

#3142 adds article-id to article tr
  redaxo/src/addons/structure/pages/index.php
Labels: automerge

#3146 be_search-Reste entfernt
  redaxo/src/addons/mediapool/lang/de_de.lang
  redaxo/src/addons/mediapool/lang/en_gb.lang
  redaxo/src/addons/mediapool/lang/es_es.lang
  redaxo/src/addons/mediapool/lang/it_it.lang
  redaxo/src/addons/mediapool/lang/pt_br.lang
  redaxo/src/addons/mediapool/lang/sv_se.lang
  redaxo/src/addons/structure/lang/de_de.lang
  redaxo/src/addons/structure/lang/en_gb.lang
  redaxo/src/addons/structure/lang/es_es.lang
  redaxo/src/addons/structure/lang/it_it.lang
  redaxo/src/addons/structure/lang/pt_br.lang
  redaxo/src/addons/structure/lang/sv_se.lang
Labels: automerge

#3145 Id -> ID
  redaxo/src/addons/structure/lang/de_de.lang
Labels: automerge

#3144 Installer-Messages verbessert
  redaxo/src/addons/install/lang/de_de.lang
  redaxo/src/addons/install/lang/en_gb.lang
  redaxo/src/addons/install/lang/es_es.lang
  redaxo/src/addons/install/lang/pt_br.lang
  redaxo/src/addons/install/lang/sv_se.lang
  redaxo/src/addons/install/lib/api_core_update.php
  redaxo/src/addons/install/lib/api_package_update.php
Labels: Installer, automerge

#3147 DB-Typ und Typ-spezifische Version abfragbar
  redaxo/src/core/.phpstorm.meta.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/system_report.php
  redaxo/src/core/pages/system.settings.php
  redaxo/src/core/tests/sql/sql_test.php
Labels: Add to Docs, automerge

#3154 travis: php 8 testen; bionic nutzen, wo möglich
  .travis.yml
Labels: automerge

#3143 Zusammenspiel version- und history-Plugin / history-Lösch-Cronjob
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_navs.scss
  redaxo/src/addons/structure/plugins/history/assets/history.js
  redaxo/src/addons/structure/plugins/history/boot.php
  redaxo/src/addons/structure/plugins/history/fragments/history/layer.php
  redaxo/src/addons/structure/plugins/history/lang/de_de.lang
  redaxo/src/addons/structure/plugins/history/lang/en_gb.lang
  redaxo/src/addons/structure/plugins/history/lib/article_slice_history.php
  redaxo/src/addons/structure/plugins/history/lib/cronjob.php
  redaxo/src/addons/structure/plugins/version/boot.php
  redaxo/src/core/fragments/core/toolbar.php
Labels: automerge

#3161 Submodule-Reste entfernt
  .dependabot/config.yml
  .github/workflows/push.yml
Labels: automerge

#3158 rex_log_file: "|" escapen
  redaxo/src/core/lib/util/log_file.php
  redaxo/src/core/tests/util/log_entry_test.php
Labels: automerge

#3157 Fehlendes Escaping ergänzt
  redaxo/src/addons/cronjob/pages/cronjobs.php
  redaxo/src/addons/cronjob/pages/log.php
Labels: automerge

#3163 Setup: DB-Name nach Host/User/Passwort
  redaxo/src/core/pages/setup.php
Labels: automerge

#3160 Default-DB-Name "redaxo5" statt "redaxo_5_0"
  .github/workflows/default.config.yml.github-action.diff
  .github/workflows/push.yml
  .travis.yml
  redaxo/src/core/default.config.yml
Labels: automerge

#3159 Packages-Page: Suchfeld-Fokus nur initial setzen
  redaxo/src/core/pages/packages.php
Labels: automerge

#3153 session autostart imrpovement
  redaxo/src/core/boot.php
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/pages/setup.php
Labels: Bug, Core, automerge

#3170 rex_log_file: Notice vermeiden
  redaxo/src/core/lib/util/log_file.php
  redaxo/src/core/tests/util/log_entry_test.php
Labels: automerge

#3167 dependabot: only security fixes
  .dependabot/config.yml
Labels: Developer Experience (DX), Enhancement, automerge

#3168 update vendors
  redaxo/src/addons/tests/composer.lock
  redaxo/src/addons/tests/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php
  redaxo/src/addons/tests/vendor/myclabs/deep-copy/src/DeepCopy/TypeFilter/Spl/ArrayObjectFilter.php
  redaxo/src/addons/tests/vendor/phpunit/phpunit/ChangeLog-7.5.md
  redaxo/src/addons/tests/vendor/phpunit/phpunit/src/Runner/Version.php
  redaxo/src/addons/tests/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/filp/whoops/CHANGELOG.md
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Exception/Frame.php
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php
Labels: automerge

#3164 fix rex_setup::checkDb
  redaxo/src/core/lib/setup/setup.php
Labels: Bug, Core, automerge

#3162 Mountpoints korrekt sortieren
  redaxo/src/addons/structure/lib/linkmap/renderer.php
  redaxo/src/addons/structure/lib/perm.php
  redaxo/src/addons/structure/lib/select_category.php
Labels: automerge

#3173 rex_timer::measure: Umgang mit Exceptions
  redaxo/src/core/lib/util/timer.php
  redaxo/src/core/tests/util/timer_test.php
Labels: automerge

#3152 Session-Start-Fehler-Handling korrigiert
  redaxo/src/core/lib/error_handler.php
  redaxo/src/core/lib/login/login.php
Labels: automerge

#3155 Multi-Rollen: Doppelte Werte in Complex-Perms vermeiden
  redaxo/src/addons/users/lib/role.php
Labels: automerge

#3175 Added phpdoc
  redaxo/src/core/lib/util/timer.php
Labels: automerge

#3174 Fix rex_timer::measure test
  redaxo/src/core/tests/util/timer_test.php
Labels: automerge

#3109 PHPMailer - Logging
  redaxo/src/addons/phpmailer/install.php
  redaxo/src/addons/phpmailer/lang/de_de.lang
  redaxo/src/addons/phpmailer/lang/en_gb.lang
  redaxo/src/addons/phpmailer/lang/es_es.lang
  redaxo/src/addons/phpmailer/lang/sv_se.lang
  redaxo/src/addons/phpmailer/lib/mailer.php
  redaxo/src/addons/phpmailer/pages/config.php
  redaxo/src/addons/phpmailer/pages/system.log.phpmailer.php
Labels: Add to Docs, Feature, PHPMailer, automerge

#3150 utf8mb4 unterstützen
  redaxo/src/addons/backup/lang/de_de.lang
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/tests/bin/setup.php
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lib/setup/import.php
  redaxo/src/core/lib/sql/table.php
  redaxo/src/core/lib/system_report.php
  redaxo/src/core/pages/setup.php
Labels: automerge

#3178 Template-Select gehört ins content-Plugin
  redaxo/src/addons/metainfo/lib/table_expander.php
  redaxo/src/addons/structure/pages/index.php
  redaxo/src/addons/structure/plugins/content/lib/select_template.php
Labels: Bug, automerge

#1426 Move tag generation to dedicated methods for easy overriding
  redaxo/src/addons/structure/lib/navigation.php
  redaxo/src/addons/structure/tests/navigation_test.php
Labels: Add to Docs, Enhancement, Structure, automerge

#3171 Backup: upload size limit
  redaxo/src/addons/backup/lang/de_de.lang
  redaxo/src/addons/backup/lang/en_gb.lang
  redaxo/src/addons/backup/pages/import.upload.php
Labels: automerge

#3156 Customizer-Layout korrigiert
  redaxo/src/addons/be_style/plugins/customizer/assets/css/styles-labelcolor.css
  redaxo/src/addons/be_style/plugins/customizer/assets/js/main.js
  redaxo/src/addons/be_style/plugins/customizer/boot.php
Labels: automerge

#3184 Perm-Selects: Max-Zeilen von 10 auf 20
  redaxo/src/addons/users/pages/roles.php
Labels: automerge

#3185 PHPMailer: README E-Mail-Log DE
  redaxo/src/addons/phpmailer/README.de.md
  redaxo/src/addons/phpmailer/README.md
Labels: Add to Docs, automerge

#2899 Benutzerrechte - sortieren und Keyword mit angehangen
  redaxo/src/addons/users/boot.php
  redaxo/src/addons/users/lang/de_de.lang
  redaxo/src/addons/users/lang/en_gb.lang
  redaxo/src/addons/users/pages/roles.php
  redaxo/src/core/lib/login/perm.php
Labels: automerge

#3190 Setup: DB-Werte trimmen
  redaxo/src/core/pages/setup.php
Labels: Setup, User Experience (UX), automerge

#3186 tar: deprecated-message vermeiden
  redaxo/src/addons/backup/vendor/tar.php
Labels: automerge

#3188 Ajax-Loader verzögert einblenden
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_loader.scss
Labels: automerge

#3192 Project: README englische Übersetzung
  redaxo/src/addons/project/README.de.md
  redaxo/src/addons/project/README.md
Labels: automerge

#2892 Templates können via Key geladen werden
  redaxo/src/addons/structure/plugins/content/install.php
  redaxo/src/addons/structure/plugins/content/lang/de_de.lang
  redaxo/src/addons/structure/plugins/content/lang/en_gb.lang
  redaxo/src/addons/structure/plugins/content/lib/var_template.php
  redaxo/src/addons/structure/plugins/content/pages/templates.php
Labels: automerge

#3187 Update CodeMirror (5.51) mit neuen Optionen
  redaxo/src/addons/be_style/CHANGELOG.md
  redaxo/src/addons/be_style/plugins/customizer/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/customizer/assets/js/main.js
  redaxo/src/addons/be_style/plugins/customizer/assets/vendor/codemirror.zip
  redaxo/src/addons/be_style/plugins/customizer/boot.php
  redaxo/src/addons/be_style/plugins/customizer/lang/de_de.lang
  redaxo/src/addons/be_style/plugins/customizer/lang/en_gb.lang
  redaxo/src/addons/be_style/plugins/customizer/lang/es_es.lang
  redaxo/src/addons/be_style/plugins/customizer/lang/it_it.lang
  redaxo/src/addons/be_style/plugins/customizer/lang/pt_br.lang
  redaxo/src/addons/be_style/plugins/customizer/lang/sv_se.lang
  redaxo/src/addons/be_style/plugins/customizer/pages/system.customizer.php
Labels: automerge

#3182 Strukturrechte add/edit/delete
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_buttons.scss
  redaxo/src/addons/be_style/plugins/redaxo/scss/_tables.scss
  redaxo/src/addons/structure/boot.php
  redaxo/src/addons/structure/lang/de_de.lang
  redaxo/src/addons/structure/lang/en_gb.lang
  redaxo/src/addons/structure/lib/api_functions/api_article_add.php
  redaxo/src/addons/structure/lib/api_functions/api_article_delete.php
  redaxo/src/addons/structure/lib/api_functions/api_article_edit.php
  redaxo/src/addons/structure/lib/api_functions/api_category_add.php
  redaxo/src/addons/structure/lib/api_functions/api_category_delete.php
  redaxo/src/addons/structure/lib/api_functions/api_category_edit.php
  redaxo/src/addons/structure/pages/index.php
  redaxo/src/addons/structure/update.php
Labels: automerge

#3195 addSlice in rex_content_service verschoben
  redaxo/src/addons/structure/plugins/content/lib/content_service.php
  redaxo/src/addons/structure/plugins/content/lib/service_slice.php
Labels: automerge

#3193 github-action: add cs2pr
  .github/workflows/push.yml
Labels: automerge

#3191 Neuer EP ART_CONTENT_UPDATED
  redaxo/src/addons/structure/plugins/content/lib/content_service.php
  redaxo/src/addons/structure/plugins/content/lib/extension_point/art_content_updated.php
  redaxo/src/addons/structure/plugins/content/pages/content.php
  redaxo/src/addons/structure/plugins/version/boot.php
Labels: automerge

#3196 packages: plugin requires base addon
  redaxo/src/core/lib/packages/manager.php
Labels: Bug, Core, Enhancement, automerge

#3197 mediapool: detect mimetype
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
Labels: Bug, Enhancement, Mediapool, automerge

#3202 Medienpool: php 7.4 notice bei upload vermeiden
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
Labels: automerge

#3204 Credits-Page überarbeitet
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/it_it.lang
  redaxo/src/core/lang/nl_nl.lang
  redaxo/src/core/lang/pt_br.lang
  redaxo/src/core/lang/sv_se.lang
  redaxo/src/core/pages/credits.php
Labels: automerge

#3203 Packages-Page: Bei Hilfe/Lizenz nach oben springen
  redaxo/src/core/pages/packages.php
Labels: automerge

#3205 use stable staabm/annotate-pull-request-from-checkstyle:^1.0 release
  .github/workflows/push.yml
Labels: automerge

#3209 Added phpunit problem matcher
  .github/workflows/push.yml
  redaxo/src/core/tests/util/timer_test.php
Labels: automerge

#3212 tests: restore global state after rex:: test
  redaxo/src/core/tests/rex_test.php
Labels: automerge

#3213 tests: make sure tests dont depend on each other
  redaxo/src/core/tests/rex_test.php
Labels: automerge

#3206 Delete Button for Cronjob Log
  redaxo/src/addons/cronjob/lang/de_de.lang
  redaxo/src/addons/cronjob/lang/en_gb.lang
  redaxo/src/addons/cronjob/pages/log.php
Labels: Cronjob, automerge

#3214 Kodiak: move config into .github/
  .github/.kodiak.toml
Labels: automerge

#3215 Setup: Bei existierender DB korrekt utf8mb4-Status auslesen
  redaxo/src/core/pages/setup.php
Labels: Bug, automerge

#3216 Struktur: Sprache konnte nicht gewechselt werden
  redaxo/src/addons/structure/lib/structure_context.php
Labels: Bug, automerge

#3210 PHPMailer log Übersetzungen aus syslog übernommen
  redaxo/src/addons/phpmailer/lang/de_de.lang
  redaxo/src/addons/phpmailer/lang/en_gb.lang
  redaxo/src/addons/phpmailer/lang/es_es.lang
  redaxo/src/addons/phpmailer/lang/sv_se.lang
  redaxo/src/addons/phpmailer/pages/system.log.phpmailer.php
Labels: PHPMailer, automerge

#3217 Zentraler Log-Ordner redaxo/data/log
  redaxo/src/addons/cronjob/lib/manager.php
  redaxo/src/addons/cronjob/pages/log.php
  redaxo/src/addons/cronjob/update.php
  redaxo/src/addons/phpmailer/README.de.md
  redaxo/src/addons/phpmailer/README.md
  redaxo/src/addons/phpmailer/boot.php
  redaxo/src/addons/phpmailer/lib/mailer.php
  redaxo/src/core/lib/util/logger.php
  redaxo/src/core/lib/util/path.php
  redaxo/src/core/lib/util/path_default_provider.php
  redaxo/src/core/update.php
Labels: Add to Docs, automerge

#3219 toggle Status der Sidebar Panels in localstorage speichern
  redaxo/src/addons/structure/plugins/content/assets/content.js
  redaxo/src/addons/structure/plugins/content/boot.php
Labels: Feature, Structure, User Experience (UX), automerge

#2629 Phpstan: level++
  phpstan.neon.dist
  redaxo/src/addons/mediapool/pages/media.detail.php
  redaxo/src/addons/mediapool/pages/media.list.php
  redaxo/src/addons/mediapool/pages/structure.php
  redaxo/src/addons/mediapool/pages/upload.php
  redaxo/src/addons/structure/plugins/content/pages/content.edit.php
  redaxo/src/addons/structure/plugins/content/pages/templates.php
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/pages/setup.php
Labels: Contributor Experience, automerge

#3118 added command setup:run
  redaxo/src/core/lib/console/application.php
  redaxo/src/core/lib/console/command_loader.php
  redaxo/src/core/lib/console/command_only_setup_packages.php
  redaxo/src/core/lib/console/command_standalone.php
  redaxo/src/core/lib/console/db/set_connection.php
  redaxo/src/core/lib/console/setup/run.php
Labels: Add to Docs, Console, Core, Feature, Setup, automerge

#3221 vendor updates
  redaxo/src/addons/tests/composer.lock
  redaxo/src/addons/tests/vendor/phpspec/prophecy/CHANGES.md
  redaxo/src/addons/tests/vendor/phpspec/prophecy/composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/symfony/console/Application.php
  redaxo/src/core/vendor/symfony/console/Helper/FormatterHelper.php
  redaxo/src/core/vendor/symfony/console/LICENSE
  redaxo/src/core/vendor/symfony/console/README.md
  redaxo/src/core/vendor/symfony/var-dumper/Dumper/ContextProvider/CliContextProvider.php
  redaxo/src/core/vendor/symfony/var-dumper/LICENSE
  redaxo/src/core/vendor/symfony/yaml/Inline.php
  redaxo/src/core/vendor/symfony/yaml/LICENSE
  redaxo/src/core/vendor/symfony/yaml/README.md
Labels: automerge

#3222 MP: Cache nicht löschen in install.php
  redaxo/src/addons/mediapool/install.php
  redaxo/src/addons/mediapool/uninstall.php
Labels: automerge

#3223 Core-Update: install.php einbinden
  redaxo/src/core/install.php
  redaxo/src/core/update.php
Labels: automerge

#3177 Release 5.9.0-beta1
  redaxo/src/addons/backup/CHANGELOG.md
  redaxo/src/addons/backup/package.yml
  redaxo/src/addons/be_style/CHANGELOG.md
  redaxo/src/addons/be_style/package.yml
  redaxo/src/addons/cronjob/CHANGELOG.md
  redaxo/src/addons/cronjob/package.yml
  redaxo/src/addons/install/CHANGELOG.md
  redaxo/src/addons/install/package.yml
  redaxo/src/addons/media_manager/CHANGELOG.md
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/addons/mediapool/CHANGELOG.md
  redaxo/src/addons/mediapool/package.yml
  redaxo/src/addons/metainfo/CHANGELOG.md
  redaxo/src/addons/metainfo/package.yml
  redaxo/src/addons/phpmailer/CHANGELOG.md
  redaxo/src/addons/phpmailer/package.yml
  redaxo/src/addons/structure/CHANGELOG.md
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/plugins/content/package.yml
  redaxo/src/addons/structure/plugins/history/package.yml
  redaxo/src/addons/users/CHANGELOG.md
  redaxo/src/addons/users/package.yml
  redaxo/src/core/CHANGELOG.md
  redaxo/src/core/boot.php
Labels: automerge

#3226 Fix typo
  redaxo/src/addons/structure/pages/index.php
Labels: Bug, automerge

#3228 fix flickering tests
  redaxo/src/addons/tests/bin/setup.php
Labels: automerge

#3237 fix travis
  .travis.yml
Labels: automerge

#3232 Systemlog: 100 statt 30 Zeilen, Download-Button
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/pages/system.log.redaxo.php
Labels: automerge

#3239 Phpmailer: log : Zeile entfernt
  redaxo/src/addons/phpmailer/pages/system.log.phpmailer.php
Labels: automerge

#3238 be_style: update.php für customizer reinstall
  redaxo/src/addons/be_style/update.php
Labels: automerge

#3236 Setup: Vor Reinstallation der Addons, diese listen
  redaxo/src/core/lib/setup/import.php
Labels: automerge

#3240 rex_sql_table: Fix für PK zu existierender Tabelle hinzufügen
  redaxo/src/core/lib/sql/table.php
  redaxo/src/core/tests/sql/sql_table_test.php
Labels: Bug, Core, automerge

#3244 Markdown-Styles: Listenpunkte für verschachtelte Listen
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_docs.scss
Labels: automerge

#3242 Helfer-Methode rex_sql::escapeLikeWildcards()
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/tests/sql/sql_test.php
Labels: automerge

#3243 Vor Backups mit anderen Core/Addon-Versionen warnen
  redaxo/src/addons/backup/lang/de_de.lang
  redaxo/src/addons/backup/pages/import.server.php
  redaxo/src/addons/backup/pages/import.upload.php
  redaxo/src/core/pages/setup.php
Labels: automerge

#3241 rex_sql: Where-Param-Handling korrigiert
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/tests/sql/sql_test.php
Labels: automerge

#3246 customizer-Aktualisierung korrigiert
  redaxo/src/addons/be_style/plugins/customizer/install.php
Labels: automerge
