Repository redaxo/redaxo, pull requests merged in 2020-07, with the labels that each got.

#3785 Passwortregeln: "min 0" ignorieren
  redaxo/src/core/lib/login/password_policy.php
  redaxo/src/core/tests/login/password_policy_test.php
Labels: automerge

#3794 assets:sync: use shorter description and moved extensive description …
  redaxo/src/core/lib/console/assets_sync.php
Labels: automerge

#3792 assets:sync: compare file hash additional to the filemtime
  redaxo/src/core/lib/console/assets_sync.php
Labels: automerge

#3796 Prepare next version
  .github/tests-visual/system_report.png
  redaxo/src/core/boot.php
Labels: automerge

#3800 Visual Regression Testing: ignore sys-report values
  .github/tests-visual/system_report.png
  .github/tests-visual/visual-record.js
Labels: Contributor Experience, automerge

#3799 sys-report: throw a meaningfull error instead of a type-error because…
  redaxo/src/core/pages/system.report.html.php
Labels: Core, Developer Experience (DX), Enhancement, automerge

#3801 Systembericht als Markdown ohne trailing whitespace
  redaxo/src/core/boot.php
  redaxo/src/core/pages/system.report.markdown.php
Labels: Bug, Core, automerge

#3793 added `config:get/set --type=octal` support
  redaxo/src/core/lib/console/config/get.php
  redaxo/src/core/lib/console/config/set.php
Labels: automerge

#3797 protocol into syslog on core/package updates
  .github/tests-visual/packages.png
  redaxo/src/addons/install/lib/api/api_core_update.php
  redaxo/src/addons/install/lib/package/package_update.php
  redaxo/src/addons/install/package.yml
Labels: Feature, Installer, automerge

#3807 Datenbank: Mindestens MySQL 5.6 / MariaDB 10.1
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/nl_nl.lang
  redaxo/src/core/lang/sv_se.lang
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/update.php
Labels: automerge

#3826 fix psalm (downgrade nikic/php-parser)
  .tools/constants.php
  composer.json
Labels: automerge

#3827 Vendor updates
  .tools/bin/update-requirements
  composer.json
  redaxo/src/addons/debug/composer.lock
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Clockwork.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Storage/FileStorage.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Support/Vanilla/Clockwork.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Support/Vanilla/config.php
  redaxo/src/addons/phpmailer/composer.lock
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/VERSION
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/language/phpmailer.lang-sv.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/PHPMailer.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/POP3.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/SMTP.php
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/autoload_classmap.php
  redaxo/src/core/vendor/composer/autoload_static.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/symfony/console/Command/Command.php
  redaxo/src/core/vendor/symfony/console/Helper/QuestionHelper.php
  redaxo/src/core/vendor/symfony/console/Terminal.php
  redaxo/src/core/vendor/symfony/polyfill-ctype/composer.json
  redaxo/src/core/vendor/symfony/polyfill-intl-grapheme/composer.json
  redaxo/src/core/vendor/symfony/polyfill-intl-normalizer/composer.json
  redaxo/src/core/vendor/symfony/polyfill-mbstring/composer.json
  redaxo/src/core/vendor/symfony/polyfill-php72/composer.json
  redaxo/src/core/vendor/symfony/polyfill-php73/composer.json
  redaxo/src/core/vendor/symfony/polyfill-php80/composer.json
  redaxo/src/core/vendor/symfony/service-contracts/LICENSE
  redaxo/src/core/vendor/symfony/service-contracts/ServiceLocatorTrait.php
  redaxo/src/core/vendor/symfony/service-contracts/ServiceSubscriberTrait.php
  redaxo/src/core/vendor/symfony/service-contracts/composer.json
  redaxo/src/core/vendor/symfony/var-dumper/Caster/ReflectionCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/ResourceCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Cloner/AbstractCloner.php
  redaxo/src/core/vendor/symfony/var-dumper/Dumper/CliDumper.php
  redaxo/src/core/vendor/voku/portable-ascii/build/composer.json
  redaxo/src/core/vendor/voku/portable-ascii/build/generate_docs.php
  redaxo/src/core/vendor/voku/portable-ascii/build/gernerate_max_key_length.php
  redaxo/src/core/vendor/voku/portable-ascii/src/voku/helper/ASCII.php
  redaxo/src/core/vendor/voku/portable-ascii/src/voku/helper/data/ascii_by_languages.php
  redaxo/src/core/vendor/voku/portable-utf8/src/voku/helper/Bootup.php
  redaxo/src/core/vendor/voku/portable-utf8/src/voku/helper/UTF8.php
Labels: automerge

#3831 rex_sql: lastInsertId zwischenspeichern
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/tests/sql/sql_test.php
Labels: automerge
