Repository redaxo/redaxo, pull requests merged in 2020-08, with the labels that each got.

#3824 Parameternamen vereinheitlicht
  redaxo/src/addons/mediapool/lib/form_element/media.php
  redaxo/src/addons/mediapool/lib/form_element/medialist.php
  redaxo/src/addons/metainfo/lib/restrictions_element.php
  redaxo/src/addons/structure/lib/linkmap/form_element/linklist.php
  redaxo/src/addons/structure/lib/linkmap/form_element/linkmap.php
  redaxo/src/core/functions/function_rex_other.php
  redaxo/src/core/lib/be/page.php
  redaxo/src/core/lib/clang/clang.php
  redaxo/src/core/lib/clang/perm.php
  redaxo/src/core/lib/console/setup/run.php
  redaxo/src/core/lib/form/elements/checkbox.php
  redaxo/src/core/lib/form/elements/container.php
  redaxo/src/core/lib/form/elements/control.php
  redaxo/src/core/lib/form/elements/element.php
  redaxo/src/core/lib/form/elements/options.php
  redaxo/src/core/lib/form/elements/prio.php
  redaxo/src/core/lib/form/elements/radio.php
  redaxo/src/core/lib/form/elements/raw.php
  redaxo/src/core/lib/form/elements/select.php
  redaxo/src/core/lib/list.php
  redaxo/src/core/lib/login/login.php
  redaxo/src/core/lib/packages/package.php
  redaxo/src/core/lib/select.php
  redaxo/src/core/lib/setup/import.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/sql/util.php
  redaxo/src/core/lib/util/i18n.php
  redaxo/src/core/lib/var/var.php
Labels: automerge

#3842 rex_dir::delete(): ignore warning
  redaxo/src/core/lib/util/dir.php
Labels: automerge

#3841 Einfache Möglichkeit, aus Template/Module auf Fehlerseite zu leiten
  redaxo/src/addons/structure/plugins/content/boot.php
  redaxo/src/addons/structure/plugins/content/lib/article_not_found_exception.php
Labels: Add to Docs, Feature, Structure, automerge

#3843 Benutzer erstellen: Fehler bei neuen Passwortregeln
  redaxo/src/addons/users/pages/users.php
Labels: Bug, automerge

#3851 added phpdoc
  redaxo/src/addons/debug/lib/debug.php
Labels: automerge
