Repository redaxo/redaxo, pull requests merged in 2020-10, with the labels that each got.

#3900 Visual tests: Package-Versionen entfernen
  .github/tests-visual/packages.png
  .github/tests-visual/visual-record.js
Labels: automerge

#3891 Vendor updates
  composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/symfony/console/Application.php
  redaxo/src/core/vendor/symfony/console/Command/Command.php
  redaxo/src/core/vendor/symfony/console/Descriptor/JsonDescriptor.php
  redaxo/src/core/vendor/symfony/console/Descriptor/TextDescriptor.php
  redaxo/src/core/vendor/symfony/console/Formatter/OutputFormatter.php
  redaxo/src/core/vendor/symfony/console/Helper/ProcessHelper.php
  redaxo/src/core/vendor/symfony/console/Helper/ProgressBar.php
  redaxo/src/core/vendor/symfony/console/Helper/QuestionHelper.php
  redaxo/src/core/vendor/symfony/console/Helper/TableStyle.php
  redaxo/src/core/vendor/symfony/console/Input/ArgvInput.php
  redaxo/src/core/vendor/symfony/console/Input/InputDefinition.php
  redaxo/src/core/vendor/symfony/console/Output/BufferedOutput.php
  redaxo/src/core/vendor/symfony/console/Output/ConsoleOutput.php
  redaxo/src/core/vendor/symfony/console/Output/ConsoleSectionOutput.php
  redaxo/src/core/vendor/symfony/console/Output/StreamOutput.php
  redaxo/src/core/vendor/symfony/console/Question/Question.php
  redaxo/src/core/vendor/symfony/console/Style/OutputStyle.php
  redaxo/src/core/vendor/symfony/console/Style/SymfonyStyle.php
  redaxo/src/core/vendor/symfony/console/Tester/TesterTrait.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/AmqpCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/DOMCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/ExceptionCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/PgSqlCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/ReflectionCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/SplCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/XmlResourceCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Cloner/AbstractCloner.php
  redaxo/src/core/vendor/symfony/var-dumper/Cloner/Data.php
  redaxo/src/core/vendor/symfony/var-dumper/Dumper/AbstractDumper.php
  redaxo/src/core/vendor/symfony/var-dumper/Dumper/CliDumper.php
  redaxo/src/core/vendor/symfony/var-dumper/Dumper/ContextProvider/SourceContextProvider.php
  redaxo/src/core/vendor/symfony/var-dumper/Dumper/HtmlDumper.php
  redaxo/src/core/vendor/symfony/var-dumper/Server/Connection.php
  redaxo/src/core/vendor/symfony/yaml/Command/LintCommand.php
  redaxo/src/core/vendor/symfony/yaml/Exception/ParseException.php
  redaxo/src/core/vendor/symfony/yaml/Inline.php
  redaxo/src/core/vendor/symfony/yaml/Parser.php
Labels: automerge

#3885 markdown: setBreaksEnabled( ) einstellbar machen
  .editorconfig
  redaxo/src/core/lib/be/controller.php
  redaxo/src/core/lib/util/markdown.php
  redaxo/src/core/pages/packages.php
Labels: automerge

#3904 Log: Darstellung Info-Meldungen korrigiert
  redaxo/src/core/lib/util/logger.php
  redaxo/src/core/pages/system.log.redaxo.php
Labels: automerge

#3905 rex_article_slice: Int-Properties mit echten Ints
  redaxo/src/addons/structure/plugins/content/lib/article_slice.php
Labels: Bug, Structure, automerge

#3892 rex_article_slice: Korrektes Handling für $ignoreOfflines in getNextSlice/getPreviousSlice
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/plugins/content/lib/article_slice.php
  redaxo/src/addons/structure/plugins/content/package.yml
  redaxo/src/addons/structure/plugins/content/tests/article_slice_test.php
Labels: automerge

#3907 Actions: Umgang mit Forks
  .github/workflows/cs-fix.yml
  .github/workflows/visual-tests.yml
Labels: automerge

#3901 Hauptmenü: System und Installer tauschen
  .github/tests-visual/backup_export.png
  .github/tests-visual/backup_import.png
  .github/tests-visual/cronjob_cronjobs.png
  .github/tests-visual/index.png
  .github/tests-visual/media_manager_settings.png
  .github/tests-visual/media_manager_types.png
  .github/tests-visual/media_manager_types_edit.png
  .github/tests-visual/metainfo_articles.png
  .github/tests-visual/metainfo_categories.png
  .github/tests-visual/metainfo_clangs.png
  .github/tests-visual/metainfo_media.png
  .github/tests-visual/modules_actions.png
  .github/tests-visual/modules_modules.png
  .github/tests-visual/packages.png
  .github/tests-visual/phpmailer_config.png
  .github/tests-visual/system_log.png
  .github/tests-visual/system_report.png
  .github/tests-visual/system_settings.png
  .github/tests-visual/templates.png
  .github/tests-visual/templates_edit.png
  .github/tests-visual/users_roles.png
  .github/tests-visual/users_users.png
  redaxo/src/addons/install/package.yml
  redaxo/src/core/lib/be/controller.php
Labels: automerge

#3909 debug: compress files in storage
  redaxo/src/addons/debug/lib/debug_clockwork.php
Labels: Bug, Debug, Developer Experience (DX), automerge

#3917 DX: Hinweis ergänzt wenn keine datenbank connection aufgebaut werden kann
  redaxo/src/core/lib/sql/sql.php
Labels: Developer Experience (DX), automerge

#3923 skip `rex_formatter` tests which require 64bit php on 32bit php
  redaxo/src/core/tests/util/formatter_test.php
Labels: automerge

#3919 tests: normalize newlines to make tests work consistently on windows
  redaxo/src/core/tests/console/config/get_test.php
Labels: Contributor Experience, automerge

#3924 tests: normalize newlines to make tests work consistently on windows
  redaxo/src/core/tests/console/config/get_test.php
Labels: automerge

#3921 added psr3 LogLevel for rex_logger::log()
  redaxo/src/core/lib/util/logger.php
Labels: automerge

#3910 DX: added `nunomaduro/collision` as a dev-dependency
  .idea/php.xml
  .idea/redaxo.iml
  composer.json
  phpunit.xml.dist
Labels: Contributor Experience, automerge

#3915 fix php test warning: "session_destroy(): Trying to destroy uninitial…
  redaxo/src/core/tests/login/backend_login_test.php
Labels: Enhancement, automerge

#3903 `rex_sql::getQueryType`: Geklammerte SELECTs unterstützen
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/tests/sql/sql_test.php
Labels: automerge

#3927 fix clone-addon cmd
  .tools/bin/clone-addon
Labels: automerge

#3928 Composer scripts
  .tools/bin/update-all
  composer.json
Labels: automerge

#3929 Passwort-Regel unter Passwortfeld anzeigen
  redaxo/src/addons/users/package.yml
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/lib/console/setup/run.php
  redaxo/src/core/lib/console/user/create.php
  redaxo/src/core/lib/console/user/set_password.php
  redaxo/src/core/lib/login/password_policy.php
  redaxo/src/core/pages/profile.php
  redaxo/src/core/pages/setup.step6.php
Labels: automerge

#3930 Media Manager: Parameternamen vereinheitlicht
  redaxo/src/addons/media_manager/lib/effect_abstract.php
  redaxo/src/addons/media_manager/lib/effects/effect_mirror.php
  redaxo/src/addons/media_manager/lib/effects/effect_resize.php
  redaxo/src/addons/media_manager/lib/managed_media.php
  redaxo/src/addons/media_manager/lib/media_manager.php
Labels: automerge

#3925 added `rex_validation_rule`, `rex_validator->getRules()`
  redaxo/src/core/lib/util/validation_rule.php
  redaxo/src/core/lib/util/validator.php
  redaxo/src/core/tests/util/validator_test.php
Labels: automerge

#3902 rex_var::toArray Dekodierung an rex_escape anpassen
  redaxo/src/core/lib/var/var.php
  redaxo/src/core/tests/var/var_test.php
Labels: automerge

#3838 rex_user: add forLogin method
  redaxo/src/core/lib/login/user.php
Labels: Add to Docs, automerge

#3937 CronJob: Absoluten Pfad zum Cron ausgeben
  redaxo/src/addons/cronjob/lang/de_de.lang
  redaxo/src/addons/cronjob/lang/en_gb.lang
  redaxo/src/addons/cronjob/lang/es_es.lang
  redaxo/src/addons/cronjob/lang/sv_se.lang
  redaxo/src/addons/cronjob/pages/cronjobs.php
Labels: automerge

#3887 New login page
  .github/tests-visual/login.png
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/peter-olexa-RYtiT3b7XW4-unsplash_2100.jpg
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/peter-olexa-RYtiT3b7XW4-unsplash_2100.webp
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/peter-olexa-RYtiT3b7XW4-unsplash_3300.jpg
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/peter-olexa-RYtiT3b7XW4-unsplash_3300.webp
  redaxo/src/addons/be_style/plugins/redaxo/scss/_login.scss
  redaxo/src/core/fragments/core/login_background.php
  redaxo/src/core/fragments/core/login_branding.php
  redaxo/src/core/layout/bottom.php
  redaxo/src/core/pages/login.php
Labels: Add to Docs, automerge

#3939 Farbausgabe bei Nutzung der Scripts über Composer
  .github/workflows/cs-check.yml
  .github/workflows/cs-fix.yml
  .github/workflows/rexlint.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  .github/workflows/visual-tests.yml
  .tools/bin/refresh
  .tools/bin/update-all
Labels: automerge

#3940 phpstorm config aktualisiert
  .idea/php.xml
  .idea/redaxo.iml
Labels: automerge

#3941 Visual tests: composer deps nicht notwendig
  .github/workflows/visual-tests.yml
Labels: automerge

#3936 make pagination in structure configurable through config.yml
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/pages/index.php
Labels: automerge

#3933 fix rex_article_slice tests on 32bit systems
  redaxo/src/addons/structure/plugins/content/tests/article_slice_test.php
Labels: automerge

#3952 factored out packages subpages into separate files
  .github/tests-visual/login.png
  redaxo/src/core/pages/packages.help.php
  redaxo/src/core/pages/packages.license.php
  redaxo/src/core/pages/packages.list.php
  redaxo/src/core/pages/packages.php
Labels: Enhancement, Installer, automerge

#3956 Login page: slight CSS fix
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_login.scss
Labels: automerge

#3955 Validate mysql host in setup process
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#3958 Medienpool: med_description `strip_tags` auf Beschreibungen anwenden
  redaxo/src/addons/mediapool/pages/media.list.php
Labels: Mediapool, automerge

#3957 Install: version anzeigen, wenn ein addon benötigt wird
  redaxo/src/core/lib/packages/manager.php
Labels: automerge

#3947 PHPMailer: Delete E-Mail-Archive
  redaxo/src/addons/phpmailer/lang/de_de.lang
  redaxo/src/addons/phpmailer/lang/en_gb.lang
  redaxo/src/addons/phpmailer/pages/config.php
Labels: PHPMailer, automerge

#3964 rex_form: set "required"-attribute if field isn't allowed to be empty
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_form.scss
  redaxo/src/core/lib/form/elements/element.php
Labels: automerge

#3975 update psalm and psalm/plugin-symfony
  composer.json
  redaxo/src/core/lib/util/socket/socket_response.php
Labels: automerge

#3948 Feature: article_status cronjob kann die Metafelder art_online_from und art_online_to zurücksetzen
  redaxo/src/addons/cronjob/plugins/article_status/lang/de_de.lang
  redaxo/src/addons/cronjob/plugins/article_status/lang/en_gb.lang
  redaxo/src/addons/cronjob/plugins/article_status/lang/es_es.lang
  redaxo/src/addons/cronjob/plugins/article_status/lang/it_it.lang
  redaxo/src/addons/cronjob/plugins/article_status/lang/pt_br.lang
  redaxo/src/addons/cronjob/plugins/article_status/lang/sv_se.lang
  redaxo/src/addons/cronjob/plugins/article_status/lib/cronjob.php
Labels: automerge

#3883 psalm: fix RedundantCondition
  psalm.xml
  redaxo/src/addons/be_style/plugins/customizer/pages/system.customizer.php
  redaxo/src/addons/mediapool/lib/var_medialist.php
  redaxo/src/addons/mediapool/pages/media.list.php
  redaxo/src/addons/structure/functions/function_rex_category.php
  redaxo/src/addons/structure/lib/linkmap/renderer.php
  redaxo/src/addons/structure/lib/linkmap/var_linklist.php
  redaxo/src/addons/structure/lib/structure_element.php
  redaxo/src/core/lib/config.php
  redaxo/src/core/lib/setup/import.php
Labels: automerge

#3978 Use ramsey/composer-install@v1 to simplify GithubAction workflow
  .github/workflows/cs-check.yml
  .github/workflows/cs-fix.yml
  .github/workflows/rexlint.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
Labels: automerge

#3981 Travis: remove mysql5 jobs
  .travis.yml
Labels: automerge

#3982 GithubAction: test multiple php versions
  .github/workflows/tests.yml
Labels: automerge

#3980 GithubAction: Added MariaDB tests
  .github/workflows/mariadb-tests.yml
  .github/workflows/mysql-tests.yml
  .travis.yml
Labels: automerge

#3970 start instantly with yform template example
  redaxo/src/addons/project/boot.php
Labels: automerge

#3791 kodiak: Coauthors are added using the Co-authored-by trailer syntax.
  .github/.kodiak.toml
Labels: automerge

#3983 GithubAction: added mariadb 10.1 test
  .github/workflows/mariadb-tests.yml
  .travis.yml
Labels: automerge

#3984 GithubAction: added mysql8 job
  .github/workflows/mysql-tests.yml
  .travis.yml
Labels: automerge

#3985 GithubAction: merge mysql & mariadb workflow
  .github/workflows/mariadb-tests.yml
  .github/workflows/tests.yml
Labels: automerge

#3966 add sort function to installer search
  redaxo/src/addons/install/pages/packages.add.php
Labels: Developer Experience (DX), Enhancement, Installer, automerge

#3986 PHPStorm-Settings: psalm/phpstan aktiviert
  .idea/inspectionProfiles/Project_Default.xml
  .idea/php.xml
  .idea/redaxo.iml
Labels: automerge

#3989 psalm 4.0 verwenden
  .tools/psalm/RexTypeReturnProvider.php
  composer.json
  psalm.xml
  redaxo/src/core/lib/list.php
Labels: automerge

#3990 Update vendors
  .tools/bin/update-all
  composer.json
  redaxo/src/addons/phpmailer/composer.lock
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/VERSION
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/composer.json
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/get_oauth_token.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/language/phpmailer.lang-de.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/language/phpmailer.lang-id.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/language/phpmailer.lang-tl.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/Exception.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/OAuth.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/PHPMailer.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/POP3.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/SMTP.php
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/autoload_classmap.php
  redaxo/src/core/vendor/composer/autoload_static.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/filp/whoops/composer.json
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Exception/Formatter.php
  redaxo/src/core/vendor/symfony/console/composer.json
  redaxo/src/core/vendor/symfony/polyfill-ctype/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-ctype/composer.json
  redaxo/src/core/vendor/symfony/polyfill-intl-grapheme/Grapheme.php
  redaxo/src/core/vendor/symfony/polyfill-intl-grapheme/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-intl-grapheme/composer.json
  redaxo/src/core/vendor/symfony/polyfill-intl-normalizer/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-intl-normalizer/composer.json
  redaxo/src/core/vendor/symfony/polyfill-mbstring/Mbstring.php
  redaxo/src/core/vendor/symfony/polyfill-mbstring/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-mbstring/composer.json
  redaxo/src/core/vendor/symfony/polyfill-php72/Php72.php
  redaxo/src/core/vendor/symfony/polyfill-php72/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-php72/composer.json
  redaxo/src/core/vendor/symfony/polyfill-php73/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-php73/composer.json
  redaxo/src/core/vendor/symfony/polyfill-php80/Resources/stubs/Attribute.php
  redaxo/src/core/vendor/symfony/polyfill-php80/Resources/stubs/Stringable.php
  redaxo/src/core/vendor/symfony/polyfill-php80/bootstrap.php
  redaxo/src/core/vendor/symfony/polyfill-php80/composer.json
  redaxo/src/core/vendor/symfony/var-dumper/Cloner/VarCloner.php
  redaxo/src/core/vendor/symfony/var-dumper/composer.json
  redaxo/src/core/vendor/symfony/yaml/composer.json
Labels: automerge

#3993 fixed rex_ini_get() phpdoc
  redaxo/src/core/functions/function_rex_other.php
Labels: automerge

#3995 More descriptive phpdoc
  redaxo/src/core/functions/function_rex_escape.php
Labels: automerge

#3997 increase phpstan level to 5 and generated a baseline
  .tools/phpstan/baseline.neon
  composer.json
  phpstan.neon.dist
Labels: automerge

#3996 phpdocs übertragen
  redaxo/src/core/functions/function_rex_globals.php
  redaxo/src/core/lib/request.php
  redaxo/src/core/lib/util/type.php
Labels: automerge

#3998 Added phpdoc
  redaxo/src/core/lib/util/sortable_iterator.php
Labels: automerge
