Repository redaxo/redaxo, pull requests merged in 2021-10, with the labels that each got.

#4782 Dark Mode: use dedicated color values to support IDE
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_variables-dark.scss
Labels: automerge

#4777 UI: new wallpaper + styles for login page
  .github/tests-visual/login--dark.png
  .github/tests-visual/login.png
  .github/tests-visual/logout--dark.png
  .github/tests-visual/logout.png
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/jr-korpa-9XngoIpxcEo-unsplash_2100.avif
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/jr-korpa-9XngoIpxcEo-unsplash_2100.jpg
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/jr-korpa-9XngoIpxcEo-unsplash_3300.avif
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/jr-korpa-9XngoIpxcEo-unsplash_3300.jpg
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/peter-olexa-RYtiT3b7XW4-unsplash_2100.jpg
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/peter-olexa-RYtiT3b7XW4-unsplash_2100.webp
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/peter-olexa-RYtiT3b7XW4-unsplash_3300.jpg
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/peter-olexa-RYtiT3b7XW4-unsplash_3300.webp
  redaxo/src/core/fragments/core/login_background.php
Labels: automerge

#4781 Dark Mode: add syntax highlighting
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_code.scss
  redaxo/src/addons/be_style/plugins/redaxo/scss/master.scss
Labels: automerge

#4780 UI: remove opacity for offline items in structure view
  .github/tests-visual/index--dark.png
  .github/tests-visual/index.png
  .github/tests-visual/structure_category_edit--dark.png
  .github/tests-visual/structure_category_edit.png
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_typo.scss
Labels: automerge

#4751 Structure: Adding live search to category selects
  redaxo/src/addons/structure/plugins/content/pages/content.functions.php
Labels: automerge

#4860 Fehler beim Erstellen eines neuen Medientypen behoben
  .github/tests-visual/media_manager_types_add--dark.png
  .github/tests-visual/media_manager_types_add.png
  redaxo/src/addons/media_manager/pages/types.php
Labels: automerge

#4862 Fix für Screenshot von MM-Effekten
  .github/imports/inital-content-for-visual-tests.sql
  .github/tests-visual/backup_import_server--dark.png
  .github/tests-visual/backup_import_server.png
  .github/tests-visual/media_manager_types--dark.png
  .github/tests-visual/media_manager_types.png
  .github/tests-visual/media_manager_types_edit--dark.png
  .github/tests-visual/media_manager_types_edit.png
  .github/tests-visual/visual-record.js
Labels: automerge

#4861 visual-tests: hard exit on failure
  .github/tests-visual/visual-record.js
Labels: Contributor Experience, automerge, Github Actions

#4864 visual-testing: don‘t interrupt testing on the first error
  .github/tests-visual/visual-record.js
Labels: automerge

#4866 visual-tests: declare local var
  .github/tests-visual/visual-record.js
Labels: automerge

#4859 apply selected rex theme to clockwork
  redaxo/src/addons/debug/boot.php
  redaxo/src/addons/debug/package.yml
  redaxo/src/core/lib/rex.php
Labels: Debug, automerge

#4868 visual-tests: fix error handling
  .github/tests-visual/visual-record.js
Labels: automerge, Github Actions

#4867 visual-tests: check clockwork interface (dark-mode only)
  .github/tests-visual/debug_clockwork--dark.png
  .github/tests-visual/debug_clockwork.png
  .github/tests-visual/visual-record.js
Labels: automerge, Github Actions

#4870 visual-tests: show origin for failed ajax requests
  .github/tests-visual/visual-record.js
Labels: automerge, Github Actions

#4873 test-visuals: fix debug race conditions
  .github/tests-visual/visual-record.js
Labels: automerge, Github Actions

#4872 update clockwork frontend - watch for `prefers-color-scheme` changes
  .github/tests-visual/debug_clockwork.png
  redaxo/src/addons/debug/frontend/frontend.zip
Labels: Debug, automerge
