Repository redaxo/redaxo, pull requests merged in 2021-11, with the labels that each got.

#4869 slight css fixes for dark mode
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_buttons.scss
  redaxo/src/addons/be_style/plugins/redaxo/scss/_dropdowns.scss
Labels: automerge

#4871 i18n: validate locale to prevent path traversal
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/lib/util/i18n.php
Labels: automerge

#4875 phpstan: don't use excludes_analyse deprecated config
  phpstan.neon.dist
Labels: automerge

#4846 prevent the sidebar from shrinking
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_navs.scss
  redaxo/src/addons/be_style/plugins/redaxo/scss/_scaffolding.scss
Labels: automerge

#4842 Neue MP-Api optimiert
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
  redaxo/src/addons/mediapool/lib/service_media.php
  redaxo/src/addons/mediapool/pages/media.detail.php
  redaxo/src/addons/mediapool/pages/media.list.php
  redaxo/src/addons/mediapool/pages/sync.php
  redaxo/src/addons/mediapool/pages/upload.php
Labels: automerge

#4878 metainfo: Ablaufoptimierungen
  redaxo/src/addons/metainfo/lib/handler/category_handler.php
  redaxo/src/addons/metainfo/lib/handler/clang_handler.php
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/metainfo/lib/handler/media_handler.php
Labels: automerge

#4877 Markdown: Optional PHP-Highlighting
  .github/tests-visual/packages_help--dark.png
  .github/tests-visual/packages_help.png
  redaxo/src/core/lib/util/markdown.php
  redaxo/src/core/pages/packages.changelog.php
  redaxo/src/core/pages/packages.help.php
Labels: automerge

#4879 Taint-Analyse: Werte aus DB als unsicher betrachten
  .tools/psalm/baseline-taint.xml
  .tools/psalm/baseline.xml
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/sql/util.php
  redaxo/src/core/lib/util/i18n.php
Labels: automerge

#4880 metainfo: Escaping
  .tools/psalm/baseline.xml
  redaxo/src/addons/metainfo/functions/function_metainfo.php
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/metainfo/lib/handler/media_handler.php
  redaxo/src/addons/metainfo/lib/table_manager.php
Labels: automerge

#4881 More escaping
  .tools/psalm/baseline-taint.xml
  .tools/psalm/baseline.xml
  redaxo/src/addons/cronjob/lib/types/phpcode.php
  redaxo/src/addons/cronjob/pages/cronjobs.php
  redaxo/src/addons/structure/lib/service_article.php
  redaxo/src/addons/structure/lib/service_category.php
  redaxo/src/addons/structure/pages/index.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php
  redaxo/src/addons/structure/plugins/content/lib/content_service.php
  redaxo/src/addons/structure/plugins/content/pages/content.php
  redaxo/src/addons/structure/plugins/content/pages/modules.actions.php
  redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
  redaxo/src/addons/structure/plugins/history/boot.php
  redaxo/src/addons/users/pages/roles.php
  redaxo/src/core/lib/be/page.php
  redaxo/src/core/lib/sql/schema_dumper.php
  redaxo/src/core/lib/util/pager.php
  redaxo/src/core/pages/credits.php
  redaxo/src/core/pages/system.clangs.php
Labels: automerge

#4882 Update vendor
  .tools/bin/update-all
  composer.json
  redaxo/src/addons/debug/composer.lock
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Clockwork.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/DataSource/PhpDataSource.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Helpers/Concerns/ResolvesViewName.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Helpers/StackFrame.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/ShouldCollect.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/ShouldRecord.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/Timeline/Event.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Storage/FileStorage.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Storage/Storage.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Storage/StorageInterface.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/composer.json
  redaxo/src/core/vendor/composer/installed.php
Labels: automerge

#4883 rex_var/rex_type: phpdocs
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/util/type.php
  redaxo/src/core/lib/var/var.php
Labels: automerge

#4150 rex_sql: added types for get/setValue
  .tools/psalm/baseline.xml
  redaxo/src/addons/cronjob/plugins/article_status/lib/cronjob.php
  redaxo/src/addons/media_manager/pages/effects.php
  redaxo/src/addons/mediapool/pages/media.detail.php
  redaxo/src/addons/metainfo/boot.php
  redaxo/src/addons/metainfo/extensions/extension_cleanup.php
  redaxo/src/addons/metainfo/functions/function_metainfo.php
  redaxo/src/addons/metainfo/install.php
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/metainfo/lib/handler/media_handler.php
  redaxo/src/addons/metainfo/lib/table_expander.php
  redaxo/src/addons/structure/lib/service_article.php
  redaxo/src/addons/structure/lib/service_category.php
  redaxo/src/addons/structure/pages/index.php
  redaxo/src/addons/structure/plugins/content/lib/api_template.php
  redaxo/src/addons/structure/plugins/content/lib/article_action.php
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#4884 PHPStan: "Offset always exists" generell unterdrücken
  .tools/phpstan/baseline.neon
  phpstan.neon.dist
Labels: automerge

#4885 dump(): rex_editor nutzen, Verlinkung zur Stelle im Code
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/util/editor.php
  redaxo/src/core/lib/var_dumper.php
Labels: automerge

#4886 Release 5.13.0-beta1
  redaxo/src/addons/backup/CHANGELOG.md
  redaxo/src/addons/backup/package.yml
  redaxo/src/addons/be_style/CHANGELOG.md
  redaxo/src/addons/be_style/package.yml
  redaxo/src/addons/be_style/plugins/customizer/package.yml
  redaxo/src/addons/be_style/plugins/redaxo/package.yml
  redaxo/src/addons/cronjob/package.yml
  redaxo/src/addons/cronjob/plugins/article_status/package.yml
  redaxo/src/addons/cronjob/plugins/optimize_tables/package.yml
  redaxo/src/addons/debug/CHANGELOG.md
  redaxo/src/addons/debug/package.yml
  redaxo/src/addons/install/package.yml
  redaxo/src/addons/media_manager/CHANGELOG.md
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/addons/mediapool/CHANGELOG.md
  redaxo/src/addons/mediapool/package.yml
  redaxo/src/addons/metainfo/CHANGELOG.md
  redaxo/src/addons/metainfo/package.yml
  redaxo/src/addons/phpmailer/CHANGELOG.md
  redaxo/src/addons/phpmailer/package.yml
  redaxo/src/addons/structure/CHANGELOG.md
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/plugins/content/package.yml
  redaxo/src/addons/users/package.yml
  redaxo/src/core/CHANGELOG.md
  redaxo/src/core/boot.php
Labels: automerge

#4888 Fix typo
  redaxo/src/core/CHANGELOG.md
Labels: automerge

#4889 Debug-Addon: Notice vermeiden in custom cli-Skripten
  redaxo/src/addons/debug/boot.php
Labels: Debug, automerge

#4894 dump()/basename() über psalm verbieten
  .tools/psalm/deprecated.stub
  psalm.xml
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/util/path.php
Labels: automerge

#4897 redaxo/php-cs-fixer-config nutzen
  .idea/php.xml
  .idea/redaxo.iml
  .php-cs-fixer.dist.php
  .tools/rector/Util/UnderscoreCamelCaseConflictingNameGuard.php
  composer.json
Labels: automerge

#4896 redaxo/psalm-plugin nutzen
  .idea/php.xml
  .idea/redaxo.iml
  .tools/psalm/RexTypeReturnProvider.php
  composer.json
  psalm.xml
Labels: automerge

#4893 R 5.13: Hover bei farbigen Buttons innerhalb Tableiste fehlerhaft
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_buttons.scss
Labels: automerge

#4874 Update PHPStan to 1.0, rector to 0.12.x
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  composer.json
  redaxo/src/core/lib/setup/setup.php
Labels: automerge

#4905 Doppelte Variable $clang
  redaxo/src/addons/structure/plugins/content/lib/content_service.php
Labels: automerge

#4909 Socket Aufruf von fsockopen auf stream_context_create geändert
  redaxo/src/core/lib/util/socket/socket.php
  redaxo/src/core/tests/util/socket_test.php
Labels: automerge

#4906 PHP-Cache-Dateien: Bei Neugenerierung Opcache invalidieren
  redaxo/src/addons/structure/plugins/content/lib/cache_template.php
  redaxo/src/addons/structure/plugins/content/lib/content_service.php
Labels: automerge

#4910 markdown-Pages: PHP-Highlighting aktivieren
  redaxo/src/core/lib/be/controller.php
Labels: automerge

#4903 tooltips überall nutzbar machen
  redaxo/src/addons/be_style/assets/javascripts/main.js
  redaxo/src/addons/phpmailer/pages/config.php
  redaxo/src/core/assets/standard.js
Labels: automerge

#4911 rex_form: phpdocs
  .tools/psalm/baseline.xml
  redaxo/src/addons/cronjob/lib/form.php
  redaxo/src/addons/metainfo/lib/table_expander.php
  redaxo/src/core/lib/form/form.php
  redaxo/src/core/lib/form/form_base.php
Labels: automerge

#4902 intl-Extension nicht frühzeitig im Setup nutzen
  redaxo/src/core/layout/top.php
  redaxo/src/core/lib/util/i18n.php
Labels: automerge

#4912 R 5.13: Structure/version für Dark Mode anpassen
  .github/tests-visual/structure_article_edit--dark.png
  .github/tests-visual/structure_article_functions--dark.png
  .github/tests-visual/structure_slice_edit--dark.png
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_bootstrap-dark-overrides.scss
  redaxo/src/addons/be_style/plugins/redaxo/scss/_scaffolding.scss
  redaxo/src/addons/be_style/plugins/redaxo/scss/bootstrap-dark-overrides/_navbar.scss
Labels: automerge

#4913 R 5.13: Structure/history korrigieren und für Dark Mode anpassen
  redaxo/src/addons/structure/plugins/history/assets/history.css
Labels: automerge

#4914 Release 5.13.0-beta2
  redaxo/src/addons/backup/package.yml
  redaxo/src/addons/be_style/CHANGELOG.md
  redaxo/src/addons/be_style/package.yml
  redaxo/src/addons/be_style/plugins/customizer/package.yml
  redaxo/src/addons/be_style/plugins/redaxo/package.yml
  redaxo/src/addons/cronjob/package.yml
  redaxo/src/addons/cronjob/plugins/article_status/package.yml
  redaxo/src/addons/cronjob/plugins/optimize_tables/package.yml
  redaxo/src/addons/debug/package.yml
  redaxo/src/addons/install/package.yml
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/addons/mediapool/package.yml
  redaxo/src/addons/metainfo/package.yml
  redaxo/src/addons/phpmailer/package.yml
  redaxo/src/addons/structure/CHANGELOG.md
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/plugins/content/package.yml
  redaxo/src/addons/structure/plugins/history/package.yml
  redaxo/src/addons/structure/plugins/version/package.yml
  redaxo/src/addons/users/package.yml
  redaxo/src/core/CHANGELOG.md
  redaxo/src/core/boot.php
Labels: automerge

#4916 Anpassung codemirror an REDAXO 5.13
  redaxo/src/addons/be_style/plugins/customizer/assets/vendor/codemirror.zip
Labels: automerge

#4917 Update vendors
  .tools/bin/update-root-composer
  composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
Labels: automerge

#4918 System-Mediatypen auch über Icon nicht verlinken
  .github/tests-visual/media_manager_types--dark.png
  .github/tests-visual/media_manager_types.png
  redaxo/src/addons/media_manager/pages/types.php
Labels: automerge

#4922 Core-Update: Logger-Klasse vor Update laden
  redaxo/src/addons/install/lib/api/api_core_update.php
Labels: automerge

#4921 Core-Update: Besserer Umgang mit fehlenden Schreibrechten
  redaxo/src/addons/install/lang/de_de.lang
  redaxo/src/addons/install/lang/en_gb.lang
  redaxo/src/addons/install/lib/api/api_core_update.php
Labels: automerge

#4923 Release install 2.9.2
  redaxo/src/addons/install/CHANGELOG.md
  redaxo/src/addons/install/package.yml
Labels: automerge

#4924 Require install addon 2.9.2
  redaxo/src/core/update.php
Labels: automerge

#4925 Release 5.13.0
  redaxo/src/addons/backup/CHANGELOG.md
  redaxo/src/addons/backup/package.yml
  redaxo/src/addons/be_style/CHANGELOG.md
  redaxo/src/addons/be_style/package.yml
  redaxo/src/addons/be_style/plugins/customizer/package.yml
  redaxo/src/addons/be_style/plugins/redaxo/package.yml
  redaxo/src/addons/cronjob/package.yml
  redaxo/src/addons/cronjob/plugins/article_status/package.yml
  redaxo/src/addons/cronjob/plugins/optimize_tables/package.yml
  redaxo/src/addons/debug/CHANGELOG.md
  redaxo/src/addons/debug/package.yml
  redaxo/src/addons/install/package.yml
  redaxo/src/addons/media_manager/CHANGELOG.md
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/addons/mediapool/CHANGELOG.md
  redaxo/src/addons/mediapool/package.yml
  redaxo/src/addons/metainfo/CHANGELOG.md
  redaxo/src/addons/metainfo/package.yml
  redaxo/src/addons/phpmailer/CHANGELOG.md
  redaxo/src/addons/phpmailer/package.yml
  redaxo/src/addons/structure/CHANGELOG.md
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/plugins/content/package.yml
  redaxo/src/addons/structure/plugins/history/package.yml
  redaxo/src/addons/structure/plugins/version/package.yml
  redaxo/src/addons/users/package.yml
  redaxo/src/core/CHANGELOG.md
  redaxo/src/core/boot.php
Labels: automerge

#4929 rex_sql_table: 0 als Defaultwert erlauben
  redaxo/src/core/lib/sql/table.php
  redaxo/src/core/tests/sql/sql_table_test.php
Labels: Bug, Core, automerge

#4931 Version 5.13.1-dev
  redaxo/src/core/boot.php
Labels: automerge

#4930 Markdown: Syntaxt-Highlighting: Short-Open-Echo-Tag berücksichtigen
  redaxo/src/core/lib/util/markdown.php
Labels: automerge

#4932 Templates: Modulzuweisung zu CTypes korrigiert
  redaxo/src/addons/structure/plugins/content/pages/templates.php
Labels: automerge

#4933 Update vendors
  .tools/psalm/baseline-taint.xml
  .tools/psalm/baseline.xml
  composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/InstalledVersions.php
  redaxo/src/core/vendor/composer/autoload_classmap.php
  redaxo/src/core/vendor/composer/autoload_static.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
  redaxo/src/core/vendor/symfony/console/Application.php
  redaxo/src/core/vendor/symfony/console/Input/ArgvInput.php
  redaxo/src/core/vendor/symfony/console/Logger/ConsoleLogger.php
  redaxo/src/core/vendor/symfony/console/Output/TrimmedBufferOutput.php
  redaxo/src/core/vendor/symfony/console/composer.json
  redaxo/src/core/vendor/symfony/deprecation-contracts/composer.json
  redaxo/src/core/vendor/symfony/http-foundation/IpUtils.php
  redaxo/src/core/vendor/symfony/http-foundation/Request.php
  redaxo/src/core/vendor/symfony/service-contracts/Attribute/SubscribedService.php
  redaxo/src/core/vendor/symfony/service-contracts/ServiceSubscriberTrait.php
  redaxo/src/core/vendor/symfony/service-contracts/composer.json
  redaxo/src/core/vendor/symfony/var-dumper/Caster/DateCaster.php
  redaxo/src/core/vendor/symfony/yaml/Inline.php
Labels: automerge

#4937 Profil: Passwort austauschen
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/sv_se.lang
  redaxo/src/core/pages/profile.php
Labels: automerge

#4934 Assets-Urls robuster ggü. Firewalls machen
  .tools/psalm/baseline.xml
  redaxo/src/core/fragments/core/top.php
Labels: automerge

#4939 Eingeloggt bleiben: Cookie nicht unnötig invalidieren
  redaxo/src/core/lib/login/backend_login.php
Labels: Bug, automerge

#4940 PHP 8.1: Deprecations aufgelöst
  .tools/psalm/baseline.xml
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/phpmailer/pages/log.php
  redaxo/src/addons/users/lib/select_element.php
Labels: Bug, automerge

#4941 actions: update php version
  .github/workflows/styles-compile.yml
  .github/workflows/unit-tests.yml
  .github/workflows/visual-tests.yml
Labels: automerge

#4938 Passwortänderung: Sessions beenden
  .tools/psalm/baseline.xml
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/lib/login/login.php
  redaxo/src/core/pages/profile.php
  redaxo/src/core/update.php
Labels: Security, automerge

#4943 UI: Weitere Hinzufügen-Links vergrößert
  redaxo/src/addons/media_manager/pages/types.php
  redaxo/src/addons/metainfo/pages/field.php
Labels: Design / CSS, User Experience (UX), automerge

#4945 PHP 8.2: Attribut AllowDynamicProperties verwenden
  redaxo/src/addons/mediapool/lib/media.php
  redaxo/src/addons/structure/lib/structure_element.php
  redaxo/src/core/lib/clang/clang.php
Labels: automerge

#4946 Update vendors
  composer.json
  redaxo/src/addons/phpmailer/composer.lock
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/VERSION
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/language/phpmailer.lang-fr.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/language/phpmailer.lang-pt_br.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/language/phpmailer.lang-ro.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/language/phpmailer.lang-sl.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/PHPMailer.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/POP3.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/SMTP.php
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
  redaxo/src/core/vendor/voku/anti-xss/src/voku/helper/AntiXSS.php
Labels: automerge

#4944 Docker: Kleine Anpassungen
  .gitignore
  README.de.md
  README.md
  docker-compose.yml
Labels: Developer Experience (DX), automerge

#4947 Release 5.13.1
  redaxo/src/addons/media_manager/CHANGELOG.md
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/addons/metainfo/CHANGELOG.md
  redaxo/src/addons/metainfo/package.yml
  redaxo/src/addons/phpmailer/CHANGELOG.md
  redaxo/src/addons/phpmailer/package.yml
  redaxo/src/addons/structure/CHANGELOG.md
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/plugins/content/package.yml
  redaxo/src/addons/users/CHANGELOG.md
  redaxo/src/addons/users/package.yml
  redaxo/src/core/CHANGELOG.md
  redaxo/src/core/boot.php
Labels: automerge

#4948 Added php 8.1 eol date
  redaxo/src/core/lib/setup/setup.php
Labels: automerge

#4949 Added MariaDb 10.6 eol date
  redaxo/src/core/lib/setup/setup.php
Labels: automerge
