Repository redaxo/redaxo, pull requests merged in 2021-04, with the labels that each got.

#4614 removed dead code
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#4608 rex_string/rex_version: more types
  .tools/psalm/baseline.xml
  redaxo/src/addons/structure/lib/navigation.php
  redaxo/src/core/lib/util/string.php
  redaxo/src/core/lib/util/version.php
Labels: automerge

#4615 psalm: remove unused vars
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/backup/pages/export.php
  redaxo/src/addons/backup/pages/import.server.php
  redaxo/src/addons/backup/pages/import.upload.php
Labels: automerge

#4618 remove unused vars
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/addons/backup/pages/import.upload.php
  redaxo/src/addons/be_style/boot.php
  redaxo/src/addons/be_style/plugins/customizer/pages/system.customizer.php
  redaxo/src/addons/media_manager/install.php
  redaxo/src/addons/media_manager/pages/effects.php
  redaxo/src/addons/media_manager/pages/types.php
  redaxo/src/addons/mediapool/boot.php
  redaxo/src/addons/mediapool/pages/index.php
  redaxo/src/addons/metainfo/boot.php
  redaxo/src/addons/metainfo/functions/function_metainfo.php
  redaxo/src/addons/metainfo/install.php
  redaxo/src/addons/metainfo/pages/field.php
  redaxo/src/addons/metainfo/pages/index.php
  redaxo/src/addons/phpmailer/pages/config.php
  redaxo/src/addons/structure/plugins/content/pages/modules.actions.php
  redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
  redaxo/src/addons/structure/plugins/history/boot.php
  redaxo/src/addons/structure/plugins/version/boot.php
  redaxo/src/addons/structure/tests/category_test.php
  redaxo/src/addons/structure/tests/navigation_test.php
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/tests/base/singleton_trait_test.php
  redaxo/src/core/tests/sql/sql_table_test.php
  redaxo/src/core/tests/util/markdown_test.php
  redaxo/src/core/tests/util/validator_test.php
Labels: automerge

#4622 Korrektur for-Attribut für E-Mail-Archivierung
  redaxo/src/addons/phpmailer/pages/config.php
Labels: automerge

#4625 disable phpstan debug mode
  .github/workflows/static-analysis.yml
Labels: automerge

#4626 Remove ci-skip handling, which is supported natively
  .github/workflows/unit-tests.yml
Labels: automerge

#4630 Visual-Tests auch in Draft-PRs
  .github/workflows/visual-tests.yml
Labels: automerge

#4629 Dependabot-PRs ohne Schreibrechte
  .github/workflows/code-style.yml
  .github/workflows/rexlint.yml
  .github/workflows/static-analysis.yml
  .github/workflows/styles-compile.yml
  .github/workflows/visual-tests.yml
Labels: automerge

#4634 rex_sql::replace() phpdoc
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#4631 Move Debug-Settings outside SMTP-Settings
  .github/tests-visual/phpmailer_config.png
  redaxo/src/addons/phpmailer/pages/config.php
Labels: PHPMailer, User Experience (UX)

#4636 remove unused code
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/addons/cronjob/pages/cronjobs.php
  redaxo/src/addons/cronjob/pages/log.php
  redaxo/src/addons/debug/boot.php
  redaxo/src/addons/install/lib/archive.php
  redaxo/src/addons/install/lib/packages.php
  redaxo/src/addons/install/lib/webservice.php
  redaxo/src/addons/media_manager/lib/effects/effect_filter_colorize.php
  redaxo/src/addons/media_manager/pages/settings.php
  redaxo/src/addons/metainfo/install.php
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/metainfo/pages/content.metainfo.php
  redaxo/src/addons/phpmailer/boot.php
  redaxo/src/addons/phpmailer/pages/checkmail.php
  redaxo/src/addons/phpmailer/pages/log.php
Labels: automerge

#4637 log: more types
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/util/log_file.php
  redaxo/src/core/lib/util/logger.php
Labels: automerge

#4641 google FLoC optout per default aktivieren
  redaxo/src/core/backend.php
Labels: automerge

#4609 factory-trait: more types & deprecate callFactoryClass
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/api_function.php
  redaxo/src/core/lib/base/factory_trait.php
  redaxo/src/core/lib/extension.php
  redaxo/src/core/lib/util/logger.php
  redaxo/src/core/tests/base/factory_trait_test.php
Labels: automerge

#4654 Update vendors
  .tools/bin/update-all
  composer.json
  redaxo/src/addons/debug/composer.lock
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Clockwork.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/DataSource/PhpDataSource.php
  redaxo/src/addons/phpmailer/composer.lock
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/VERSION
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/composer.json
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/language/phpmailer.lang-uk.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/PHPMailer.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/POP3.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/SMTP.php
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/InstalledVersions.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Util/SystemFacade.php
  redaxo/src/core/vendor/symfony/deprecation-contracts/LICENSE
  redaxo/src/core/vendor/symfony/deprecation-contracts/composer.json
  redaxo/src/core/vendor/symfony/service-contracts/Attribute/Required.php
  redaxo/src/core/vendor/symfony/service-contracts/LICENSE
  redaxo/src/core/vendor/symfony/service-contracts/ServiceLocatorTrait.php
  redaxo/src/core/vendor/symfony/service-contracts/ServiceSubscriberInterface.php
  redaxo/src/core/vendor/symfony/service-contracts/ServiceSubscriberTrait.php
  redaxo/src/core/vendor/symfony/service-contracts/composer.json
Labels: automerge

#4655 Release phpmailer 2.10.1
  redaxo/src/addons/phpmailer/CHANGELOG.md
  redaxo/src/addons/phpmailer/package.yml
Labels: Security, automerge

#4656 PhpStorm-Settings: baselines nicht mehr excluden
  .idea/redaxo.iml
Labels: automerge
