Repository redaxo/redaxo, pull requests merged in 2021-03, with the labels that each got.

#4512 Setup: Backend-Session nicht beenden
  redaxo/src/core/lib/setup/setup.php
Labels: automerge

#4511 rex_formatter: handle 0000-00-00
  redaxo/src/core/lib/util/formatter.php
Labels: automerge

#4516 be_style: Während Update korrekte Assets kopieren
  redaxo/src/addons/be_style/install.php
Labels: Bug, automerge

#4515 Release 5.12.0-beta3
  redaxo/src/addons/backup/package.yml
  redaxo/src/addons/be_style/CHANGELOG.md
  redaxo/src/addons/be_style/package.yml
  redaxo/src/addons/be_style/plugins/customizer/package.yml
  redaxo/src/addons/be_style/plugins/redaxo/package.yml
  redaxo/src/addons/cronjob/package.yml
  redaxo/src/addons/cronjob/plugins/article_status/package.yml
  redaxo/src/addons/debug/package.yml
  redaxo/src/addons/install/package.yml
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/addons/mediapool/package.yml
  redaxo/src/addons/metainfo/package.yml
  redaxo/src/addons/phpmailer/package.yml
  redaxo/src/addons/structure/CHANGELOG.md
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/plugins/content/package.yml
  redaxo/src/addons/structure/plugins/history/package.yml
  redaxo/src/addons/structure/plugins/version/package.yml
  redaxo/src/addons/users/package.yml
  redaxo/src/core/CHANGELOG.md
  redaxo/src/core/boot.php
Labels: automerge

#4517 psalm action: type-coverage ausgeben
  .github/workflows/static-analysis.yml
Labels: automerge

#4522 Update vendors
  .tools/bin/update-all
  composer.json
  redaxo/src/addons/backup/composer.lock
  redaxo/src/addons/backup/vendor/splitbrain/php-archive/composer.json
  redaxo/src/addons/backup/vendor/splitbrain/php-archive/src/Tar.php
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/ClassLoader.php
  redaxo/src/core/vendor/composer/InstalledVersions.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
Labels: automerge

#4523 Update jquery 3.6.0
  redaxo/src/core/assets/jquery.js
  redaxo/src/core/assets/jquery.min.js
  redaxo/src/core/assets/jquery.min.map
Labels: automerge

#4525 run php 7.3 actions on ubuntu-18.04
  .github/workflows/code-style.yml
  .github/workflows/rexlint.yml
  .github/workflows/unit-tests.yml
Labels: automerge

#4528 addSqlOptions / addDBSqlOptions: DB-Auswahl ergänzt
  redaxo/src/core/lib/select.php
Labels: automerge

#4530 added db-query related phpdocs
  redaxo/src/core/lib/select.php
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#4531 Version 5.12.1-dev
  redaxo/src/core/boot.php
Labels: automerge

#4532 Version 5.13.0-dev
  redaxo/src/core/boot.php
Labels: automerge

#4534 rex_be_controller: more precise phpdoc
  redaxo/src/core/lib/be/controller.php
Labels: automerge

#4533 rex_path: added phpdoc
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/boot.php
  redaxo/src/core/lib/util/path.php
Labels: automerge

#4536 Update vendors
  composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/InstalledVersions.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
  redaxo/src/core/vendor/psr/container/composer.json
  redaxo/src/core/vendor/psr/container/src/ContainerExceptionInterface.php
  redaxo/src/core/vendor/psr/container/src/ContainerInterface.php
  redaxo/src/core/vendor/psr/container/src/NotFoundExceptionInterface.php
  redaxo/src/core/vendor/symfony/console/Exception/CommandNotFoundException.php
  redaxo/src/core/vendor/symfony/console/Helper/Helper.php
  redaxo/src/core/vendor/symfony/console/Helper/QuestionHelper.php
  redaxo/src/core/vendor/symfony/console/Input/StringInput.php
  redaxo/src/core/vendor/symfony/http-foundation/HeaderUtils.php
  redaxo/src/core/vendor/symfony/http-foundation/Request.php
  redaxo/src/core/vendor/symfony/http-foundation/Response.php
  redaxo/src/core/vendor/symfony/http-foundation/Session/Storage/Handler/MarshallingSessionHandler.php
  redaxo/src/core/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php
  redaxo/src/core/vendor/symfony/string/Resources/functions.php
  redaxo/src/core/vendor/symfony/yaml/Exception/ParseException.php
Labels: automerge

#4535 Actions: Cache für psalm/phpstan entfernt
  .github/workflows/static-analysis.yml
Labels: automerge

#4542 rex_input_select: added phpdoc
  redaxo/src/addons/metainfo/lib/input/select.php
Labels: automerge

#4539 backup: added phpdocs
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/backup/lib/tar.php
Labels: automerge

#4544 socket_response: added phpdocs
  redaxo/src/core/lib/util/socket/socket_response.php
Labels: automerge

#4543 rex_article_action: added phpdoc
  redaxo/src/addons/structure/plugins/content/lib/article_action.php
Labels: automerge

#4541 managed_media: added phpdocs
  redaxo/src/addons/media_manager/lib/managed_media.php
Labels: automerge

#4540 Added manager_sql phpdocs
  .tools/psalm/baseline-taint.xml
  redaxo/src/addons/cronjob/lib/cronjob.php
  redaxo/src/addons/cronjob/lib/manager_sql.php
Labels: automerge

#4545 actions: auto commit psalm baselines
  .github/workflows/static-analysis.yml
Labels: automerge

#4547 rex_view messages: taint-specialize nutzen
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/lib/view.php
Labels: automerge

#4546 psalm: activate 'mixed' errors
  .tools/psalm/baseline.xml
  psalm.xml
Labels: automerge

#4548 fix psalm errors in unit tests
  .tools/psalm/baseline.xml
  redaxo/src/core/tests/base/instance_list_pool_trait_test.php
  redaxo/src/core/tests/sql/sql_table_test.php
  redaxo/src/core/tests/util/dir_test.php
  redaxo/src/core/tests/util/file_test.php
  redaxo/src/core/tests/util/finder_test.php
  redaxo/src/core/tests/util/i18n_test.php
  redaxo/src/core/tests/util/log_file_test.php
Labels: automerge

#4538 Login page: input styles + show background image for mobile devices
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_login.scss
Labels: automerge

#4550 rex_stream: add types
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/util/stream.php
Labels: automerge

#4553 rex_sql_column/index/fk: phpdocs
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/sql/column.php
  redaxo/src/core/lib/sql/foreign_key.php
  redaxo/src/core/lib/sql/index.php
Labels: automerge

#4552 rex_sql_table: more specific types
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/sql/table.php
Labels: automerge

#4549 rex_package: add types for getPath methods
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/packages/interface.php
  redaxo/src/core/lib/packages/null.php
Labels: automerge

#4556 rex_media::forId ergänzt
  redaxo/src/addons/mediapool/lib/media.php
Labels: Mediapool, automerge

#4558 Mediapool get media list
  .tools/psalm/baseline.xml
  redaxo/src/addons/mediapool/lib/service_media.php
  redaxo/src/addons/mediapool/pages/media.list.php
Labels: Mediapool, automerge

#4561 check if params width/height are set
  redaxo/src/addons/media_manager/lib/effects/effect_resize.php
Labels: automerge

#4566 Update vendors
  composer.json
  redaxo/src/addons/debug/composer.lock
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Clockwork.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/Timeline/Event.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Support/Vanilla/config.php
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/InstalledVersions.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
  redaxo/src/core/vendor/symfony/console/Command/HelpCommand.php
  redaxo/src/core/vendor/symfony/console/Command/ListCommand.php
  redaxo/src/core/vendor/symfony/var-dumper/Command/ServerDumpCommand.php
  redaxo/src/core/vendor/symfony/yaml/Command/LintCommand.php
Labels: automerge

#4569 more precise phpdoc
  redaxo/src/addons/structure/plugins/content/lib/article_slice.php
Labels: automerge

#4573 update tools
  .idea/php.xml
  .idea/redaxo.iml
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline-taint.xml
  .tools/psalm/baseline.xml
  composer.json
Labels: automerge

#4572 login page: reduce z-index for footer
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_login.scss
Labels: automerge

#4574 rex_socket: timer label korrigiert
  redaxo/src/core/lib/util/socket/socket.php
Labels: automerge

#4575 rex_sql::getArray: more specific types
  .tools/psalm/baseline.xml
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/cronjob/update.php
  redaxo/src/addons/mediapool/lib/mediapool.php
  redaxo/src/addons/mediapool/pages/sync.php
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/metainfo/lib/handler/media_handler.php
  redaxo/src/addons/metainfo/lib/table_expander.php
  redaxo/src/addons/structure/lib/service_article.php
  redaxo/src/addons/structure/lib/service_category.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php
  redaxo/src/addons/structure/plugins/content/pages/templates.php
  redaxo/src/addons/users/lib/role.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/pages/setup.step5.php
Labels: automerge

#4576 rex_media_manager: more types
  .tools/psalm/baseline.xml
  redaxo/src/addons/media_manager/lib/managed_media.php
  redaxo/src/addons/media_manager/lib/media_manager.php
Labels: automerge

#4577 media manager: more types
  .tools/psalm/baseline.xml
  redaxo/src/addons/media_manager/lib/effect_abstract.php
  redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
  redaxo/src/addons/media_manager/lib/effects/effect_crop.php
  redaxo/src/addons/media_manager/lib/effects/effect_filter_blur.php
  redaxo/src/addons/media_manager/lib/effects/effect_filter_colorize.php
  redaxo/src/addons/media_manager/lib/effects/effect_filter_sharpen.php
  redaxo/src/addons/media_manager/lib/effects/effect_flip.php
  redaxo/src/addons/media_manager/lib/effects/effect_image_format.php
  redaxo/src/addons/media_manager/lib/effects/effect_insert_image.php
  redaxo/src/addons/media_manager/lib/effects/effect_mirror.php
  redaxo/src/addons/media_manager/lib/effects/effect_resize.php
  redaxo/src/addons/media_manager/lib/effects/effect_rotate.php
  redaxo/src/addons/media_manager/lib/effects/effect_rounded_corners.php
  redaxo/src/addons/media_manager/lib/effects/effect_workspace.php
  redaxo/src/addons/media_manager/lib/managed_media.php
  redaxo/src/addons/media_manager/pages/effects.php
Labels: automerge

#4578 rex_pager: new methods setPage/setCursor
  redaxo/src/core/lib/util/pager.php
  redaxo/src/core/tests/util/pager_test.php
Labels: automerge

#4581 rex_backup_tar::getMessages existiert nicht mehr
  redaxo/src/addons/backup/lang/de_de.lang
  redaxo/src/addons/backup/lang/en_gb.lang
  redaxo/src/addons/backup/lang/es_es.lang
  redaxo/src/addons/backup/lang/it_it.lang
  redaxo/src/addons/backup/lang/pt_br.lang
  redaxo/src/addons/backup/lang/sv_se.lang
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/backup/package.yml
Labels: automerge

#4579 rex_media_service::getList: rex_pager nutzen
  redaxo/src/addons/mediapool/lib/service_media.php
  redaxo/src/addons/mediapool/pages/media.list.php
Labels: automerge

#4582 rex_path/rex_stream: taint specialize
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/lib/util/path_default_provider.php
  redaxo/src/core/lib/util/stream.php
Labels: automerge

#4584 Make sure we don‘t leak a output-buffer on exceptions
  redaxo/src/addons/structure/plugins/content/lib/article_content.php
Labels: automerge

#4583 rex_article_content: more types
  .tools/psalm/baseline-taint.xml
  .tools/psalm/baseline.xml
  redaxo/src/addons/structure/plugins/content/lib/article_content.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php
  redaxo/src/addons/structure/plugins/content/pages/content.edit.php
Labels: automerge

#4589 login page: fix z-index for footer (#4572)
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_login.scss
Labels: automerge

#4590 Visual tests: hide blinking cursor + increase timeout
  .github/tests-visual/login.png
  .github/tests-visual/logout.png
  .github/tests-visual/packages.png
  .github/tests-visual/setup_4.png
  .github/tests-visual/structure_category_edit.png
  .github/tests-visual/visual-record.js
Labels: automerge

#4591 rector: disable process timeout
  composer.json
Labels: automerge

#4595 update phpstorm settings
  .idea/redaxo.iml
  .idea/scopes/core___core_addons.xml
Labels: automerge

#4592 Neues Hilfskript rebase-to-bugfix
  .tools/bin/rebase-to-bugfix
  composer.json
Labels: automerge

#4596 rex_package: more types
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/packages/interface.php
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/lib/packages/null.php
  redaxo/src/core/lib/packages/package.php
  redaxo/src/core/pages/credits.php
Labels: automerge

#4585 Neue Methode rex::requireUser()
  .tools/psalm/baseline.xml
  redaxo/src/core/layout/top.php
  redaxo/src/core/lib/be/navigation.php
  redaxo/src/core/lib/form/form.php
  redaxo/src/core/lib/login/api_user_impersonate.php
  redaxo/src/core/lib/rex.php
  redaxo/src/core/lib/view.php
  redaxo/src/core/pages/profile.php
Labels: automerge

#4598 fix clone-addon script
  .tools/bin/clone-addon
Labels: automerge

#4594 Neuer Command: package:run-update-script
  redaxo/src/core/lib/console/command_loader.php
  redaxo/src/core/lib/console/package/run_update_script.php
Labels: Add to Docs, automerge

#4602 rex_url: phpdocs
  .tools/psalm/baseline.xml
  redaxo/src/core/boot.php
  redaxo/src/core/lib/util/url.php
Labels: automerge

#4607 Update vendors
  composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/InstalledVersions.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
  redaxo/src/core/vendor/filp/whoops/composer.json
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Handler/JsonResponseHandler.php
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Handler/PlainTextHandler.php
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Handler/XmlResponseHandler.php
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Run.php
  redaxo/src/core/vendor/filp/whoops/src/Whoops/RunInterface.php
  redaxo/src/core/vendor/symfony/console/Command/Command.php
  redaxo/src/core/vendor/symfony/console/Helper/Helper.php
  redaxo/src/core/vendor/symfony/console/Helper/ProgressBar.php
  redaxo/src/core/vendor/symfony/console/Helper/QuestionHelper.php
  redaxo/src/core/vendor/symfony/console/Input/ArrayInput.php
  redaxo/src/core/vendor/symfony/console/Input/InputOption.php
  redaxo/src/core/vendor/symfony/console/Style/SymfonyStyle.php
  redaxo/src/core/vendor/symfony/string/Inflector/EnglishInflector.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/DateCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/ReflectionCaster.php
Labels: automerge

#4597 Default-Wert für Version korrigiert
  redaxo/src/addons/install/lib/package/package_update.php
Labels: automerge

#4603 Installer: more types
  .tools/psalm/baseline.xml
  redaxo/src/addons/install/lib/api/api_package_upload.php
  redaxo/src/addons/install/lib/archive.php
  redaxo/src/addons/install/lib/package/package_add.php
  redaxo/src/addons/install/lib/package/package_download.php
  redaxo/src/addons/install/lib/package/package_update.php
  redaxo/src/addons/install/lib/packages.php
  redaxo/src/addons/install/lib/webservice.php
  redaxo/src/addons/install/pages/packages.upload.php
Labels: automerge

#4601 rex_version::gitHash: Fix, wenn $repo nicht gesetzt
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/util/version.php
  redaxo/src/core/tests/util/version_test.php
Labels: automerge

#4580 rex_extension::registerPoint: Return-Type über Template
  .tools/psalm/baseline.xml
  redaxo/src/addons/be_style/lib/be_style.php
  redaxo/src/addons/mediapool/lib/service_media.php
  redaxo/src/addons/structure/plugins/content/lib/article_content.php
  redaxo/src/core/functions/function_rex_other.php
  redaxo/src/core/lib/extension.php
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/tests/extension_test.php
Labels: automerge
