Repository redaxo/redaxo, pull requests merged in 2021-02, with the labels that each got.

#4374 Update de_de.lang
  redaxo/src/core/lang/de_de.lang
Labels: automerge

#4363 Packages list: highlight required package
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_utilities.scss
  redaxo/src/core/pages/packages.list.php
Labels: Installer, User Experience (UX), automerge

#4393 github actions mysql version
  .github/tests-visual/setup_4.png
  .github/tests-visual/system_report.png
  .github/tests-visual/system_settings.png
  .github/workflows/cs-check.yml
  .github/workflows/rexlint.yml
  .github/workflows/sarif-report.yml
  .github/workflows/static-analysis.yml
  .github/workflows/styles-compile.yml
  .github/workflows/tests.yml
  .github/workflows/visual-tests.yml
Labels: automerge

#4394 actions: ignore-platform-req nicht mehr notwendig
  .github/workflows/tests.yml
Labels: automerge

#4397 rex_sql::getValue: type-parameter wieder entfernt
  .tools/psalm/RexTypeReturnProvider.php
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/lib/login/user.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/tests/sql/sql_test.php
Labels: automerge

#4399 MM-Effekte-Namen einheitlicher
  redaxo/src/addons/media_manager/lang/en_gb.lang
  redaxo/src/addons/media_manager/lang/es_es.lang
  redaxo/src/addons/media_manager/lang/sv_se.lang
Labels: automerge

#4398 Update be_style vendors
  .github/tests-visual/system_settings.png
  .github/tests-visual/users_edit.png
  redaxo/src/addons/be_style/vendor/bootstrap-select/CHANGELOG.md
  redaxo/src/addons/be_style/vendor/bootstrap-select/CONTRIBUTING.md
  redaxo/src/addons/be_style/vendor/bootstrap-select/README.md
  redaxo/src/addons/be_style/vendor/bootstrap-select/dist/css/bootstrap-select.css
  redaxo/src/addons/be_style/vendor/bootstrap-select/dist/css/bootstrap-select.css.map
  redaxo/src/addons/be_style/vendor/bootstrap-select/dist/css/bootstrap-select.min.css
  redaxo/src/addons/be_style/vendor/bootstrap-select/dist/js/bootstrap-select.js
  redaxo/src/addons/be_style/vendor/bootstrap-select/dist/js/bootstrap-select.js.map
  redaxo/src/addons/be_style/vendor/bootstrap-select/dist/js/bootstrap-select.min.js
  redaxo/src/addons/be_style/vendor/bootstrap-select/dist/js/bootstrap-select.min.js.map
  redaxo/src/addons/be_style/vendor/bootstrap-select/dist/js/i18n/defaults-de_DE.min.js
  redaxo/src/addons/be_style/vendor/bootstrap-select/dist/js/i18n/defaults-en_US.min.js
  redaxo/src/addons/be_style/vendor/bootstrap-select/dist/js/i18n/defaults-es_ES.min.js
  redaxo/src/addons/be_style/vendor/bootstrap-select/dist/js/i18n/defaults-it_IT.min.js
  redaxo/src/addons/be_style/vendor/bootstrap-select/dist/js/i18n/defaults-nl_NL.min.js
  redaxo/src/addons/be_style/vendor/bootstrap-select/dist/js/i18n/defaults-pt_BR.min.js
  redaxo/src/addons/be_style/vendor/bootstrap-select/dist/js/i18n/defaults-sv_SE.min.js
  redaxo/src/addons/be_style/vendor/bootstrap-select/package-lock.json
  redaxo/src/addons/be_style/vendor/bootstrap-select/package.json
  redaxo/src/addons/be_style/vendor/bootstrap-select/sass/bootstrap-select.scss
  redaxo/src/addons/be_style/vendor/bootstrap/CHANGELOG.md
  redaxo/src/addons/be_style/vendor/bootstrap/CONTRIBUTING.md
  redaxo/src/addons/be_style/vendor/bootstrap/README.md
  redaxo/src/addons/be_style/vendor/bootstrap/package-lock.json
  redaxo/src/addons/be_style/vendor/font-awesome/CONTRIBUTING.md
  redaxo/src/addons/be_style/vendor/font-awesome/HELP-US-OUT.txt
  redaxo/src/addons/be_style/vendor/font-awesome/README.md
Labels: automerge

#4400 Visual tests: use puppeteer@6 for now
  .github/tests-visual/cronjob_cronjobs_add.png
  .github/tests-visual/login.png
  .github/tests-visual/metainfo_articles_add.png
  .github/tests-visual/setup_4.png
  .github/tests-visual/structure_article_edit.png
  .github/tests-visual/structure_article_functions.png
  .github/tests-visual/structure_slice_edit.png
  .github/tests-visual/system_customizer.png
  .github/tests-visual/system_settings.png
  .github/tests-visual/users_edit.png
  .github/tests-visual/visual-record.js
  .github/workflows/visual-tests.yml
Labels: automerge

#4395 Beispiel yorm Klasseninitialisierung
  redaxo/src/addons/project/boot.php
Labels: automerge

#4403 Visuelles Feedback beim Wechsel des Debug-Modus
  redaxo/src/core/pages/system.settings.php
Labels: automerge

#4404 Visual tests: update customizer, add more snaps
  .github/tests-visual/logout.png
  .github/tests-visual/packages_customizer_installed.png
  .github/tests-visual/system_settings_safemode.png
  .github/tests-visual/visual-record.js
  .github/workflows/visual-tests.yml
Labels: automerge

#4407 Translation debug lang en
  redaxo/src/addons/debug/lang/en_gb.lang
Labels: automerge

#4419 rex_cronjob_manager: fix/add phpdocs
  redaxo/src/addons/cronjob/lib/manager.php
Labels: automerge

#4406 Packages:: eindeutige, valide id in links
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/pages/packages.list.php
Labels: automerge

#4415 fragment search autofocus
  .github/tests-visual/packages.png
  redaxo/src/addons/install/pages/packages.add.php
  redaxo/src/core/fragments/core/form/search.php
Labels: automerge

#4410 phpmailer :: Prüfen ob mail() verfügbar
  redaxo/src/addons/phpmailer/pages/config.php
Labels: automerge

#4421 set focus on addon search
  .github/tests-visual/packages.png
  redaxo/src/core/pages/packages.list.php
Labels: automerge

#4422 Visual tests: updates
  .github/tests-visual/visual-record.js
Labels: automerge

#4425 Improved readability
  redaxo/src/core/lib/form/form_base.php
Labels: automerge

#4426 Readme en/de for debug AddOn
  redaxo/src/addons/debug/README.de.md
  redaxo/src/addons/debug/README.md
Labels: automerge

#4409 actions: beide cs-check-actions verschmolzen
  .github/workflows/cs-check.yml
  .github/workflows/cs-fix.yml
Labels: automerge

#4427 PHPMailer tidy boot.php, install / update
  .tools/phpstan/baseline.neon
  redaxo/src/addons/phpmailer/boot.php
  redaxo/src/addons/phpmailer/lib/mailer.php
Labels: PHPMailer, automerge

#4428 Be style en readme
  .github/tests-visual/system_settings.png
  .github/tests-visual/system_settings_safemode.png
  redaxo/src/addons/be_style/README.de.md
  redaxo/src/addons/be_style/README.md
  redaxo/src/addons/be_style/help.php
Labels: automerge

#4429 Actions yml-dateien: Einheitlicheres Format und bessere Bezeichnungen
  .github/workflows/chatops.yml
  .github/workflows/code-style.yml
  .github/workflows/cs-fix.yml
  .github/workflows/rexlint.yml
  .github/workflows/sarif-report.yml
  .github/workflows/static-analysis.yml
  .github/workflows/styles-compile.yml
  .github/workflows/tests.yml
  .github/workflows/unit-tests.yml
  .github/workflows/visual-tests.yml
  .idea/codeStyles/Project.xml
Labels: automerge

#4431 Screenshots: Versionen aus-x-en
  .github/tests-visual/system_settings.png
  .github/tests-visual/system_settings_safemode.png
  .github/tests-visual/visual-record.js
Labels: automerge

#4424 UI: adjust tab subnavigation in edit mode
  .github/tests-visual/structure_article_edit.png
  .github/tests-visual/structure_slice_edit.png
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_navs.scss
Labels: automerge

#4408 UI: improve packages list layout
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_tables.scss
  redaxo/src/addons/install/pages/packages.add.php
Labels: automerge

#4430 PHPMailer :: changed suggested mailer to smtp
  .github/tests-visual/phpmailer_config.png
  redaxo/src/addons/phpmailer/package.yml
Labels: PHPMailer, automerge

#4423 UI: update breadcumbs and language select
  .github/tests-visual/index.png
  .github/tests-visual/mediapool_structure.png
  .github/tests-visual/structure_article_edit.png
  .github/tests-visual/structure_article_functions.png
  .github/tests-visual/structure_category_edit.png
  .github/tests-visual/structure_slice_edit.png
  redaxo/src/addons/be_style/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_scaffolding.scss
  redaxo/src/addons/be_style/plugins/redaxo/scss/_variables.scss
Labels: automerge

#4432 Metainfo readme en/de
  redaxo/src/addons/metainfo/README.de.md
  redaxo/src/addons/metainfo/README.md
  redaxo/src/addons/metainfo/help.php
Labels: automerge

#4435 Update vendors
  composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/ClassLoader.php
  redaxo/src/core/vendor/composer/InstalledVersions.php
  redaxo/src/core/vendor/composer/autoload_real.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
  redaxo/src/core/vendor/symfony/console/EventListener/ErrorListener.php
  redaxo/src/core/vendor/symfony/yaml/Dumper.php
Labels: automerge

#4436 Installer: "Addon-Version löschen" optimiert
  redaxo/src/addons/install/lib/api/api_package_delete.php
  redaxo/src/addons/install/pages/packages.upload.php
Labels: automerge

#4441 README für Medienpool
  redaxo/src/addons/mediapool/README.de.md
  redaxo/src/addons/mediapool/README.md
  redaxo/src/addons/mediapool/help.php
Labels: automerge

#4442 README für Struktur AddOn
  redaxo/src/addons/structure/README.de.md
  redaxo/src/addons/structure/README.md
  redaxo/src/addons/structure/help.php
Labels: automerge

#4443 README Installer
  redaxo/src/addons/install/README.de.md
  redaxo/src/addons/install/README.md
  redaxo/src/addons/install/help.php
Labels: automerge

#4444 Visual tests: clang + media
  .github/imports/inital-content-for-visual-tests.sql
  .github/imports/media/redaxo_2018_berlin_sticker.jpg
  .github/tests-visual/backup_import_server.png
  .github/tests-visual/index.png
  .github/tests-visual/mediapool_media.png
  .github/tests-visual/mediapool_media_file.png
  .github/tests-visual/structure_article_edit.png
  .github/tests-visual/structure_article_functions.png
  .github/tests-visual/structure_category_edit.png
  .github/tests-visual/structure_slice_edit.png
  .github/tests-visual/system_lang.png
  .github/tests-visual/visual-record.js
  .github/workflows/visual-tests.yml
Labels: automerge

#4445 UI: show article name, reduce space and change preview icon in edit mode
  .github/tests-visual/structure_article_edit.png
  .github/tests-visual/structure_article_functions.png
  .github/tests-visual/structure_slice_edit.png
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_scaffolding.scss
  redaxo/src/addons/structure/plugins/content/pages/content.php
Labels: automerge

#4449 README backup
  redaxo/src/addons/backup/README.de.md
  redaxo/src/addons/backup/README.md
  redaxo/src/addons/backup/help.php
Labels: automerge

#4452 filter-extension als erforderlich gesetzt
  redaxo/src/core/lib/setup/setup.php
Labels: automerge

#4455 MM-Effekt image_properties: gd-resource erzwingen
  redaxo/src/addons/media_manager/lib/effects/effect_image_properties.php
Labels: automerge

#4457 mediapool: use word-break for title and file name
  redaxo/src/addons/mediapool/pages/media.detail.php
  redaxo/src/addons/mediapool/pages/media.list.php
Labels: automerge

#4454 Enable customizable data-row (<tr>-tag)
  redaxo/src/core/lib/list.php
Labels: automerge

#4458 sanitizeHtml: allow "window.location" code snippet
  redaxo/src/core/lib/util/string.php
  redaxo/src/core/tests/util/string_test.php
Labels: automerge

#4433 Neuer MM-Effect image_format - Bild in anderes Format konvertieren
  redaxo/src/addons/media_manager/lang/de_de.lang
  redaxo/src/addons/media_manager/lang/en_gb.lang
  redaxo/src/addons/media_manager/lib/effects/effect_image_format.php
Labels: automerge

#4462 Update vendors
  .tools/bin/update-all
  composer.json
  redaxo/src/addons/phpmailer/composer.lock
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/VERSION
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/get_oauth_token.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/language/phpmailer.lang-cs.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/language/phpmailer.lang-sk.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/OAuth.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/PHPMailer.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/POP3.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/SMTP.php
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/InstalledVersions.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
  redaxo/src/core/vendor/symfony/polyfill-intl-grapheme/bootstrap80.php
  redaxo/src/core/vendor/symfony/polyfill-intl-normalizer/bootstrap80.php
  redaxo/src/core/vendor/symfony/polyfill-mbstring/bootstrap80.php
Labels: automerge

#4463 setup:run: Bei Fehler abbrechen
  redaxo/src/core/lib/console/setup/run.php
Labels: automerge

#4465 rector: force camcelCase-properties
  .tools/rector/rector.php
  redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
  redaxo/src/addons/media_manager/lib/effects/effect_image_format.php
  redaxo/src/addons/media_manager/lib/managed_media.php
  redaxo/src/addons/media_manager/lib/media_manager.php
  redaxo/src/addons/mediapool/lib/media_category.php
  redaxo/src/addons/mediapool/lib/media_category_select.php
  redaxo/src/addons/structure/lib/linkmap/form_element/linklist.php
  redaxo/src/addons/structure/lib/linkmap/form_element/linkmap.php
  redaxo/src/addons/structure/lib/navigation.php
  redaxo/src/addons/structure/lib/select_category.php
  redaxo/src/addons/structure/plugins/content/lib/article_slice.php
  redaxo/src/core/lib/select.php
  redaxo/src/core/lib/setup/setup.php
Labels: automerge

#4466 Volle rector-Einbingung (composer, action)
  .github/workflows/code-style.yml
  .idea/php.xml
  .idea/redaxo.iml
  composer.json
  rector.php
Labels: automerge

#4476 Handle table rex_user not found in setup
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/sql/table.php
Labels: automerge

#4479 rex_form_element: Umgang mit Attributen korrigiert/optimiert
  redaxo/src/addons/users/lib/select_element.php
  redaxo/src/core/lib/form/config_form.php
  redaxo/src/core/lib/form/elements/container.php
  redaxo/src/core/lib/form/elements/element.php
  redaxo/src/core/lib/form/form.php
  redaxo/src/core/lib/form/form_base.php
Labels: automerge

#4483 rex_extension: Umgang mit $level-Param
  redaxo/src/core/lib/extension.php
Labels: automerge

#4482 "Report a bug" in neuem Tab öffnen
  redaxo/src/core/lib/error_handler.php
Labels: automerge

#4480 handle null values for string functions
  .tools/psalm/baseline.xml
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/users/lib/select_element.php
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#4489 Server-Timing-Header nicht mehr senden
  redaxo/src/core/lib/response.php
Labels: automerge

#4490 Setup: Schon bestehende DB-Verbindung schließen
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/pages/setup.php
Labels: automerge

#4491 rex_article_slice: Propertynamen korrigiert
  redaxo/src/addons/structure/plugins/content/lib/article_slice.php
Labels: automerge

#4496 Typo
  redaxo/src/addons/phpmailer/lang/de_de.lang
Labels: automerge

#4499 login page: fix border color
  .github/tests-visual/login.png
  .github/tests-visual/logout.png
  .github/tests-visual/phpmailer_config.png
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_login.scss
Labels: automerge

#4500 fix 'Exception: no error' when using empty/null keys in rex_i18n
  redaxo/src/core/lib/util/i18n.php
Labels: automerge

#4506 Autoloader: fix cache handling
  redaxo/src/core/functions/function_rex_other.php
  redaxo/src/core/lib/autoload.php
Labels: automerge

#4461 structure/content: added `rex_extension_point_slice_menu` extension-point
  redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php
  redaxo/src/addons/structure/plugins/content/lib/extension_point/slice_menu.php
Labels: Add to Docs, Structure, automerge
