Repository redaxo/redaxo, pull requests merged in 2021-01, with the labels that each got.

#4279 Help: externe support page markieren
  redaxo/src/core/pages/packages.help.php
Labels: Design / CSS, Developer Experience (DX), automerge

#4264 package CHANGELOG.md via neuer package help bereich zugänglich machen
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/pages/packages.changelog.php
  redaxo/src/core/pages/packages.details.php
  redaxo/src/core/pages/packages.help.php
  redaxo/src/core/pages/packages.license.php
  redaxo/src/core/pages/packages.php
Labels: automerge

#4268 Erneutes-Setup abbrechbar machen
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lib/exception.php
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/pages/setup.php
  redaxo/src/core/pages/setup.step1.php
  redaxo/src/core/pages/setup.step2.php
  redaxo/src/core/pages/setup.step3.php
  redaxo/src/core/pages/setup.step4.php
  redaxo/src/core/pages/setup.step5.php
  redaxo/src/core/pages/setup.step6.php
  redaxo/src/core/pages/setup.step7.php
Labels: Feature, Setup, automerge

#4275 Whoops: 'Report a bug' button hinzugefügt
  redaxo/src/core/lib/error_handler.php
Labels: Core, Developer Experience (DX), Enhancement, automerge

#4285 PhpStorm-Settings: Nicht existenten tests-Ordner entfernt
  .idea/redaxo.iml
Labels: automerge

#4284 media-manager: a system-types' name can no longer be changed
  redaxo/src/addons/media_manager/lib/media_manager.php
  redaxo/src/addons/media_manager/pages/types.php
Labels: automerge

#4286 Vendor updates
  composer.json
  redaxo/src/addons/debug/composer.lock
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Clockwork.php
  redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Support/Vanilla/Clockwork.php
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/InstalledVersions.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
Labels: automerge

#4270 setup: select 'database exists - skip' per default to be less destructive
  redaxo/src/core/lib/console/setup/run.php
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/pages/setup.step5.php
Labels: Console, Developer Experience (DX), Setup, automerge

#4289 UI: readonly input felder sollten nicht auf focus/hover reagieren
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_form.scss
Labels: User Experience (UX), automerge

#4246 UI: update user icon to show inactive users
  .github/tests-visual/users_edit.png
  redaxo/src/addons/be_style/assets/css/styles.css
  redaxo/src/addons/be_style/scss/_icon.scss
  redaxo/src/addons/users/lang/de_de.lang
  redaxo/src/addons/users/lang/en_gb.lang
  redaxo/src/addons/users/lang/es_es.lang
  redaxo/src/addons/users/lang/pt_br.lang
  redaxo/src/addons/users/lang/sv_se.lang
  redaxo/src/addons/users/pages/users.php
Labels: automerge

#4234 UI: improve alert styles within tables
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_tables.scss
Labels: automerge

#4233 UI: refresh sidebar navigation styles
  .github/tests-visual/backup_export.png
  .github/tests-visual/backup_import.png
  .github/tests-visual/cronjob_cronjobs.png
  .github/tests-visual/index.png
  .github/tests-visual/media_manager_settings.png
  .github/tests-visual/media_manager_types.png
  .github/tests-visual/media_manager_types_edit.png
  .github/tests-visual/metainfo_articles.png
  .github/tests-visual/metainfo_categories.png
  .github/tests-visual/metainfo_clangs.png
  .github/tests-visual/metainfo_media.png
  .github/tests-visual/modules_actions.png
  .github/tests-visual/modules_modules.png
  .github/tests-visual/packages.png
  .github/tests-visual/phpmailer_config.png
  .github/tests-visual/system_log.png
  .github/tests-visual/system_report.png
  .github/tests-visual/system_settings.png
  .github/tests-visual/templates.png
  .github/tests-visual/templates_edit.png
  .github/tests-visual/users_edit.png
  .github/tests-visual/users_role_add.png
  .github/tests-visual/users_roles.png
  .github/tests-visual/users_users.png
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_navs.scss
Labels: automerge

#4288 Setup: prevent fail2ban blocking
  redaxo/src/core/assets/standard.js
  redaxo/src/core/pages/setup.step3.php
Labels: automerge

#4235 UI: refresh tabs styles
  .github/tests-visual/backup_export.png
  .github/tests-visual/backup_import.png
  .github/tests-visual/cronjob_cronjobs.png
  .github/tests-visual/media_manager_settings.png
  .github/tests-visual/media_manager_types.png
  .github/tests-visual/media_manager_types_edit.png
  .github/tests-visual/mediapool_media.png
  .github/tests-visual/mediapool_structure.png
  .github/tests-visual/mediapool_sync.png
  .github/tests-visual/mediapool_upload.png
  .github/tests-visual/metainfo_articles.png
  .github/tests-visual/metainfo_categories.png
  .github/tests-visual/metainfo_clangs.png
  .github/tests-visual/metainfo_media.png
  .github/tests-visual/modules_actions.png
  .github/tests-visual/modules_modules.png
  .github/tests-visual/phpmailer_config.png
  .github/tests-visual/system_log.png
  .github/tests-visual/system_report.png
  .github/tests-visual/system_settings.png
  .github/tests-visual/users_edit.png
  .github/tests-visual/users_role_add.png
  .github/tests-visual/users_roles.png
  .github/tests-visual/users_users.png
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_navs.scss
Labels: automerge

#4251 UI: use generic rex-link to expand clickable areas
  redaxo/src/addons/backup/pages/import.server.php
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_typo.scss
  redaxo/src/addons/cronjob/pages/cronjobs.php
  redaxo/src/addons/install/pages/packages.add.php
  redaxo/src/addons/install/pages/packages.update.php
  redaxo/src/addons/install/pages/packages.upload.php
  redaxo/src/addons/mediapool/pages/media.list.php
  redaxo/src/addons/mediapool/pages/structure.php
  redaxo/src/addons/structure/functions/function_rex_category.php
  redaxo/src/addons/structure/pages/index.php
  redaxo/src/addons/structure/plugins/content/pages/modules.actions.php
  redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
  redaxo/src/addons/structure/plugins/content/pages/templates.php
  redaxo/src/addons/users/pages/roles.php
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/fragments/core/navigations/breadcrumb.php
  redaxo/src/core/lib/list.php
  redaxo/src/core/pages/packages.list.php
  redaxo/src/core/pages/system.clangs.php
  redaxo/src/core/pages/system.settings.php
Labels: Add to Docs, automerge

#4299 backup: 'compress' option im cronjob implementiert
  redaxo/src/addons/backup/lang/de_de.lang
  redaxo/src/addons/backup/lang/en_gb.lang
  redaxo/src/addons/backup/lib/compressor.php
  redaxo/src/addons/backup/lib/cronjob.php
Labels: Backup, Enhancement, automerge

#4297 Addons / Installer: Clear-Button to Searchfields
  .github/tests-visual/packages.png
  redaxo/src/addons/be_style/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_form.scss
  redaxo/src/addons/be_style/scss/_icon.scss
  redaxo/src/addons/install/lang/de_de.lang
  redaxo/src/addons/install/lang/en_gb.lang
  redaxo/src/addons/install/lang/es_es.lang
  redaxo/src/addons/install/lang/pt_br.lang
  redaxo/src/addons/install/lang/sv_se.lang
  redaxo/src/addons/install/pages/packages.add.php
  redaxo/src/core/assets/standard.js
  redaxo/src/core/fragments/core/form/search.php
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/sv_se.lang
  redaxo/src/core/pages/packages.list.php
Labels: automerge

#4298 be_style/customizer: color picker verwenden
  redaxo/src/addons/be_style/plugins/customizer/pages/system.customizer.php
Labels: Design / CSS, Developer Experience (DX), Enhancement, automerge

#4309 clear-button-fix input padding
  .github/tests-visual/backup_export.png
  .github/tests-visual/backup_import.png
  .github/tests-visual/cronjob_cronjobs.png
  .github/tests-visual/login.png
  .github/tests-visual/media_manager_settings.png
  .github/tests-visual/media_manager_types.png
  .github/tests-visual/media_manager_types_edit.png
  .github/tests-visual/mediapool_media.png
  .github/tests-visual/mediapool_structure.png
  .github/tests-visual/mediapool_sync.png
  .github/tests-visual/mediapool_upload.png
  .github/tests-visual/metainfo_articles.png
  .github/tests-visual/metainfo_categories.png
  .github/tests-visual/metainfo_clangs.png
  .github/tests-visual/metainfo_media.png
  .github/tests-visual/modules_actions.png
  .github/tests-visual/modules_modules.png
  .github/tests-visual/packages.png
  .github/tests-visual/phpmailer_config.png
  .github/tests-visual/system_log.png
  .github/tests-visual/system_report.png
  .github/tests-visual/system_settings.png
  .github/tests-visual/users_edit.png
  .github/tests-visual/users_role_add.png
  .github/tests-visual/users_roles.png
  .github/tests-visual/users_users.png
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_form.scss
Labels: automerge

#4310 system-log: add csrf protection
  redaxo/src/core/pages/system.log.redaxo.php
Labels: automerge

#4301 UI: update sidebar links on setup page
  .tools/phpstan/baseline.neon
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_navs.scss
  redaxo/src/core/layout/top.php
Labels: automerge

#4306 backup: support import of sql.gz files
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/backup/lib/compressor.php
  redaxo/src/addons/backup/pages/import.server.php
  redaxo/src/addons/backup/pages/import.upload.php
Labels: Backup, automerge

#4305 GitHub workflows: run visual tests with setup pages
  .github/tests-visual/backup_import_server.png
  .github/tests-visual/cronjob_cronjobs_add.png
  .github/tests-visual/login.png
  .github/tests-visual/media_manager_types_add.png
  .github/tests-visual/metainfo_articles_add.png
  .github/tests-visual/modules_actions_add.png
  .github/tests-visual/modules_modules_add.png
  .github/tests-visual/setup.png
  .github/tests-visual/setup_2.png
  .github/tests-visual/setup_3.png
  .github/tests-visual/setup_4.png
  .github/tests-visual/setup_5.png
  .github/tests-visual/setup_6.png
  .github/tests-visual/setup_7.png
  .github/tests-visual/system_lang.png
  .github/tests-visual/system_settings.png
  .github/tests-visual/templates_add.png
  .github/tests-visual/visual-record.js
  .github/workflows/visual-tests.yml
Labels: Contributor Experience, automerge

#4302 gh-actions: improve error message when compiled css was not commited
  .github/workflows/rexlint.yml
Labels: automerge

#4256 metainfo.css nur im 'content'-Bereich ausgeben
  redaxo/src/addons/metainfo/boot.php
Labels: Metainfo, automerge

#4303 UI: adjust font sizes and line heights
  .github/tests-visual/backup_export.png
  .github/tests-visual/backup_import.png
  .github/tests-visual/backup_import_server.png
  .github/tests-visual/cronjob_cronjobs.png
  .github/tests-visual/cronjob_cronjobs_add.png
  .github/tests-visual/index.png
  .github/tests-visual/login.png
  .github/tests-visual/media_manager_settings.png
  .github/tests-visual/media_manager_types.png
  .github/tests-visual/media_manager_types_add.png
  .github/tests-visual/media_manager_types_edit.png
  .github/tests-visual/mediapool_media.png
  .github/tests-visual/mediapool_structure.png
  .github/tests-visual/mediapool_sync.png
  .github/tests-visual/mediapool_upload.png
  .github/tests-visual/metainfo_articles.png
  .github/tests-visual/metainfo_articles_add.png
  .github/tests-visual/metainfo_categories.png
  .github/tests-visual/metainfo_clangs.png
  .github/tests-visual/metainfo_media.png
  .github/tests-visual/modules_actions.png
  .github/tests-visual/modules_actions_add.png
  .github/tests-visual/modules_modules.png
  .github/tests-visual/modules_modules_add.png
  .github/tests-visual/packages.png
  .github/tests-visual/phpmailer_config.png
  .github/tests-visual/setup.png
  .github/tests-visual/setup_2.png
  .github/tests-visual/setup_3.png
  .github/tests-visual/setup_4.png
  .github/tests-visual/setup_5.png
  .github/tests-visual/setup_6.png
  .github/tests-visual/setup_7.png
  .github/tests-visual/system_lang.png
  .github/tests-visual/system_log.png
  .github/tests-visual/system_report.png
  .github/tests-visual/system_settings.png
  .github/tests-visual/templates.png
  .github/tests-visual/templates_add.png
  .github/tests-visual/templates_edit.png
  .github/tests-visual/users_edit.png
  .github/tests-visual/users_role_add.png
  .github/tests-visual/users_roles.png
  .github/tests-visual/users_users.png
  redaxo/src/addons/be_style/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_variables.scss
Labels: automerge

#4318 Passwort-Manager taugliche Eingabe in User-Oberfläche
  redaxo/src/addons/users/pages/users.php
Labels: automerge

#4320 Install: Hervorhebung vom aktuellen Release und von Entwicklungsversionen
  .github/tests-visual/users_edit.png
  redaxo/src/addons/install/lang/de_de.lang
  redaxo/src/addons/install/pages/packages.add.php
  redaxo/src/addons/install/pages/packages.update.php
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/sv_se.lang
Labels: Installer, automerge

#4334 Safe-Mode: Deaktivieren-Button ohne PJAX
  redaxo/src/core/layout/top.php
Labels: automerge

#4344 rex_logger: rex_exceptions ohne Großbuchstabe vorne
  redaxo/src/core/lib/util/logger.php
Labels: automerge

#4342 Download-Links ohne PJAX, insbesondere bei Backups
  redaxo/src/addons/backup/pages/import.server.php
  redaxo/src/core/assets/standard.js
Labels: automerge

#4349 Auto commit compiled css files
  .github/workflows/rexlint.yml
  .github/workflows/styles-compile.yml
Labels: automerge

#4340 Visual tests: wait until `networkidle0` instead of `load` for setup steps
  .github/tests-visual/setup_4.png
  .github/tests-visual/visual-record.js
Labels: automerge

#4330 rex_response: Add httpStatus parameter to sendRedirect
  redaxo/src/core/lib/response.php
Labels: automerge

#4350 Server-Timings über einen einzigen Header
  redaxo/src/core/lib/response.php
Labels: automerge

#4316 Installer auch im Safe Mode verfügbar halten
  redaxo/src/core/default.config.yml
  redaxo/src/core/update.php
Labels: automerge

#4343 Nach Backup erstellen: Korrekte Felder einblenden
  redaxo/src/addons/backup/pages/export.php
Labels: automerge

#4345 Whoops: fix buttons
  redaxo/src/core/lib/error_handler.php
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Resources/js/whoops.base.js
Labels: automerge

#4337 UI: revert PJAX to 5.11 behaviour
  redaxo/src/addons/structure/plugins/content/package.yml
  redaxo/src/core/assets/standard.js
  redaxo/src/core/fragments/core/header.php
  redaxo/src/core/fragments/core/navigation.php
  redaxo/src/core/pages/system.log.redaxo.php
Labels: automerge

#4348 Setup: bei `CREATE DATABASE` als Collation `utf8mb4_unicode_ci` nutzen
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#4356 Update vendors
  composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
Labels: automerge

#4358 Added phpdoc
  redaxo/src/core/lib/sql/table.php
Labels: automerge

#4360 UI: update tabs inside panels
  .github/tests-visual/templates_add.png
  .github/tests-visual/templates_edit.png
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_navs.scss
Labels: automerge

#4361 UI: use word break for system log
  redaxo/src/addons/be_style/assets/css/styles.css
  redaxo/src/addons/be_style/scss/_helper.scss
  redaxo/src/core/pages/system.log.redaxo.php
Labels: automerge

#4352 UI: Revert to former jquery-pjax
  .tools/bin/update-all
  .tools/psalm/baseline.xml
  redaxo/src/core/assets/jquery-pjax.min.js
  redaxo/src/core/assets/pjax.min.js
  redaxo/src/core/assets/standard.js
  redaxo/src/core/backend.php
  redaxo/src/core/fragments/core/footer.php
  redaxo/src/core/layout/bottom.php
  redaxo/src/core/layout/top.php
  redaxo/src/core/lib/be/controller.php
  redaxo/src/core/lib/request.php
Labels: automerge

#4370 rex_vars: Ziffern im Namen erlauben
  redaxo/src/core/lib/var/var.php
  redaxo/src/core/tests/var/var_test.php
Labels: automerge

#4371 UI: setup wording
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/nl_nl.lang
  redaxo/src/core/lang/pt_br.lang
  redaxo/src/core/lang/sv_se.lang
Labels: automerge

#4373 Visual Tests: update step 7
  .github/tests-visual/setup_7.png
  .github/tests-visual/visual-record.js
Labels: automerge

#4375 Report a bug: strip multiple spaces
  redaxo/src/core/lib/error_handler.php
Labels: automerge

#4379 Update setup step 2: License
  .github/tests-visual/setup_2.png
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/it_it.lang
  redaxo/src/core/lang/nl_nl.lang
  redaxo/src/core/lang/pt_br.lang
  redaxo/src/core/lang/sv_se.lang
  redaxo/src/core/pages/setup.step2.php
Labels: Developer Experience (DX), Setup, User Experience (UX), automerge

#4380 remove unused code
  redaxo/src/core/backend.php
  redaxo/src/core/fragments/core/navigations/content.php
  redaxo/src/core/fragments/core/navigations/meta.php
  redaxo/src/core/lib/console/setup/run.php
  redaxo/src/core/lib/form/config_form.php
  redaxo/src/core/lib/form/elements/checkbox.php
  redaxo/src/core/lib/form/elements/container.php
  redaxo/src/core/lib/form/elements/element.php
  redaxo/src/core/lib/form/elements/radio.php
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/var_dumper.php
  redaxo/src/core/pages/packages.license.php
  redaxo/src/core/pages/packages.list.php
  redaxo/src/core/pages/profile.php
  redaxo/src/core/pages/system.log.external.php
Labels: automerge

#4384 Use rex-bot for actions
  .github/workflows/chatops.yml
  .github/workflows/cs-fix.yml
  .github/workflows/styles-compile.yml
  .github/workflows/visual-tests.yml
Labels: automerge

#4386 phpstan: disable treatPhpDocTypesAsCertain
  .tools/phpstan/baseline.neon
  phpstan.neon.dist
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#4382 rex_form: escape redirect url
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/lib/form/form_base.php
Labels: automerge

#4383 remove unused code
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/lib/form/elements/control.php
Labels: automerge

#4372 Erneutes Setup über URL-Token
  redaxo/src/core/layout/top.php
  redaxo/src/core/lib/console/setup/run.php
  redaxo/src/core/lib/rex.php
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/pages/setup.php
  redaxo/src/core/pages/system.settings.php
  redaxo/src/core/schemas/config.json
Labels: Add to Docs, automerge

#4387 Visual tests: add customizer
  .github/tests-visual/system_customizer.png
  .github/tests-visual/visual-record.js
  .github/workflows/visual-tests.yml
Labels: automerge

#4381 Mark exception output in cli as escaped
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/lib/error_handler.php
Labels: automerge
