Repository redaxo/redaxo, pull requests merged in 2022-07, with the labels that each got.

#5195 fixed method name case
  redaxo/src/addons/backup/lib/cronjob.php
Labels: automerge

#5196 extract `rex_backend_login->increaseLoginTries()`
  redaxo/src/core/lib/login/backend_login.php
Labels: automerge

#5199 autoload: cache löschen bei uncaught class-not-found errors
  redaxo/src/core/lib/error_handler.php
Labels: automerge

#5198 Mention available `password_policy` config.yml keys
  redaxo/src/core/default.config.yml
Labels: automerge

#5158 added rex_path::findBinaryPath()
  redaxo/src/core/lib/util/path.php
  redaxo/src/core/tests/path_test.php
Labels: automerge

#5197 config.yml: added `backend_login_policy`
  redaxo/src/core/default.config.yml
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/lib/login/login_policy.php
  redaxo/src/core/pages/login.php
  redaxo/src/core/schemas/config.json
  redaxo/src/core/tests/login/backend_login_test.php
Labels: Security, Core, automerge

#5204 remove attribute ignore rule
  composer.json
  phpstan.neon.dist
Labels: automerge

#5191 Ermöglichen von eigenen Attributen bei rex_form_base
  redaxo/src/core/lib/form/form_base.php
Labels: automerge

#5168 Neuer EP PACKAGE_CACHE_DELETED
  redaxo/src/core/lib/packages/ep_package_cache_deleted.php
  redaxo/src/core/lib/packages/package.php
Labels: automerge

#5208 added missing phpstorm settings
  .idea/php.xml
  .idea/redaxo.iml
Labels: automerge

#5209 timeout github actions after 5 minutes
  .github/workflows/chatops.yml
  .github/workflows/code-style.yml
  .github/workflows/remove-automerge-label.yml
  .github/workflows/rexlint.yml
  .github/workflows/sarif-report.yml
  .github/workflows/static-analysis.yml
  .github/workflows/styles-compile.yml
  .github/workflows/unit-tests.yml
  .github/workflows/visual-tests.yml
Labels: automerge

#5200 simplify `rex_login_policy`
  .tools/phpstan/baseline.neon
  phpstan.neon.dist
  redaxo/src/core/default.config.yml
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/lib/login/login_policy.php
  redaxo/src/core/schemas/config.json
  redaxo/src/core/tests/login/backend_login_test.php
Labels: Add to Docs, automerge

#5189 Hide sensitive information with SensitiveParameter attribute
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/addons/structure/plugins/history/lib/history_login.php
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/lib/login/login.php
  redaxo/src/core/lib/login/password_policy.php
  redaxo/src/core/lib/login/user.php
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#5212 Use GLOB_NOSORT
  redaxo/src/addons/mediapool/lib/cache_media.php
Labels: automerge

#5211 Use GLOB_NOSORT
  redaxo/src/addons/backup/lib/cronjob.php
Labels: automerge

#5213 simplify purgeMailarchive()
  redaxo/src/addons/phpmailer/lib/cronjob.php
Labels: automerge

#5214 use `config.yml` cookie settings for `rex_htaccess_check`-cookie
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/core/assets/standard.js
  redaxo/src/core/backend.php
  redaxo/src/core/lib/login/login.php
Labels: automerge

#5215 psalm-config bzgl. Attribute-Klassen aktualisiert
  .tools/psalm/baseline.xml
  psalm.xml
Labels: automerge

#5217 cronjob: increase log-limit to 100 errors
  redaxo/src/addons/cronjob/pages/log.php
Labels: automerge

#5216 fix debug addon when redaxo running in subfolder
  .tools/psalm/baseline.xml
  redaxo/src/addons/debug/boot.php
Labels: Debug, automerge

#5220 rex_var_template: Erläuterung für Fake-Param
  redaxo/src/addons/structure/plugins/content/lib/var_template.php
Labels: automerge

#5219 Oops-Seite bei Arbeitsversion-Voransicht
  redaxo/src/addons/structure/plugins/version/boot.php
Labels: automerge

#5221 version-plugin: fix type errors
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/addons/structure/plugins/content/lib/extension_point/art_content_updated.php
  redaxo/src/addons/structure/plugins/version/boot.php
  redaxo/src/addons/structure/plugins/version/lib/revision.php
Labels: automerge

#5222 Version-Plugin: Bei Kopieren zw. Live/Arbeitsv. in neue Version wechseln
  redaxo/src/addons/structure/plugins/version/boot.php
  redaxo/src/addons/structure/plugins/version/lib/revision.php
Labels: automerge

#5226 Fragment: Dynamische Properties vermeiden
  .tools/psalm/baseline.xml
  redaxo/src/core/fragments/core/page/grid.php
Labels: automerge

#5229 Rollen können dupliziert werden
  redaxo/src/addons/users/lang/de_de.lang
  redaxo/src/addons/users/lang/en_gb.lang
  redaxo/src/addons/users/pages/roles.php
Labels: automerge

#5231 Templates-Cache im korrekten Addon-Ordner
  redaxo/src/addons/structure/plugins/content/lib/api_template.php
  redaxo/src/addons/structure/plugins/content/lib/cache_template.php
Labels: automerge

#5233 Socket-Proxy: Host-Header ohne Port
  redaxo/src/core/lib/util/socket/socket_proxy.php
Labels: automerge

#5228 Cronjob-Verwaltung: Checkbox/Radio statt Selects
  .github/tests-visual/cronjob_cronjobs_add--dark.png
  .github/tests-visual/cronjob_cronjobs_add.png
  redaxo/src/addons/cronjob/pages/cronjobs.php
Labels: automerge

#5232 rex_form: Attribute für Fieldsets
  redaxo/src/core/lib/form/form_base.php
Labels: automerge

#5236 MM: Cache-Directory kann programmatisch geändert werden
  redaxo/src/addons/media_manager/lib/media_manager.php
Labels: automerge

#5239 rex_managed_media: getMediaFilename liefert einheitlich neuen Dateinamen
  redaxo/src/addons/media_manager/lib/managed_media.php
  redaxo/src/addons/media_manager/lib/media_manager.php
Labels: automerge

#5240 Visual tests: Bei Änderungen automerge-Label entfernen
  .github/workflows/visual-tests.yml
Labels: automerge

#5227 Cronjob-Command: Messages und Status ausgeben
  .tools/psalm/baseline.xml
  redaxo/src/addons/cronjob/lib/command/run.php
  redaxo/src/addons/cronjob/lib/manager_sql.php
Labels: automerge

#5235 Installer: Beim Upload automatisch git-Dateien ignorieren
  redaxo/src/addons/install/lib/api/api_package_upload.php
Labels: automerge

#5242 Login-Seite: Hintergrundbild und Styling
  .github/tests-visual/login--dark.png
  .github/tests-visual/login.png
  .github/tests-visual/logout--dark.png
  .github/tests-visual/logout.png
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/davide-cantelli-ajisKc2uuFk-unsplash_2100.avif
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/davide-cantelli-ajisKc2uuFk-unsplash_2100.jpg
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/davide-cantelli-ajisKc2uuFk-unsplash_3300.avif
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/davide-cantelli-ajisKc2uuFk-unsplash_3300.jpg
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/jr-korpa-9XngoIpxcEo-unsplash_2100.avif
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/jr-korpa-9XngoIpxcEo-unsplash_2100.jpg
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/jr-korpa-9XngoIpxcEo-unsplash_3300.avif
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/jr-korpa-9XngoIpxcEo-unsplash_3300.jpg
  redaxo/src/core/fragments/core/login_background.php
Labels: automerge

#5251 slowQueryLogPath() returns a taint-safe file
  .tools/psalm/baseline-taint.xml
  redaxo/src/core/lib/sql/util.php
Labels: automerge

#5252 support composer taint-baseline on windows
  composer.json
Labels: Core, Developer Experience (DX), automerge

#5253 Login-Seite: Hintergrundbild und Styling
  .github/tests-visual/login--dark.png
  .github/tests-visual/login.png
  .github/tests-visual/logout--dark.png
  .github/tests-visual/logout.png
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/davide-cantelli-ajisKc2uuFk-unsplash_2100.avif
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/davide-cantelli-ajisKc2uuFk-unsplash_2100.jpg
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/davide-cantelli-ajisKc2uuFk-unsplash_3300.avif
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/davide-cantelli-ajisKc2uuFk-unsplash_3300.jpg
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/dynamic-wang-EHnrP9CanuQ-unsplash_2400.avif
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/dynamic-wang-EHnrP9CanuQ-unsplash_2400.jpg
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/dynamic-wang-EHnrP9CanuQ-unsplash_3600.avif
  redaxo/src/addons/be_style/plugins/redaxo/assets/images/dynamic-wang-EHnrP9CanuQ-unsplash_3600.jpg
  redaxo/src/core/fragments/core/login_background.php
Labels: automerge

#5255 Slow Query Log: DB-Abfragen vermeiden
  redaxo/src/core/backend.php
  redaxo/src/core/lib/be/controller.php
Labels: automerge

#5258 Übersetzung korrigiert
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/sv_se.lang
Labels: automerge

#5257 Passwortregeln als HTML-Attribute
  redaxo/src/addons/users/package.yml
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/lib/login/password_policy.php
  redaxo/src/core/pages/profile.php
  redaxo/src/core/pages/setup.step5.php
  redaxo/src/core/tests/login/password_policy_test.php
Labels: automerge

#5260 Visual tests: remove timeouts
  .github/tests-visual/visual-record.js
Labels: automerge

#5262 update rector to 0.13.9
  .tools/phpstan/baseline.neon
  composer.json
Labels: automerge

#5202 declare `rex::getProperty()` conditional return types
  .idea/inspectionProfiles/Project_Default.xml
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/console/config/get.php
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/lib/rex.php
  redaxo/src/core/lib/util/editor.php
Labels: automerge

#5263 cs
  redaxo/src/core/lib/packages/package.php
Labels: automerge

#5264 Update tools
  composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
Labels: automerge

#5269 Fix für Configaufruf bei setStayLoggedInCookie
  redaxo/src/core/lib/login/backend_login.php
Labels: automerge

#5273 docs
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/addons/structure/functions/function_rex_url.php
  redaxo/src/addons/structure/lib/linkmap/form_element/linklist.php
  redaxo/src/addons/structure/lib/linkmap/form_element/linkmap.php
  redaxo/src/addons/structure/lib/linkmap/linkmap.php
  redaxo/src/addons/structure/lib/linkmap/renderer.php
  redaxo/src/addons/structure/lib/linkmap/sitemap.php
  redaxo/src/core/lib/sql/sql.php
Labels: automerge
