Repository redaxo/redaxo, pull requests merged in 2022-01, with the labels that each got.

#4992 Cli-Setup: Warnung, dass Checks nur die Cli-Umgebung prüfen
  redaxo/src/core/lib/console/setup/run.php
Labels: automerge

#4993 Cmd-Help: Dynamische Pfade nutzen
  redaxo/src/core/lib/console/assets_sync.php
Labels: automerge

#4983 setup_security_msg (unsichere Ordner) optimiert
  .github/tests-visual/setup_3--dark.png
  .github/tests-visual/setup_3.png
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/nl_nl.lang
  redaxo/src/core/lang/pt_br.lang
  redaxo/src/core/lang/sv_se.lang
Labels: automerge

#4994 phpdoc improvements
  redaxo/src/core/lib/rex.php
Labels: automerge

#5002 Deprecated: trim(): Passing null to parameter 1 ($string) of type string is deprecated
  redaxo/src/addons/users/lib/role.php
Labels: automerge

#5000 rex_sql: Params mit korrektem Typ binden
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/tests/sql/sql_select_test.php
Labels: automerge

#4996 Fehler optimiert, wenn kein Artikel vorhanden oder Artikel nicht gefunden
  redaxo/src/addons/structure/plugins/content/boot.php
Labels: automerge

#5004 [PHP 8.2] rex_stream: fix deprecation
  redaxo/src/core/lib/util/stream.php
Labels: automerge

#5005 use ramsey/composer-install@v2
  .github/workflows/code-style.yml
  .github/workflows/rexlint.yml
  .github/workflows/sarif-report.yml
  .github/workflows/static-analysis.yml
  .github/workflows/unit-tests.yml
Labels: automerge

#5006 phpstorm-settings aktualisiert
  .idea/codeStyles/Project.xml
  .idea/redaxo.iml
  phpunit.xml.dist
Labels: automerge

#4999 category2article: catname und catpriority aktualisieren
  redaxo/src/addons/structure/lib/service_article.php
Labels: automerge

#5001 bootstrap-select: Text "Bitte wählen" ersetzt mit "—"
  .github/tests-visual/cronjob_cronjobs_add--dark.png
  .github/tests-visual/cronjob_cronjobs_add.png
  .github/tests-visual/users_edit--dark.png
  .github/tests-visual/users_edit.png
  redaxo/src/addons/be_style/assets/javascripts/main.js
Labels: automerge

#4998 Inhalte von/zu Sprache kopieren: auch Arbeitsversion
  .tools/psalm/baseline.xml
  redaxo/src/addons/structure/plugins/content/lib/api_functions/api_content_copy.php
  redaxo/src/addons/structure/plugins/content/lib/content_service.php
Labels: automerge

#4997 Artikel-Funktionen: Version-Toolbar nicht anzeigen
  .github/tests-visual/structure_article_functions--dark.png
  .github/tests-visual/structure_article_functions.png
  redaxo/src/addons/structure/plugins/version/boot.php
Labels: automerge

#4995 structure: Default-Config hinterlegen
  redaxo/src/addons/structure/package.yml
Labels: automerge

#5013 Metainfo: Date-Felder: Checkbox-Status korrigiert
  redaxo/src/addons/metainfo/lib/handler/handler.php
Labels: automerge

#5016 MP: Alte Funktionen wieder kompatibel zu 5.12
  .tools/psalm/baseline.xml
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
Labels: automerge

#5014 "Eingeloggt bleiben" repariert
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/login/backend_login.php
Labels: Bug, automerge

#5017 Update vendors
  .tools/psalm/baseline-taint.xml
  .tools/psalm/baseline.xml
  composer.json
  phpstan.neon.dist
  psalm.xml
  redaxo/src/addons/be_style/assets/css/styles.css
  redaxo/src/addons/be_style/composer.lock
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/composer.json
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Base/Range.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Block.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Block/AtRootBlock.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Block/CallableBlock.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Block/ContentBlock.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Block/DirectiveBlock.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Block/EachBlock.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Block/ElseBlock.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Block/ElseifBlock.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Block/ForBlock.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Block/IfBlock.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Block/MediaBlock.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Block/NestedPropertyBlock.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Block/WhileBlock.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Colors.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Compiler.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Compiler/Environment.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/Compressed.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/Nested.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Formatter/OutputBlock.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Node.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Node/Number.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Parser.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/SourceMap/Base64.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/SourceMap/Base64VLQ.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/SourceMap/SourceMapGenerator.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Type.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Util.php
  redaxo/src/addons/be_style/vendor/scssphp/scssphp/src/Version.php
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php
  redaxo/src/core/vendor/symfony/polyfill-php80/Resources/stubs/UnhandledMatchError.php
  redaxo/src/core/vendor/symfony/polyfill-php80/Resources/stubs/ValueError.php
  redaxo/src/core/vendor/symfony/polyfill-php81/Php81.php
  redaxo/src/core/vendor/symfony/polyfill-php81/Resources/stubs/ReturnTypeWillChange.php
Labels: automerge

#5018 Fehlende Package-Page: Fehlermeldung optimiert
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/packages/package.php
Labels: automerge

#5024 phpstan: remove bleeding edge mode
  phpstan.neon.dist
Labels: automerge

#5022 MP: Standardsortierung nach Updatedate
  redaxo/src/addons/mediapool/lib/service_media.php
Labels: automerge

#5023 Attribute für getColumnLink korrigiert
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/list.php
Labels: automerge

#5033 Use prepared Statement in media_handler
  .tools/psalm/baseline.xml
  redaxo/src/addons/metainfo/lib/handler/media_handler.php
Labels: automerge

#5029 PHPMailer :: Absender der Errormail
  redaxo/src/addons/phpmailer/lib/mailer.php
Labels: PHPMailer, automerge

#5030 manager-sql: added typehints
  .tools/psalm/baseline.xml
  redaxo/src/addons/cronjob/lib/manager_sql.php
Labels: automerge

#5031 Phpdocs
  .tools/psalm/baseline.xml
  redaxo/src/addons/structure/plugins/history/lib/article_slice_history.php
Labels: automerge

#5032 Phpdocs
  .tools/psalm/baseline.xml
  redaxo/src/addons/structure/plugins/version/lib/revision.php
Labels: automerge

#5034 added phpdocs
  .tools/psalm/baseline.xml
  redaxo/src/addons/metainfo/functions/function_metainfo.php
Labels: automerge

#5035 backup: improve error message on `opendir()` errors
  redaxo/src/addons/backup/lib/backup.php
Labels: Backup, automerge
