Repository redaxo/redaxo, pull requests merged in 2022-08, with the labels that each got.

#5276 Version-Plugin: Session-Variable korrigiert
  redaxo/src/addons/structure/plugins/version/lib/revision.php
Labels: automerge

#5279 mark `rex_sql::getRows()` as impure
  .tools/phpstan/baseline.neon
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#5272 rex_sql: Immer über prepare/execute gehen
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/tests/sql/sql_select_test.php
Labels: Bug

#5287 scss-compiler: use non-zero exit code on Exception
  redaxo/src/addons/be_style/lib/scss_compiler.php
Labels: automerge

#5289 phpstan return types Core-Addon metainfo
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/addons/metainfo/extensions/extension_cleanup.php
  redaxo/src/addons/metainfo/functions/function_metainfo.php
  redaxo/src/addons/metainfo/lib/handler/category_handler.php
  redaxo/src/addons/metainfo/lib/handler/clang_handler.php
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/metainfo/lib/input.php
  redaxo/src/addons/metainfo/lib/input/date.php
  redaxo/src/addons/metainfo/lib/input/datetime.php
  redaxo/src/addons/metainfo/lib/input/linkbutton.php
  redaxo/src/addons/metainfo/lib/input/linklistbutton.php
  redaxo/src/addons/metainfo/lib/input/mediabutton.php
  redaxo/src/addons/metainfo/lib/input/medialistbutton.php
  redaxo/src/addons/metainfo/lib/input/select.php
  redaxo/src/addons/metainfo/lib/input/time.php
  redaxo/src/addons/metainfo/lib/table_manager.php
  redaxo/src/core/lib/form/form_base.php
Labels: automerge

#5288 phpstan return types Core-Addon backup, be_style, install, media_manager, mediapool
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/backup/lib/tar.php
  redaxo/src/addons/be_style/lib/be_style.php
  redaxo/src/addons/be_style/lib/command/compile.php
  redaxo/src/addons/be_style/lib/scss_compiler.php
  redaxo/src/addons/install/lib/api/api_core_update.php
  redaxo/src/addons/install/lib/archive.php
  redaxo/src/addons/install/lib/command/download.php
  redaxo/src/addons/install/lib/command/list.php
  redaxo/src/addons/install/lib/command/update.php
  redaxo/src/addons/install/lib/package/package_download.php
  redaxo/src/addons/install/lib/packages.php
  redaxo/src/addons/install/lib/webservice.php
  redaxo/src/addons/media_manager/lib/effect_abstract.php
  redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
  redaxo/src/addons/media_manager/lib/effects/effect_resize.php
  redaxo/src/addons/media_manager/lib/managed_media.php
  redaxo/src/addons/media_manager/lib/media_manager.php
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
  redaxo/src/addons/mediapool/lib/cache_media.php
  redaxo/src/addons/mediapool/lib/form_element/media.php
  redaxo/src/addons/mediapool/lib/form_element/medialist.php
  redaxo/src/addons/mediapool/lib/media.php
  redaxo/src/addons/mediapool/lib/media_category_select.php
Labels: automerge

#5290 phpstan return types Core-Addon phpmailer, structure, users, debug, cronjob
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/addons/cronjob/lib/command/run.php
  redaxo/src/addons/cronjob/lib/cronjob.php
  redaxo/src/addons/cronjob/lib/manager.php
  redaxo/src/addons/cronjob/lib/manager_sql.php
  redaxo/src/addons/debug/lib/debug_clockwork.php
  redaxo/src/addons/debug/lib/extensions/api_function_debug.php
  redaxo/src/addons/phpmailer/lib/mailer.php
  redaxo/src/addons/structure/lib/navigation.php
  redaxo/src/addons/structure/lib/select_category.php
  redaxo/src/addons/structure/lib/service_article.php
  redaxo/src/addons/structure/lib/service_category.php
  redaxo/src/addons/structure/lib/structure_element.php
  redaxo/src/addons/structure/lib/var_article.php
  redaxo/src/addons/structure/lib/var_category.php
  redaxo/src/addons/structure/plugins/content/lib/api_template.php
  redaxo/src/addons/structure/plugins/content/lib/article_action.php
  redaxo/src/addons/structure/plugins/content/lib/article_content.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
  redaxo/src/addons/structure/plugins/content/lib/content_service.php
  redaxo/src/addons/structure/plugins/content/lib/select_template.php
  redaxo/src/addons/structure/plugins/history/lib/article_slice_history.php
  redaxo/src/addons/structure/plugins/history/lib/history_login.php
  redaxo/src/addons/users/lib/role.php
  redaxo/src/addons/users/lib/select_element.php
  redaxo/src/core/lib/api_function.php
  redaxo/src/core/lib/extension.php
  redaxo/src/core/lib/form/elements/element.php
  redaxo/src/core/lib/login/role.php
Labels: automerge

#5291 Rector: InlineSimplePropertyAnnotationRector nutzen
  rector.php
  redaxo/src/addons/backup/lib/tar.php
  redaxo/src/addons/install/lib/package/package_update.php
  redaxo/src/addons/install/lib/packages.php
  redaxo/src/addons/media_manager/lib/effect_abstract.php
  redaxo/src/addons/mediapool/lib/media_category_select.php
  redaxo/src/addons/structure/lib/linkmap/form_element/linklist.php
  redaxo/src/addons/structure/lib/linkmap/form_element/linkmap.php
  redaxo/src/addons/structure/lib/linkmap/linkmap.php
  redaxo/src/addons/structure/lib/linkmap/sitemap.php
  redaxo/src/addons/structure/lib/select_category.php
  redaxo/src/addons/structure/lib/structure_context.php
  redaxo/src/addons/structure/plugins/content/lib/api_module.php
  redaxo/src/addons/structure/plugins/content/lib/api_template.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
  redaxo/src/addons/structure/plugins/content/lib/extension_point/slice_menu.php
  redaxo/src/addons/structure/plugins/content/lib/select_template.php
  redaxo/src/core/lib/autoload.php
  redaxo/src/core/lib/base/factory_trait.php
  redaxo/src/core/lib/be/controller.php
  redaxo/src/core/lib/be/page_main.php
  redaxo/src/core/lib/clang/clang.php
  redaxo/src/core/lib/config_db.php
  redaxo/src/core/lib/context.php
  redaxo/src/core/lib/csrf_token.php
  redaxo/src/core/lib/exception.php
  redaxo/src/core/lib/form/elements/control.php
  redaxo/src/core/lib/list.php
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/lib/login/login.php
  redaxo/src/core/lib/login/password_policy.php
  redaxo/src/core/lib/login/user.php
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/lib/util/i18n.php
  redaxo/src/core/lib/util/logger.php
  redaxo/src/core/lib/util/pager.php
  redaxo/src/core/lib/util/path.php
  redaxo/src/core/lib/util/path_default_provider.php
  redaxo/src/core/lib/util/socket/socket_proxy.php
  redaxo/src/core/lib/util/validation_rule.php
Labels: automerge

#5278 fix phpstan errors
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/addons/structure/pages/index.php
  redaxo/src/addons/structure/plugins/content/fragments/module_select.php
  redaxo/src/addons/structure/plugins/content/pages/modules.actions.php
  redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
  redaxo/src/core/lib/api_function.php
  redaxo/src/core/lib/rex.php
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#5300 version-Plugin: bei work_to_live neue Revision vor EP setzen
  redaxo/src/addons/structure/plugins/version/boot.php
Labels: Add to Docs, automerge, FOR :: Tricks

#5302 Update versions
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/plugins/content/package.yml
  redaxo/src/addons/structure/plugins/history/package.yml
  redaxo/src/addons/structure/plugins/version/package.yml
  redaxo/src/core/boot.php
Labels: automerge

#5295 use php 8.2 in visual tests
  .github/workflows/visual-tests.yml
Labels: automerge

#5283 introduce `rex_login::SESSION_*` constants
  .tools/psalm/baseline.xml
  redaxo/src/addons/structure/plugins/history/lib/history_login.php
  redaxo/src/addons/structure/plugins/history/package.yml
  redaxo/src/core/boot.php
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/lib/login/login.php
Labels: automerge

#5308 Change default truncate ellipsis ... to typo char …
  redaxo/src/core/lib/util/formatter.php
Labels: automerge

#5303 version-plugin: Konstanten nutzen
  .tools/phpstan/baseline.neon
  redaxo/src/addons/structure/plugins/version/boot.php
  redaxo/src/addons/structure/plugins/version/lib/revision.php
Labels: automerge

#5284 rex_login: kill session after at max `session_max_overall_duration` seconds
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/core/default.config.yml
  redaxo/src/core/lib/login/login.php
  redaxo/src/core/schemas/config.json
  redaxo/src/core/tests/login/backend_login_test.php
Labels: automerge

#5305 phpstan return types Core
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/core/functions/function_rex_globals.php
  redaxo/src/core/lib/api_function.php
  redaxo/src/core/lib/autoload.php
  redaxo/src/core/lib/base/factory_trait.php
  redaxo/src/core/lib/base/instance_list_pool_trait.php
  redaxo/src/core/lib/base/instance_pool_trait.php
  redaxo/src/core/lib/be/controller.php
  redaxo/src/core/lib/be/navigation.php
  redaxo/src/core/lib/be/page.php
  redaxo/src/core/lib/clang/clang.php
  redaxo/src/core/lib/clang/service.php
  redaxo/src/core/lib/config.php
  redaxo/src/core/lib/console/application.php
  redaxo/src/core/lib/console/cache/clear.php
  redaxo/src/core/lib/context.php
  redaxo/src/core/lib/csrf_token.php
  redaxo/src/core/lib/error_handler.php
  redaxo/src/core/lib/extension_point.php
  redaxo/src/core/lib/form/elements/container.php
  redaxo/src/core/lib/form/elements/control.php
  redaxo/src/core/lib/form/elements/element.php
  redaxo/src/core/lib/form/elements/options.php
  redaxo/src/core/lib/form/elements/prio.php
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/packages/interface.php
  redaxo/src/core/lib/packages/null.php
  redaxo/src/core/lib/request.php
  redaxo/src/core/lib/util/log_file.php
  redaxo/src/core/lib/util/path.php
  redaxo/src/core/lib/util/socket/socket.php
  redaxo/src/core/lib/util/stream.php
  redaxo/src/core/lib/util/timer.php
  redaxo/src/core/lib/util/url.php
  redaxo/src/core/lib/var/var.php
  redaxo/src/core/lib/var_dumper.php
  redaxo/src/core/lib/view.php
Labels: automerge

#5306 phpstan return type core 2
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/error_handler.php
  redaxo/src/core/lib/form/elements/element.php
  redaxo/src/core/lib/form/elements/select.php
  redaxo/src/core/lib/form/form.php
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/fragment.php
  redaxo/src/core/lib/list.php
  redaxo/src/core/lib/packages/addons/addon.php
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/lib/packages/package.php
  redaxo/src/core/lib/response.php
  redaxo/src/core/lib/rex.php
  redaxo/src/core/lib/select.php
  redaxo/src/core/lib/setup/import.php
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/lib/sql/schema_dumper.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/sql/table.php
  redaxo/src/core/lib/sql/util.php
  redaxo/src/core/lib/system_report.php
  redaxo/src/core/lib/system_setting.php
  redaxo/src/core/lib/util/i18n.php
  redaxo/src/core/lib/util/logger.php
  redaxo/src/core/lib/util/markdown.php
  redaxo/src/core/lib/util/pager.php
Labels: automerge

#5310 More Phpdocs
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/addons/be_style/lib/scss_compiler.php
  redaxo/src/addons/mediapool/lib/form_element/media.php
  redaxo/src/addons/mediapool/lib/form_element/medialist.php
  redaxo/src/addons/metainfo/lib/restrictions_element.php
  redaxo/src/addons/structure/lib/linkmap/form_element/linklist.php
  redaxo/src/addons/structure/lib/linkmap/form_element/linkmap.php
  redaxo/src/addons/structure/lib/select_category.php
  redaxo/src/addons/structure/lib/structure_element.php
  redaxo/src/addons/structure/lib/system_setting_article_id.php
  redaxo/src/core/lib/be/page.php
  redaxo/src/core/lib/console/command_loader.php
  redaxo/src/core/lib/console/extension_point_console_shutdown.php
  redaxo/src/core/lib/console/setup/run.php
  redaxo/src/core/lib/context.php
  redaxo/src/core/lib/error_handler.php
  redaxo/src/core/lib/form/elements/checkbox.php
  redaxo/src/core/lib/form/elements/container.php
  redaxo/src/core/lib/form/elements/element.php
  redaxo/src/core/lib/form/elements/options.php
  redaxo/src/core/lib/form/elements/prio.php
  redaxo/src/core/lib/form/elements/radio.php
  redaxo/src/core/lib/form/elements/raw.php
  redaxo/src/core/lib/form/elements/select.php
  redaxo/src/core/lib/util/finder.php
  redaxo/src/core/lib/util/markdown.php
  redaxo/src/core/lib/util/socket/socket.php
  redaxo/src/core/lib/util/sortable_iterator.php
Labels: automerge

#5321 PHPMailer: archiving not sent mails with prefix not_sent
  redaxo/src/addons/phpmailer/lib/mailer.php
Labels: PHPMailer, Add to Docs, automerge

#5322 PHPMailer: Readme Ergänzung zu Logging und Archiv-Funkion
  redaxo/src/addons/phpmailer/README.de.md
  redaxo/src/addons/phpmailer/README.md
Labels: PHPMailer, automerge

#5324 fix: form-control-clear styles
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_panels.scss
Labels: automerge
