Repository redaxo/redaxo, pull requests merged in 2022-03, with the labels that each got.

#5062 Package-Klassen: Genauere Typen
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/packages/addons/addon.php
  redaxo/src/core/lib/packages/addons/interface.php
  redaxo/src/core/lib/packages/interface.php
  redaxo/src/core/lib/packages/package.php
  redaxo/src/core/lib/packages/plugins/plugin.php
Labels: automerge

#5063 rector: Eigene Rules korrigiert/optimiert
  .tools/rector/Rule/UnderscoreToCamelCasePropertyNameRector.php
  .tools/rector/Rule/UnderscoreToCamelCaseVariableNameRector.php
  .tools/rector/Util/UnderscoreCamelCaseConflictingNameGuard.php
  .tools/rector/Util/UnderscoreCamelCasePropertyRenamer.php
  redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
  redaxo/src/core/lib/be/controller.php
  redaxo/src/core/lib/packages/package.php
Labels: automerge

#5072 Komprimierte Backups auch löschen + .gz
  redaxo/src/addons/backup/lib/cronjob.php
Labels: automerge

#5077 rex_context: Neue zusätzliche Methoden
  redaxo/src/core/lib/context.php
Labels: automerge

#5080 Version 5.14.0-dev
  redaxo/src/core/boot.php
Labels: automerge

#5081 Dev-Versionen
  redaxo/src/addons/backup/package.yml
  redaxo/src/addons/be_style/package.yml
  redaxo/src/addons/debug/package.yml
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/addons/mediapool/package.yml
  redaxo/src/addons/metainfo/package.yml
  redaxo/src/addons/phpmailer/package.yml
  redaxo/src/addons/structure/package.yml
  redaxo/src/addons/structure/plugins/content/package.yml
  redaxo/src/addons/structure/plugins/history/package.yml
  redaxo/src/core/boot.php
Labels: automerge

#3527 medienpool: natives lazy loading verwenden
  redaxo/src/addons/mediapool/assets/lazysizes.min.js
  redaxo/src/addons/mediapool/boot.php
  redaxo/src/addons/mediapool/package.yml
  redaxo/src/addons/mediapool/pages/media.list.php
Labels: Enhancement, Mediapool, automerge

#5075 Eigene Assertion-Methoden
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/api_function.php
  redaxo/src/core/lib/console/setup/run.php
  redaxo/src/core/lib/error_handler.php
  redaxo/src/core/lib/form/elements/container.php
  redaxo/src/core/lib/fragment.php
  redaxo/src/core/lib/login/backend_password_policy.php
  redaxo/src/core/lib/rex.php
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/sql/table.php
  redaxo/src/core/lib/util/type.php
Labels: automerge

#5070 rex_sql: only connect to database when needed
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/tests/sql/sql_test.php
Labels: automerge

#5082 Neue Methode zum ändern eines BE-Seiten-Titels
  redaxo/src/core/lib/be/page.php
Labels: automerge

#5025 JS-Level Darkmode detector
  redaxo/src/addons/be_style/plugins/redaxo/assets/javascripts/redaxo.js
  redaxo/src/addons/be_style/plugins/redaxo/boot.php
Labels: Developer Experience (DX), automerge
