Repository redaxo/redaxo, pull requests merged in 2022-10, with the labels that each got.

#5346 added `@phpstandba-inference-placeholder` to `rex::getTablePrefix()`
  redaxo/src/core/lib/rex.php
Labels: automerge

#5349 added `@phpstandba-inference-placeholder` to `rex_article_slice_history::getTablePrefix()`
  redaxo/src/addons/structure/plugins/history/lib/article_slice_history.php
Labels: automerge

#5352 escapeLikeWildcards: Backslash auch escapen
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/tests/sql/sql_test.php
Labels: Bug, automerge

#5353 define more taint-sinks in rex_sql
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#5357 remove no longer relevant `function_exists('ImageCreateTrueColor')`
  .tools/psalm/baseline.xml
  redaxo/src/addons/media_manager/lib/effects/effect_crop.php
  redaxo/src/addons/media_manager/lib/effects/effect_resize.php
Labels: automerge

#5358 removed useless `isset` calls
  redaxo/src/addons/media_manager/lib/effects/effect_mirror.php
  redaxo/src/addons/media_manager/lib/effects/effect_workspace.php
Labels: automerge

#5355 remove magic values, use constants instead
  redaxo/src/addons/metainfo/install.php
  redaxo/src/addons/metainfo/lib/default_type.php
  redaxo/src/addons/metainfo/lib/handler/media_handler.php
Labels: automerge

#5359 removed always true condition
  .tools/phpstan/baseline.neon
  redaxo/src/addons/mediapool/lib/media_category_select.php
  redaxo/src/addons/structure/lib/select_category.php
Labels: automerge

#5363 Install AddOn: AddOns und Plugins installieren #903
  redaxo/src/addons/install/lang/de_de.lang
  redaxo/src/addons/install/lang/en_gb.lang
  redaxo/src/addons/install/lang/es_es.lang
  redaxo/src/addons/install/lang/pt_br.lang
  redaxo/src/addons/install/lang/sv_se.lang
  redaxo/src/addons/install/lib/api/api_package_add.php
Labels: automerge

#5356 added sql escaping
  .tools/psalm/baseline.xml
  redaxo/src/addons/cronjob/plugins/article_status/lib/cronjob.php
  redaxo/src/addons/mediapool/assets/mediapool.js
  redaxo/src/addons/metainfo/lib/table_expander.php
  redaxo/src/addons/metainfo/pages/content.metainfo.php
  redaxo/src/addons/structure/plugins/content/boot.php
  redaxo/src/addons/structure/plugins/content/lib/article_slice.php
  redaxo/src/addons/structure/plugins/history/lib/article_slice_history.php
  redaxo/src/core/assets/standard.js
Labels: automerge

#5339 Log active user sessions to database
  .github/tests-visual/backup_export--dark.png
  .github/tests-visual/backup_export.png
  .tools/psalm/baseline.xml
  redaxo/src/addons/backup/pages/export.php
  redaxo/src/core/install.php
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/lib/login/login.php
  redaxo/src/core/lib/login/user_session.php
  redaxo/src/core/pages/profile.php
  redaxo/src/core/pages/profile.sessions.php
Labels: automerge

#5368 Backend User Session Remove
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lib/login/user_session.php
  redaxo/src/core/pages/profile.php
  redaxo/src/core/pages/profile.sessions.php
Labels: automerge

#5371 prevent user from removing the current backend session
  redaxo/src/core/pages/profile.sessions.php
Labels: automerge

#5361 PHPMailer :: Neue EPs PHPMAILER_PRE_SEND + PHPMAILER_POST_SEND
  redaxo/src/addons/phpmailer/lib/mailer.php
Labels: PHPMailer, automerge

#5372 remove unused param & proper naming
  .tools/phpstan/baseline.neon
  redaxo/src/addons/install/lib/package/package_add.php
  redaxo/src/addons/install/lib/packages.php
Labels: Installer, automerge

#5375 Session-Liste: intlDateTime nutzen
  redaxo/src/core/pages/profile.sessions.php
Labels: automerge

#5374 Fremdschlüssel für rex_user_session
  redaxo/src/core/install.php
  redaxo/src/core/lib/setup/import.php
Labels: Core, automerge

#5377 replace `rex::getUser()` with `rex::requireUser()`
  .tools/psalm/baseline.xml
  redaxo/src/addons/users/pages/users.php
Labels: automerge

#5362 Markierungsfarbe in AddOn-Tabelle nach Installer-Download
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_tables.scss
Labels: automerge

#5379 fix jetbrains php deprecation annotation
  redaxo/src/core/lib/rex.php
  redaxo/src/core/lib/util/string.php
Labels: automerge

#5370 prevent admin-user modification by non-admin
  redaxo/src/addons/users/pages/users.php
Labels: Security, Users, automerge

#5381 Vendor-Updates
  .tools/psalm/baseline-taint.xml
  .tools/psalm/baseline.xml
  composer.json
  redaxo/src/addons/phpmailer/composer.json
  redaxo/src/addons/phpmailer/composer.lock
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/VERSION
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/composer.json
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/language/phpmailer.lang-da.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/language/phpmailer.lang-pl.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/PHPMailer.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/POP3.php
  redaxo/src/addons/phpmailer/vendor/phpmailer/phpmailer/src/SMTP.php
  redaxo/src/core/composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
  redaxo/src/core/vendor/symfony/console/Helper/Helper.php
  redaxo/src/core/vendor/symfony/http-foundation/BinaryFileResponse.php
  redaxo/src/core/vendor/symfony/string/Resources/data/wcswidth_table_wide.php
  redaxo/src/core/vendor/symfony/string/Resources/data/wcswidth_table_zero.php
  redaxo/src/core/vendor/voku/portable-utf8/src/voku/helper/UTF8.php
Labels: automerge

#5373 remove user sessions if the password has changed
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/lib/login/user_session.php
Labels: automerge

#5376 Optimize user-session handling
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/lib/login/user_session.php
  redaxo/src/core/update.php
Labels: automerge

#5365 Installer - Veröffentlicht am Datum bei den Updates ausgeben
  redaxo/src/addons/install/pages/packages.update.php
Labels: automerge
