Repository redaxo/redaxo, pull requests merged in 2022-04, with the labels that each got.

#5086 Ausgabe der Rollen in Benutzerliste angepasst
  .github/tests-visual/users_users--dark.png
  .github/tests-visual/users_users.png
  redaxo/src/addons/be_style/plugins/redaxo/assets/css/styles.css
  redaxo/src/addons/be_style/plugins/redaxo/scss/_docs.scss
  redaxo/src/addons/users/pages/users.php
Labels: automerge

#5098 rex_formatter : move 0000-00-00 handling
  redaxo/src/core/lib/util/formatter.php
Labels: automerge

#5099 Update tools
  .tools/phpstan/baseline.neon
  composer.json
Labels: automerge

#5101 MM image_format: Extension bei jpeg korrigiert
  redaxo/src/addons/media_manager/lib/effects/effect_image_format.php
Labels: Bug, Media Manager, automerge

#5102 rex_article_slice: fix getMediaListArray
  redaxo/src/addons/structure/plugins/content/lib/article_slice.php
Labels: automerge

#5112 rex_mediapool_saveMedia() korrigiert
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
Labels: automerge

#5108 rex_var::quote: support null value
  redaxo/src/core/lib/var/var.php
Labels: automerge

#5110 Command assets:sync: Core-Assets-Handling optimiert
  redaxo/src/core/lib/console/assets_sync.php
Labels: automerge

#5109 Package-Cache besser löschen
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/lib/packages/package.php
Labels: automerge

#5111 rex_form: Fieldset mit eckigen Klammern unterstützen
  redaxo/src/core/lib/form/form_base.php
Labels: automerge

#5113 debug: check core config file to decide if clockwork should be turned on
  redaxo/src/addons/debug/boot.php
  redaxo/src/addons/debug/lib/debug_clockwork.php
Labels: Debug, automerge

#5124 Added php8 to blocked extensions
  redaxo/src/addons/mediapool/package.yml
Labels: automerge
