Repository redaxo/redaxo, pull requests merged in 2023-03, with the labels that each got.

#5391 github actions: use rex-console setup
  .github/workflows/default.config.yml.github-action.diff
  .github/workflows/static-analysis.yml
  .github/workflows/styles-compile.yml
  .github/workflows/unit-tests.yml
  .github/workflows/visual-tests.yml
  .php-cs-fixer.dist.php
  .tools/bin/setup
  redaxo/src/core/lib/console/setup/run.php
Labels: automerge

#5635 update tools
  .tools/phpstan/baseline.neon
  composer.json
Labels: automerge

#5622 Feature/allow article list sorting
  redaxo/src/addons/structure/pages/index.php
Labels: Feature, Structure

#5639 fix ajax-loader css
  redaxo/src/addons/be_style/assets/css/styles.css
  redaxo/src/addons/be_style/scss/_base.scss
Labels: automerge

#5641 Tests: Fix sql queries
  redaxo/src/core/tests/list_test.php
  redaxo/src/core/tests/sql/sql_test.php
Labels: automerge

#5640 Überflüssige closing tags
  README.de.md
  redaxo/src/core/fragments/core/be_ooops.php
Labels: automerge

#5638 Update PhpStorm-Inspection-Settings
  .idea/inspectionProfiles/Project_Default.xml
Labels: automerge

#5644 rex_socket: https als Default
  redaxo/src/core/lib/util/socket/socket.php
  redaxo/src/core/lib/util/socket/socket_proxy.php
  redaxo/src/core/tests/util/socket_test.php
Labels: Backwards Incompatible

#5653 SETUP :: new deprecation check for MariaDB, MySQL and PHP versions
  redaxo/src/core/lib/setup/setup.php
Labels: Setup

#5674 Core-Update: Ignorieren, wenn Session schon in DB
  redaxo/src/core/update.php
Labels: automerge

#5676 rex_sql: escape database name in sql
  redaxo/src/core/lib/sql/sql.php
Labels: Security, automerge

#5675 phar:// stream wrapper: Korrekten Dir-Separator nutzen
  redaxo/src/addons/install/lib/archive.php
  redaxo/src/addons/install/lib/package/package_download.php
Labels: automerge
