Repository redaxo/redaxo, pull requests merged in 2023-02, with the labels that each got.

#5555 mediapool: Property types
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/addons/mediapool/lib/form_element/media.php
  redaxo/src/addons/mediapool/lib/form_element/medialist.php
  redaxo/src/addons/mediapool/lib/media.php
  redaxo/src/addons/mediapool/lib/media_category.php
  redaxo/src/addons/mediapool/lib/media_category_select.php
Labels: automerge

#5559 Typo
  redaxo/src/core/lib/extension.php
Labels: automerge

#5550 Addon-Update optimieren
  redaxo/src/addons/install/lib/package/package_update.php
Labels: automerge

#5561 Metainfo: Typ-Ergänzungen
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/addons/metainfo/extensions/extension_cleanup.php
  redaxo/src/addons/metainfo/functions/function_metainfo.php
  redaxo/src/addons/metainfo/install.php
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/metainfo/lib/input.php
  redaxo/src/addons/metainfo/lib/input/date.php
  redaxo/src/addons/metainfo/lib/input/datetime.php
  redaxo/src/addons/metainfo/lib/input/linkbutton.php
  redaxo/src/addons/metainfo/lib/input/linklistbutton.php
  redaxo/src/addons/metainfo/lib/input/mediabutton.php
  redaxo/src/addons/metainfo/lib/input/medialistbutton.php
  redaxo/src/addons/metainfo/lib/input/select.php
  redaxo/src/addons/metainfo/lib/input/text.php
  redaxo/src/addons/metainfo/lib/input/textarea.php
  redaxo/src/addons/metainfo/lib/input/time.php
  redaxo/src/addons/metainfo/lib/table_expander.php
  redaxo/src/addons/metainfo/lib/table_manager.php
Labels: automerge

#5563 Property types
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  psalm.xml
  redaxo/src/addons/structure/tests/category_test.php
  redaxo/src/addons/users/lib/select_element.php
  redaxo/src/core/tests/base/instance_list_pool_trait_test.php
  redaxo/src/core/tests/console/config/set_test.php
  redaxo/src/core/tests/util/i18n_test.php
  redaxo/src/core/tests/util/socket_proxy_test.php
  redaxo/src/core/tests/util/socket_test.php
  redaxo/src/core/tests/util/timer_test.php
Labels: automerge

#5498 Media Manager: AVIF-Unterstützung
  .github/tests-visual/media_manager_settings--dark.png
  .github/tests-visual/media_manager_settings.png
  redaxo/src/addons/media_manager/lang/de_de.lang
  redaxo/src/addons/media_manager/lang/en_gb.lang
  redaxo/src/addons/media_manager/lang/sv_se.lang
  redaxo/src/addons/media_manager/lib/effects/effect_image_format.php
  redaxo/src/addons/media_manager/lib/effects/effect_image_properties.php
  redaxo/src/addons/media_manager/lib/managed_media.php
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/addons/media_manager/pages/settings.php
Labels: Add to Docs, automerge

#5564 Eindeutiger Name für Fremdschlüssel
  redaxo/src/core/install.php
Labels: automerge

#5567 Userssessions nun auch in der Verwaltung verfügbar
  .github/tests-visual/users_edit--dark.png
  .github/tests-visual/users_edit.png
  .github/tests-visual/visual-record.js
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/pages/profile.sessions.php
Labels: automerge

#5570 Syslog: Debug-Meldungen nicht in rot
  redaxo/src/core/pages/system.log.redaxo.php
Labels: automerge

#5572 Exception "Unable to fetch row" optimiert
  redaxo/src/core/lib/sql/sql.php
Labels: automerge

#5571 Update tools, PHPUnit 10
  .gitignore
  .idea/php.xml
  .idea/redaxo.iml
  .tools/bin/update-all
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  composer.json
  phpunit.xml.dist
  redaxo/src/addons/media_manager/tests/media_manager_test.php
  redaxo/src/addons/mediapool/tests/mediapool_test.php
  redaxo/src/addons/structure/plugins/content/tests/article_content_base_test.php
  redaxo/src/addons/structure/plugins/content/tests/article_content_test.php
  redaxo/src/addons/structure/tests/category_test.php
  redaxo/src/addons/structure/tests/function_url_test.php
  redaxo/src/addons/structure/tests/navigation_test.php
  redaxo/src/core/tests/base/instance_list_pool_trait_test.php
  redaxo/src/core/tests/base/instance_pool_trait_test.php
  redaxo/src/core/tests/console/config/get_test.php
  redaxo/src/core/tests/console/config/set_test.php
  redaxo/src/core/tests/login/password_policy_test.php
  redaxo/src/core/tests/packages/package_test.php
  redaxo/src/core/tests/path_test.php
  redaxo/src/core/tests/sql/sql_table_test.php
  redaxo/src/core/tests/sql/sql_test.php
  redaxo/src/core/tests/util/file_test.php
  redaxo/src/core/tests/util/formatter_test.php
  redaxo/src/core/tests/util/log_entry_test.php
  redaxo/src/core/tests/util/log_file_test.php
  redaxo/src/core/tests/util/markdown_test.php
  redaxo/src/core/tests/util/socket_response_test.php
  redaxo/src/core/tests/util/socket_test.php
  redaxo/src/core/tests/util/string_test.php
  redaxo/src/core/tests/util/type_test.php
  redaxo/src/core/tests/util/validator_test.php
  redaxo/src/core/tests/util/version_test.php
  redaxo/src/core/tests/var/var_config_test.php
  redaxo/src/core/tests/var/var_property_test.php
  redaxo/src/core/tests/var/var_test.php
  redaxo/src/core/tests/var/var_test_base.php
Labels: automerge

#5578 rex_escape: bei stdClass neues Objekt erzeugen
  redaxo/src/core/functions/function_rex_escape.php
  redaxo/src/core/tests/functions_test.php
Labels: Bug, automerge

#5581 psalm/phpstan-Präfix entfernt, wo nicht nötig
  .tools/psalm/baseline.xml
  redaxo/src/addons/backup/lib/backup.php
  redaxo/src/addons/cronjob/lib/form.php
  redaxo/src/addons/install/lib/api/api_core_update.php
  redaxo/src/addons/install/lib/package/package_update.php
  redaxo/src/addons/media_manager/lib/media_manager.php
  redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
  redaxo/src/addons/structure/functions/function_rex_url.php
  redaxo/src/addons/structure/lib/service_article.php
  redaxo/src/addons/structure/lib/service_category.php
  redaxo/src/addons/structure/plugins/content/lib/article_slice.php
  redaxo/src/addons/users/lib/role.php
  redaxo/src/core/functions/function_rex_escape.php
  redaxo/src/core/lib/base/instance_list_pool_trait.php
  redaxo/src/core/lib/base/instance_pool_trait.php
  redaxo/src/core/lib/be/navigation.php
  redaxo/src/core/lib/be/page.php
  redaxo/src/core/lib/console/assets_sync.php
  redaxo/src/core/lib/context.php
  redaxo/src/core/lib/extension.php
  redaxo/src/core/lib/extension_point.php
  redaxo/src/core/lib/form/form.php
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/fragment.php
  redaxo/src/core/lib/list.php
  redaxo/src/core/lib/login/api_has_user_session.php
  redaxo/src/core/lib/login/api_user_impersonate.php
  redaxo/src/core/lib/login/complex_perm.php
  redaxo/src/core/lib/login/login.php
  redaxo/src/core/lib/login/user.php
  redaxo/src/core/lib/packages/addons/manager.php
  redaxo/src/core/lib/packages/interface.php
  redaxo/src/core/lib/packages/manager.php
  redaxo/src/core/lib/response.php
  redaxo/src/core/lib/rex.php
  redaxo/src/core/lib/select.php
  redaxo/src/core/lib/setup/import.php
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/lib/sql/table.php
  redaxo/src/core/lib/util/file.php
  redaxo/src/core/lib/util/finder.php
  redaxo/src/core/lib/util/i18n.php
  redaxo/src/core/lib/util/socket/socket.php
  redaxo/src/core/lib/util/timer.php
  redaxo/src/core/lib/util/validation_rule.php
  redaxo/src/core/lib/util/validator.php
  redaxo/src/core/lib/util/version.php
  redaxo/src/core/lib/var/var.php
  redaxo/src/core/lib/view.php
Labels: automerge

#5576 rector: apply ChangeSwitchToMatchRector
  rector.php
  redaxo/src/addons/debug/boot.php
  redaxo/src/addons/media_manager/lib/effects/effect_header.php
  redaxo/src/addons/media_manager/lib/effects/effect_insert_image.php
  redaxo/src/addons/mediapool/lib/cache_media.php
  redaxo/src/addons/metainfo/lib/handler/media_handler.php
  redaxo/src/addons/metainfo/pages/index.php
  redaxo/src/addons/structure/lib/cache_article.php
  redaxo/src/addons/structure/plugins/history/boot.php
  redaxo/src/core/lib/error_handler.php
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/login/password_policy.php
  redaxo/src/core/lib/util/logger.php
  redaxo/src/core/lib/util/sortable_iterator.php
  redaxo/src/core/lib/util/validator.php
  redaxo/src/core/pages/packages.details.php
Labels: automerge

#5579 Nonce an weiteren Stellen nutzen
  redaxo/src/addons/cronjob/pages/cronjobs.php
  redaxo/src/addons/debug/boot.php
  redaxo/src/addons/phpmailer/lib/mailer.php
  redaxo/src/addons/phpmailer/pages/config.php
  redaxo/src/addons/structure/plugins/history/boot.php
  redaxo/src/core/fragments/core/be_ooops.php
  redaxo/src/core/fragments/core/fe_ooops.php
  redaxo/src/core/fragments/core/login_background.php
  redaxo/src/core/lib/error_handler.php
  redaxo/src/core/pages/setup.php
  redaxo/src/core/pages/setup.step2.php
  redaxo/src/core/pages/setup.step5.php
  redaxo/src/core/pages/system.report.markdown.php
Labels: automerge

#5580 Unit-Tests: more types
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/addons/media_manager/tests/media_manager_test.php
  redaxo/src/addons/mediapool/tests/mediapool_test.php
  redaxo/src/addons/structure/tests/category_test.php
  redaxo/src/addons/structure/tests/function_url_test.php
  redaxo/src/core/tests/console/config/get_test.php
  redaxo/src/core/tests/console/config/set_test.php
  redaxo/src/core/tests/login/password_policy_test.php
  redaxo/src/core/tests/packages/package_test.php
  redaxo/src/core/tests/path_test.php
  redaxo/src/core/tests/sql/sql_table_test.php
  redaxo/src/core/tests/sql/sql_test.php
  redaxo/src/core/tests/util/file_test.php
  redaxo/src/core/tests/util/finder_test.php
  redaxo/src/core/tests/util/formatter_test.php
  redaxo/src/core/tests/util/markdown_test.php
  redaxo/src/core/tests/util/socket_response_test.php
  redaxo/src/core/tests/util/socket_test.php
  redaxo/src/core/tests/util/string_test.php
  redaxo/src/core/tests/util/timer_test.php
  redaxo/src/core/tests/util/type_test.php
  redaxo/src/core/tests/util/validator_test.php
  redaxo/src/core/tests/util/version_test.php
  redaxo/src/core/tests/var/var_config_test.php
  redaxo/src/core/tests/var/var_property_test.php
  redaxo/src/core/tests/var/var_test.php
  redaxo/src/core/tests/var/var_test_base.php
Labels: automerge

#5582 dump(): Suchfunktion ermöglichen
  redaxo/src/core/lib/var_dumper.php
Labels: Add to Docs

#5574 Vendor-Updates (whoops-Downgrade)
  composer.json
  redaxo/src/core/composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/ClassLoader.php
  redaxo/src/core/vendor/composer/autoload_real.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Resources/css/prism.css
  redaxo/src/core/vendor/filp/whoops/src/Whoops/Resources/js/prism.js
  redaxo/src/core/vendor/symfony/http-foundation/IpUtils.php
  redaxo/src/core/vendor/voku/anti-xss/src/voku/helper/AntiXSS.php
Labels: automerge

#5494 Backend: Login per Webauthn/Passkey
  .github/tests-visual/backup_export--dark.png
  .github/tests-visual/backup_export.png
  .github/tests-visual/users_edit--dark.png
  .github/tests-visual/users_edit.png
  .tools/bin/update-all
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  composer.json
  redaxo/src/addons/backup/pages/export.php
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/assets/webauthn.js
  redaxo/src/core/backend.php
  redaxo/src/core/composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/install.php
  redaxo/src/core/lang/de_de.lang
  redaxo/src/core/lang/en_gb.lang
  redaxo/src/core/lang/es_es.lang
  redaxo/src/core/lang/nl_nl.lang
  redaxo/src/core/lang/pt_br.lang
  redaxo/src/core/lang/sv_se.lang
  redaxo/src/core/lib/login/api_user_remove_auth_method.php
  redaxo/src/core/lib/login/backend_login.php
  redaxo/src/core/lib/login/login.php
  redaxo/src/core/lib/login/user_session.php
  redaxo/src/core/lib/login/webauthn.php
  redaxo/src/core/lib/setup/import.php
  redaxo/src/core/pages/login.php
  redaxo/src/core/pages/profile.auth_methods.php
  redaxo/src/core/pages/profile.php
  redaxo/src/core/vendor/composer/autoload_classmap.php
  redaxo/src/core/vendor/composer/autoload_psr4.php
  redaxo/src/core/vendor/composer/autoload_static.php
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
  redaxo/src/core/vendor/lbuchs/webauthn/LICENSE
  redaxo/src/core/vendor/lbuchs/webauthn/composer.json
  redaxo/src/core/vendor/lbuchs/webauthn/src/Attestation/AttestationObject.php
  redaxo/src/core/vendor/lbuchs/webauthn/src/Attestation/AuthenticatorData.php
  redaxo/src/core/vendor/lbuchs/webauthn/src/Attestation/Format/AndroidKey.php
  redaxo/src/core/vendor/lbuchs/webauthn/src/Attestation/Format/AndroidSafetyNet.php
  redaxo/src/core/vendor/lbuchs/webauthn/src/Attestation/Format/Apple.php
  redaxo/src/core/vendor/lbuchs/webauthn/src/Attestation/Format/FormatBase.php
  redaxo/src/core/vendor/lbuchs/webauthn/src/Attestation/Format/None.php
  redaxo/src/core/vendor/lbuchs/webauthn/src/Attestation/Format/Packed.php
  redaxo/src/core/vendor/lbuchs/webauthn/src/Attestation/Format/Tpm.php
  redaxo/src/core/vendor/lbuchs/webauthn/src/Attestation/Format/U2f.php
  redaxo/src/core/vendor/lbuchs/webauthn/src/Binary/ByteBuffer.php
  redaxo/src/core/vendor/lbuchs/webauthn/src/CBOR/CborDecoder.php
  redaxo/src/core/vendor/lbuchs/webauthn/src/WebAuthn.php
  redaxo/src/core/vendor/lbuchs/webauthn/src/WebAuthnException.php
Labels: Add to Docs

#5607 fix typo
  redaxo/src/addons/backup/lib/cronjob.php
Labels: automerge

#5606 AVIF fehlte noch an einigen Stellen
  redaxo/src/addons/media_manager/lib/effect_abstract.php
  redaxo/src/addons/media_manager/lib/effects/effect_mirror.php
  redaxo/src/addons/media_manager/lib/effects/effect_workspace.php
  redaxo/src/addons/media_manager/lib/managed_media.php
  redaxo/src/addons/mediapool/package.yml
Labels: automerge

#5602 WebAuthn: require user verification
  redaxo/src/core/lib/login/webauthn.php
Labels: automerge

#5603 Update tools
  .tools/bin/update-all
  .tools/bin/update-tools
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline-taint.xml
  .tools/psalm/baseline.xml
  composer.json
  psalm.xml
Labels: automerge

#5611 Benutzer hinzufügen: Passkeys/Sessions nicht ausgeben
  redaxo/src/addons/users/pages/users.php
Labels: automerge

#5610 MM: in image_format prüfen, ob Formate verfügbar
  redaxo/src/addons/media_manager/lib/effects/effect_image_format.php
Labels: automerge

#5615 Support `PDO::FETCH_KEY_PAIR` in `rex_sql->getArray()`
  .tools/psalm/baseline.xml
  redaxo/src/core/lib/sql/sql.php
  redaxo/src/core/tests/sql/sql_test.php
Labels: automerge

#5619 Vendor-Updates
  composer.json
  redaxo/src/core/composer.json
  redaxo/src/core/composer.lock
  redaxo/src/core/vendor/composer/installed.json
  redaxo/src/core/vendor/composer/installed.php
  redaxo/src/core/vendor/symfony/console/Application.php
  redaxo/src/core/vendor/symfony/console/Helper/ProgressIndicator.php
  redaxo/src/core/vendor/symfony/console/Input/InputArgument.php
  redaxo/src/core/vendor/symfony/console/Input/InputOption.php
  redaxo/src/core/vendor/symfony/console/LICENSE
  redaxo/src/core/vendor/symfony/console/Output/ConsoleSectionOutput.php
  redaxo/src/core/vendor/symfony/console/Style/SymfonyStyle.php
  redaxo/src/core/vendor/symfony/http-foundation/Cookie.php
  redaxo/src/core/vendor/symfony/http-foundation/HeaderUtils.php
  redaxo/src/core/vendor/symfony/http-foundation/LICENSE
  redaxo/src/core/vendor/symfony/http-foundation/Request.php
  redaxo/src/core/vendor/symfony/http-foundation/Response.php
  redaxo/src/core/vendor/symfony/http-foundation/Session/SessionInterface.php
  redaxo/src/core/vendor/symfony/http-foundation/Session/Storage/Handler/NativeFileSessionHandler.php
  redaxo/src/core/vendor/symfony/http-foundation/Session/Storage/Handler/PdoSessionHandler.php
  redaxo/src/core/vendor/symfony/http-foundation/Session/Storage/MetadataBag.php
  redaxo/src/core/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php
  redaxo/src/core/vendor/symfony/http-foundation/Session/Storage/SessionStorageInterface.php
  redaxo/src/core/vendor/symfony/string/AbstractUnicodeString.php
  redaxo/src/core/vendor/symfony/string/LICENSE
  redaxo/src/core/vendor/symfony/var-dumper/Caster/Caster.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/ReflectionCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/Caster/SymfonyCaster.php
  redaxo/src/core/vendor/symfony/var-dumper/LICENSE
  redaxo/src/core/vendor/symfony/yaml/Dumper.php
  redaxo/src/core/vendor/symfony/yaml/LICENSE
Labels: automerge

#5614 URLs einheitlich unescaped ausliefern
  .tools/psalm/baseline.xml
  redaxo/src/addons/cronjob/pages/cronjobs.php
  redaxo/src/addons/debug/lib/debug_clockwork.php
  redaxo/src/addons/media_manager/lib/media_manager.php
  redaxo/src/addons/mediapool/pages/upload.php
  redaxo/src/addons/structure/functions/function_rex_url.php
  redaxo/src/addons/structure/lib/api_functions/api_article_copy.php
  redaxo/src/addons/structure/lib/structure_element.php
  redaxo/src/addons/structure/plugins/content/pages/content.php
  redaxo/src/addons/structure/plugins/history/boot.php
  redaxo/src/core/boot.php
  redaxo/src/core/fragments/core/buttons/button.php
  redaxo/src/core/fragments/core/dropdowns/dropdown.php
  redaxo/src/core/fragments/core/navigations/breadcrumb.php
  redaxo/src/core/fragments/core/navigations/main.php
  redaxo/src/core/fragments/core/navigations/meta.php
  redaxo/src/core/layout/top.php
  redaxo/src/core/lib/api_function.php
  redaxo/src/core/lib/be/controller.php
  redaxo/src/core/lib/be/page.php
  redaxo/src/core/lib/context.php
  redaxo/src/core/lib/form/form_base.php
  redaxo/src/core/lib/list.php
  redaxo/src/core/lib/login/api_user_impersonate.php
  redaxo/src/core/lib/setup/setup.php
  redaxo/src/core/lib/util/string.php
  redaxo/src/core/lib/util/url.php
  redaxo/src/core/pages/profile.php
  redaxo/src/core/pages/system.settings.php
  redaxo/src/core/tests/context_test.php
  redaxo/src/core/tests/util/string_test.php
Labels: Backwards Incompatible
