Repository redaxo/redaxo, pull requests merged in 2024-02, with the labels that each got.

#5883 remove customizer title font-weight
  .github/tests-visual/packages_customizer_installed--dark.png
  .github/tests-visual/packages_customizer_installed.png
  .github/tests-visual/system_customizer--dark.png
  .github/tests-visual/system_customizer.png
  redaxo/src/addons/be_style/plugins/customizer/assets/css/styles.css
Labels: Bug, User Experience (UX)

#5907 Prepared query nutzen
  .tools/psalm/baseline-taint.xml
  redaxo/src/addons/metainfo/lib/table_expander.php
Labels: automerge

#5908 fix psalm MissingTemplateParam
  .tools/phpstan/baseline.neon
  .tools/psalm/baseline.xml
  redaxo/src/addons/structure/plugins/content/lib/extension_point/slice_menu.php
  redaxo/src/core/lib/console/extension_point_console_shutdown.php
Labels: automerge

#5910 config.yml: safe_mode statt safemode
  redaxo/src/core/backend.php
  redaxo/src/core/default.config.yml
  redaxo/src/core/lib/rex.php
  redaxo/src/core/schemas/config.json
Labels: Add to Docs

#5909 Live-Mode einführen
  .tools/psalm/baseline.xml
  redaxo/src/addons/backup/package.yml
  redaxo/src/addons/cronjob/lib/cronjob.php
  redaxo/src/addons/cronjob/lib/manager.php
  redaxo/src/addons/cronjob/package.yml
  redaxo/src/addons/cronjob/pages/cronjobs.php
  redaxo/src/addons/debug/package.yml
  redaxo/src/addons/install/lib/api/api_core_update.php
  redaxo/src/addons/install/lib/api/api_package_add.php
  redaxo/src/addons/install/lib/api/api_package_delete.php
  redaxo/src/addons/install/lib/api/api_package_update.php
  redaxo/src/addons/install/lib/api/api_package_upload.php
  redaxo/src/addons/install/package.yml
  redaxo/src/addons/media_manager/package.yml
  redaxo/src/addons/metainfo/lib/handler/handler.php
  redaxo/src/addons/metainfo/package.yml
  redaxo/src/addons/structure/plugins/content/lib/var_value.php
  redaxo/src/addons/structure/plugins/content/package.yml
  redaxo/src/core/backend.php
  redaxo/src/core/default.config.yml
  redaxo/src/core/lib/be/controller.php
  redaxo/src/core/lib/error_handler.php
  redaxo/src/core/lib/packages/api_package.php
  redaxo/src/core/lib/rex.php
  redaxo/src/core/pages/system.settings.php
  redaxo/src/core/schemas/config.json
  redaxo/src/core/schemas/package.json
  redaxo/src/core/tests/rex_test.php
Labels: Add to Docs

#5914 rex_list: `ORDER BY` nicht mehr per Regex ersetzen
  .tools/psalm/baseline.xml
  redaxo/src/addons/users/pages/users.php
  redaxo/src/core/lib/list.php
Labels: Security

#5920 Media Manager: remove deprecated methods and system types
  redaxo/src/addons/media_manager/lib/managed_media.php
  redaxo/src/addons/media_manager/lib/media_manager.php
Labels: automerge

#5952 Create/Update-Felder korrekt setzen
  redaxo/src/addons/structure/plugins/content/pages/modules.actions.php
  redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
  redaxo/src/addons/structure/plugins/content/pages/templates.php
Labels: Bug

#5953 Structure: Bei Count-Query nicht unnötig sortieren
  redaxo/src/addons/structure/pages/index.php
Labels: automerge

#5958 PHPMailer :: Auslagerung des DetourMode als eigene Methode
  .tools/psalm/baseline.xml
  redaxo/src/addons/phpmailer/lib/mailer.php
Labels: PHPMailer
